### ISSUE TITLE
save video stream?

### ISSUE THREAD

**Issue by katakombi** [pystardust/ytfzf#1]
Thanks for the script, it is really cool!
Would it be possible to implement to dump the video stream into a file?

**Comment by pystardust** [comment]
Thats a built feature of mpv. Press capital Q instead of small q to quit. And your play position will be saved.

**Comment by pystardust** [comment]
I think it would be better to feed it into youtube-dl to save it as a file. All you need to do is replace mpv with youtube-dl. I am thinking of a adding flags to download instead of viewing.

**Comment by pystardust** [comment]
I have added an option to download video
