### ISSUE TITLE
Video playing error 

### ISSUE THREAD

**Issue by Lunatic1985** [pystardust/ytfzf#12]
some videos won't play:

[ytdl_hook] ERROR: requested format not available 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
ERROR[#03]: Couldn't play the video/audio using the current player.
	Try updating youtube-dl

**Comment by danrobi11** [comment]
Please provide the exact ytfzf command you used with the url that doesnt work, that would help.

**Comment by Lunatic1985** [comment]
> Please provide the exact ytfzf command you used with the url that doesnt work. That will help in order to reproduce.
ytfzf garbage the world is not enough                                        
[ytdl_hook] ERROR: requested format not available 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
ERROR[#03]: Couldn't play the video/audio using the current player.
	Try updating youtube-dl
Check for new versions and report at: https://github.com/pystardust/ytfzf

happens with a bunch of videos , works correct randomly  ;)

**Comment by Lunatic1985** [comment]
![2021-02-21_23-06](https://user-images.githubusercontent.com/79431199/108665037-985d4600-7499-11eb-9db7-0cc5b7d26107.png)

**Comment by pystardust** [comment]
This looks like youtube-dl is outdated.

here are possible fixes.
1. update youtube-dl from https://github.com/ytdl-org/youtube-dl , cause it;s usually outdated in the default repos. 
2.  If you have changed the default format in the code, then undo the change. Try passing in the -f  option and choosing one of the available options. Let me know what errors you face.

**Comment by Lunatic1985** [comment]
> This looks like youtube-dl is outdated.
> 
> here are possible fixes.
> 
> 1. update youtube-dl from https://github.com/ytdl-org/youtube-dl , cause it;s usually outdated in the default repos.
> 2. If you have changed the default format in the code, then undo the change. Try passing in the -f  option and choosing one of the available options. Let me know what errors you face.

Yeah just changed the vídeo resolution with echo "ytdl-format=18" >> ~/.config/mpv/mpv.conf, thats all. I'm going to uninstall my version of youtube-dl (Gentoo) and try again tomorrow with another more updated version, thanks for replying.

**Comment by pystardust** [comment]
yt-dl format can be set by an environmental variable now

```
   export  YTFZF_PREF='22'         
```
All be script does is finds url from youtube. You can try copying some links form youtube(browser) and check if your youtube-dl is working.

**Comment by Bugswriter** [comment]
don't use magic numbers like 18 or 22 .. because there is no garantee, instead of magic numbers which have no clear meaning, try- 
ytdl-format="bestvideo[height<=?1080][vcodec!=vp9]+bestaudio/best"

**Comment by pystardust** [comment]
@Bugswriter Thanks, that seems really cool, ill add this to the read me soon.

**Comment by Lunatic1985** [comment]
> yt-dl format can be set by an environmental variable now
> 
> ```
>    export  YTFZF_PREF='22'         
> ```
> 
> All the script does is finds url from youtube and feeds it to mpv/yotube-dl . You can try copying some links form youtube(browser) and check if your youtube-dl is working.

Hi, I completely uninstalled my youtube-dl version, I installed the official one from github, I also reinstalled ytfzf and I still have the same playback problems, some videos work but others do not (same error from my capture). I guess I have bad luck.

**Comment by pystardust** [comment]
One last check, can you manually browser those particular videos that don't work, on a browser.
Take their url, and try
```
mpv "<url>"
```

**Comment by Lunatic1985** [comment]
> One last check, can you manually browser those particular videos that don't work, on a browser.
> Take their url, and try
> 
> ```
> mpv "<url>"
> ```

![2021-02-23_16-21](https://user-images.githubusercontent.com/79431199/108915967-3a447600-75f3-11eb-8351-33767e7394dc.png)

**Comment by westofer** [comment]
@Lunatic1985 , try using `"` (quotation) to avoid shell expansion/escape the slashes and `&`

**Comment by Lunatic1985** [comment]
> @Lunatic1985 , try using `"` (quotation) to avoid shell expansion/escape the slashes and `&`

yeah still happens with the quotation, im cursed  ;D

**Comment by westofer** [comment]
`mpv "https://www.youtube.com/watch?v=pSvH9vH60Ig"` in fish shell works fine for me :/

**Comment by Lunatic1985** [comment]
> `mpv "https://www.youtube.com/watch?v=pSvH9vH60Ig"` in fish shell works fine for me :/

no luck with fish and bash  ;/, but thanks man

**Comment by Lunatic1985** [comment]
> `mpv "https://www.youtube.com/watch?v=pSvH9vH60Ig"` in fish shell works fine for me :/



> `mpv "https://www.youtube.com/watch?v=pSvH9vH60Ig"` in fish shell works fine for me :/

![2021-02-23_23-29](https://user-images.githubusercontent.com/79431199/108952399-025b2400-762f-11eb-9542-8d802b54a4df.png)

**Comment by westofer** [comment]
> Yeah just changed the vídeo resolution with echo "ytdl-format=18" >> ~/.config/mpv/mpv.conf, thats all. I'm going to uninstall my version of youtube-dl (Gentoo) and try again tomorrow with another more updated version, thanks for replying.

formats should be picked from by adding `export YTFZF_PREF="18"` to `.bashrc` or `.zshrc` or `fishrc??`

this is because, if format is not available you then get prompted instead of error

[refer to readme: ](https://github.com/pystardust/ytfzf/blob/master/README.md#format)

**Comment by Lunatic1985** [comment]
> [#12 (comment)](https://github.com/pystardust/ytfzf/issues/12#issuecomment-783138456)
> 
> > Yeah just changed the vídeo resolution with echo "ytdl-format=18" >> ~/.config/mpv/mpv.conf, thats all. I'm going to uninstall my version of youtube-dl (Gentoo) and try again tomorrow with another more updated version, thanks for replying.
> 
> formats should be picked from by adding `export YTFZF_PREF="18"` to `.bashrc` or `.zshrc` or `fishrc??`
> 
> this is because, if format is not available you then get prompted instead of error
> 
> [refer to readme: ](https://github.com/pystardust/ytfzf/blob/master/README.md#format)

![2021-02-23_23-42](https://user-images.githubusercontent.com/79431199/108953468-d8a2fc80-7630-11eb-8887-2cfc9800b242.png)

**Comment by westofer** [comment]
`youtube-dl --version` is latest? 2021.02.22

**Comment by Lunatic1985** [comment]
> `youtube-dl --version` is latest? 2021.02.22

![2021-02-23_23-45](https://user-images.githubusercontent.com/79431199/108953707-418a7480-7631-11eb-9ea4-02b2744f8eba.png)     yes, latest youtube-dl

**Comment by westofer** [comment]
@pystardust any ideas?

**Comment by Lunatic1985** [comment]
> @pystardust any ideas?

hey man it's fine, I'm going to leave it for now, I'll keep looking at the project :)
