### ISSUE TITLE
Is there a way to use ytfzf from inside rofi-script?

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#120]
Hi, I'd like to be able to do something like this (to only have one shortcut to invoke `rofi`):
```
rofi  -modi run,file-browser,"CALC:qalc +u8","youtube:/usr/bin/ytfzf -D" \
        -show run \
        -display-drun "Run" \
        -display-file-browser FILES \
        -display-run SHELL \
        -columns 2
```
As I am switching modes I get an error message for `ytfzf` "Do not launch..". I am not sure if it's possible to achieve this functionality but it would be great if that's possible. Thanks.

**Comment by Euro20179** [comment]
when i tried this and my YTFZF_EXTMENU was set to rofi, i got an error saying i had 2 instances of rofi running, so i set YTFZF_EXTMENU to a path to this script (make sure the script has execute permissions)
```sh
#!/bin/sh

killall -9 rofi
rofi -dmenu -fuzzy -width 1500
```

**Comment by jose1711** [comment]
Thank you. Actually I was provided an alternative solution by folks on IRC. It goes like this:

```
rofi -modi run,youtube:~/bin/rofi.sh -show youtube
```

Contents of `~/bin/rofi.sh`:
```
#!/bin/bash
if [ -n "$1" ]
then
  case "$1" in
    "youtube")
       coproc ( ytfzf -D >/dev/null 2>&1 )
       ;;
  esac
else
  echo "youtube"
  echo "exit"
fi
```

**Comment by pystardust** [comment]
Oh thats great. If there is anything else let us know. I am closing the issue
