### ISSUE TITLE
Invalid parsing of YTFZF_EXTMENU

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#129]
Seems parsing of YTFZF_EXTMENU variable containing blanks is broken. Here's an attempt to set prompt to `Search Youtube`:
```
YTFZF_EXTMENU='dmenu -i -l 15 -p "Search Youtube"' ytfzf -D
```
This results in
![obrázok](https://user-images.githubusercontent.com/1406222/110698084-7e3b9b80-81ed-11eb-9ab6-48f88678694e.png)

**Comment by pystardust** [comment]
The line has been changes as suggested by Euro20179.  Update `ytfzf` and try again
```sh
ytfzf --update
```

**Comment by jose1711** [comment]
thank you for a quick fix. closing
