### ISSUE TITLE
not work in dmenu mode

### ISSUE THREAD

**Issue by mrbooshehri** [pystardust/ytfzf#14]
I've got ytfzf from AUR and this is the output:

ytfzf -D starboy
usage: dmenu [-bvcfsxF] [-l lines] [-p prompt] [-fn font] [-m monitor]
             [-nb color] [-nf color] [-sb color] [-sf color] [-w windowid]
             [-bw width] [-hb color] [-hf color] [-hp items] [-h height]
 [-nhb color] [-nhf color] [-shb color] [-shf color]
Usage: ytfzf <search query>
     ytfzf -h         # to show help text

**Comment by pystardust** [comment]
Now dmenu doesnt take in query that way.
do 
```
ytfzf -D
```
it'll prompt you to search.
Tell me how it goes

**Comment by mrbooshehri** [comment]
not difference
output: 

ytfzf -D
usage: dmenu [-bvcfsxF] [-l lines] [-p prompt] [-fn font] [-m monitor]
             [-nb color] [-nf color] [-sb color] [-sf color] [-w windowid]
             [-bw width] [-hb color] [-hf color] [-hp items] [-h height]
 [-nhb color] [-nhf color] [-shb color] [-shf color]
Usage: ytfzf <search query>
ytfzf -h         # to show help text

**Comment by westofer** [comment]
@mrbooshehri 
does `pacman -Q ytfzf-git`  output `r64.36b7de7-3`?

if not please upgrade ytfzf `yay -Sua` or `paru -Sua`

**Comment by pystardust** [comment]
Did you patch you dmenu? 

Check if the following command works
```
seq 10 | dmenu -i -l 30 -p search
```

**Comment by mrbooshehri** [comment]
> @mrbooshehri
> does `pacman -Q ytfzf-git` output `r64.36b7de7-3`?
> 
> if not please upgrade ytfzf `yay -Sua` or `paru -Sua`

this is the output of the command, seems i'm using the latest version

pacman -Q ytfzf-git
ytfzf-git r64.36b7de7-3

**Comment by mrbooshehri** [comment]
> Did you patch you dmenu?
> 
> Check if the following command works
> 
> ```
> seq 10 | dmenu -i -l 30 -p search
> ```

yes I applied some patches on my dmenu. the -i switch which you mentioned does not exist in mine.
bye the way i'm using dmenu-5.0.

**Comment by pystardust** [comment]
-i gives case insensitive searching
Since your build of dmenu doesnt seem to have it you could run
```
YTFZF_EXTMENU=" dmenu -l 30 -p search "  ytfzf -D
```
Or export the variable and use `ytfzf -D`

**Comment by batbatxyz** [comment]
I had the same issue and fixed it by editing the ytfzf script in vim to remove the -i from the dmenu command
I have another issue with dmenu regarding the alignment of the video details. The image below shows what I'm talking about.
![2021-02-22-194137_1184x965_scrot](https://user-images.githubusercontent.com/79488675/108788429-efb8f000-7545-11eb-9aba-b2c785ce35ba.png)
My dmenu is pretty heavily patched, so could that be causing it or is this an issue with ytfzf? I'd love any help you could provide.

Also, since this is another issue related to dmenu I posted it in this issue thread, but if you would like me to start a new one, let me know.

**Comment by mrbooshehri** [comment]
> I had the same issue and fixed it by editing the ytfzf script in vim to remove the -i from the dmenu command
> 
> I have another issue with dmenu regarding the alignment of the video details. The image below shows what I'm talking about.
> ![2021-02-22-194137_1184x965_scrot](https://user-images.githubusercontent.com/79488675/108788429-efb8f000-7545-11eb-9aba-b2c785ce35ba.png)
> The details of the videos in separate lines are not aligned correctly as they are in fzf mode which makes for the messy look shown above.
> 
> My dmenu is pretty heavily patched, so could that be causing it or is this an issue with ytfzf? I'd love any help you could provide.
> 
> Also, since this is another issue related to dmenu I posted it in this issue thread, but if you would like me to start a new one, let me know.

Thanks so much, it works for me too

**Comment by pystardust** [comment]
This is my vanilla build of dmenu, I will need to look at the patched being used
![2021-02-23-123126_1920x1080_scrot](https://user-images.githubusercontent.com/79201151/108811490-66e89580-75d3-11eb-8888-662a556fcec1.png)

**Comment by westofer** [comment]
@mrbooshehri try using a monospace font

**Comment by pystardust** [comment]
> This is my vanilla build of dmenu, I will need to look at the patched being used
> ![2021-02-23-123126_1920x1080_scrot](https://user-images.githubusercontent.com/79201151/108811490-66e89580-75d3-11eb-8888-662a556fcec1.png)

 As @westofer has mention, I am using hack font (monospace)

**Comment by mrbooshehri** [comment]
> @mrbooshehri try using a monospace font

Thanks, I will try it

**Comment by pystardust** [comment]
@westofer Should we remove the `-i` option of dmenu from defaults?
As 2 people have faced this issue. But with out the `-i` option searching becomes much harder.

**Comment by westofer** [comment]
yeah sound good.
btw can the titles be converted to lower case?

**Comment by mrbooshehri** [comment]
> @westofer Should we remove the `-i` option of dmenu from defaults?
> As 2 people have faced this issue. But with out the `-i` option searching becomes much harder.

I just used it without -i in couple of hours and it works smooth and nice. I will inform you if any problem happens due to this change.

**Comment by pystardust** [comment]
> yeah sound good.
> btw can the titles be converted to lower case?

I would not look good being lower case. 
I just cloned dmenu from its suckless, it has -i by default.

**Comment by pystardust** [comment]
We can reopen this if anyone else has an issue

**Comment by mrbooshehri** [comment]
> > yeah sound good.
> > btw can the titles be converted to lower case?
> 
> It would not look good being lower case. 
> I just cloned dmenu from its suckless, it has -i by default.

I guess the missing -i option is because the fzf patch wich I applied to my dmenu.

**Comment by KaoriRinaFujimoto** [comment]
had the same issue, in my case however it collided with the [case-insensitive](https://tools.suckless.org/dmenu/patches/case-insensitive/) patch.  
I just re-added the `-i` option into `dmenu.c` and now everything is working as expected.
