### ISSUE TITLE
Latest release removes the loading screen (when used with -t)

### ISSUE THREAD

**Issue by paniash** [pystardust/ytfzf#145]
After the recent update, running `ytfzf -t` to view thumbnails does not show a loading screen i.e. `Loading thumbnails....` as before. The progress of the thumbnail downloads could be checked with the number of dots (...) earlier. I suggest bringing this back. A workaround would be to set this `Loading thumbnails...` as a default and remove it only when used with a `-q` or `--quiet` option.

**Comment by pystardust** [comment]
Removing the Loading seems to increase the speed by about `0.2` seconds. So we decided to remove it all together. Maybe we can add it as you said.

**Comment by paniash** [comment]
If it increases speed, then it's all the more better. Atleast a static loading page saying that the thumbnails are being downloaded would be nice (no need of increasing dots).

**Comment by pystardust** [comment]
I have added loading messages for scraping and thumbnail downloads @paniash

**Comment by paniash** [comment]
@pystardust After updating `ytfzf`, I don't see a loading message. Did you add it as an optional argument?
