### ISSUE TITLE
ytfzf -t: invalid preview window layout: left:50%:noborder:wrap

### ISSUE THREAD

**Issue by qquq** [pystardust/ytfzf#151]
ytfzf is unable to show thumbnail.
After invoking command ytfzf -t [whatever] it returns:
_invalid preview window layout: left:50%:noborder:wrap_
Setting _--preview-side=right_ has no effect.
App's versions:
ytfzf 1.1.0 (installed through pip)
ueberzug 18.1.9 (installed through pip)
The rest of dependencies comes from repo (debian stable).

**Comment by westofer** [comment]
can you post the output of `ytfzf --version`

I assume the bug is because of outdate fzf version

**Comment by qquq** [comment]
The version is 0.17.5. Thanks for pointing out the older bugreport. I've installed the newest version from github and it works fine now.
