### ISSUE TITLE
Thumbnails don't work when using hidepid

### ISSUE THREAD

**Issue by Kodmod** [pystardust/ytfzf#157]
This may be too specific to even consider.

The kernel has the ability to hide processes for security (see [ArchWiki](https://wiki.archlinux.org/index.php/Security#hidepid)). When this is active, the thumbnails are never shown, presumably because the script is unable to get the `$PROC_ID`. Is there any way around this besides disabling `hidepid`?

**Comment by pystardust** [comment]
PID is used to facilitate multiple sessions of ytfzf running at the same time.
We could disable this feature and everything would work fine as long as only one ytfzf session is open at a time.
Apply thid diff the master branch
```diff
diff --git a/ytfzf b/ytfzf
index 7453e63..f59387d 100755
--- a/ytfzf
+++ b/ytfzf
@@ -106,10 +106,6 @@ scrape="${scrape-yt_search}"
 [ -z "$TTY_COLS" ] && export TTY_COLS="$(tput cols)"
 #variable used for when this process spawns subprocesses and there needs to be a unique value (ueberzug)
 #this could be any unique value, $$ is used because it is the most easily accessible unique value
-if [ -z "$PROC_ID" ] ; then
-	export PROC_ID="$$"
-	echo "$$" >> "$pid_file"
-fi
 
 #dependency check
 dep_ck () {
@@ -321,7 +317,7 @@ video_menu () {
 #the is doesn't have to be the $$ it just has to be unique for each instance of the script
 #$$ is the easiest unique value to access that I could think of
 
-FIFO="/tmp/ytfzf-ueberzug-fifo-$PROC_ID"
+FIFO="/tmp/ytfzf-ueberzug-fifo"
 ID="ytfzf-ueberzug"
 WIDTH=$FZF_PREVIEW_COLUMNS
 HEIGHT=$FZF_PREVIEW_LINES
@@ -699,14 +695,7 @@ play_url () {
 }
 #> Checks if other sessions are running, if not then deletes thumbnails
 delete_thumbnails () {
-	session_count=0
-	while read -r pid; do
-		[ -d /proc/"$pid" ] && session_count=$(( session_count + 1 ))
-	done < "$pid_file"
-	if [ $session_count -eq 1 ] ; then
-		[ -d "$thumb_dir" ] && rm -r "$thumb_dir"
-		printf "" > "$pid_file"
-	fi
+	[ -d "$thumb_dir" ] && rm -r "$thumb_dir"
 }
 #> Save and clean up before script exits
 save_before_exit () {

```

**Comment by Kodmod** [comment]
Hmm, strange. I applied the patch and thumbnails still don't load. All I get is the 'loading' animation at the top right. I'm sure that the `hidepid` thing is the problem though, as thumbnails work when I comment out the line in `fstab`.

**Comment by pystardust** [comment]
```sh
#!/bin/sh

[ -z "$TTY_COLS" ] && export TTY_COLS="$(tput cols)"
FIFO="/tmp/ytfzf-test-pipe"



start_ub () {
	[ -e "$FIFO" ] || mkfifo "$FIFO"
	# To keep fifo open
	ueberzug layer --parser json < "$FIFO" & 
	exec 3>"$FIFO"
}
stop_ub () {
	# close the redirection
	exec 3>&-
	rm "$FIFO" 
}


preview_img () {
	WIDTH=$FZF_PREVIEW_COLUMNS
	HEIGHT=$FZF_PREVIEW_LINES

	printf "%s : %s\n" "tty_cols" "$TTY_COLS"
	printf "%s : %s\n" "fzf_width" "$WIDTH"

	thumb_width=$WIDTH
	thumb_height=$((HEIGHT - 2))

	thumb_x=$(($TTY_COLS / 2 + 3))
	thumb_y=10
	read ueberzug_info << EOF
{ "action": "add", "identifier": "test", "path": "$1", "x": $thumb_x, "y": $thumb_y, "scaler": "fit_contain", "width": $thumb_width, "height": $thumb_height }
EOF
	printf "%s\n" "$ueberzug_info" > "$FIFO"
}

remove_img () {
	read ueberzug_info << EOF
{ "action": "remove", "identifier": "test" }
EOF
	printf "%s\n" "$ueberzug_info" > "$FIFO"
}

if [ "$#" -ge 1 ]; then
	regex='.*\.(png|jpg|gif)$'
	echo "$1" | grep -E -q "$regex" && { preview_img "$1" ; exit; }
	remove_img
	[ -d "$1" ] && { ls "$1" ; exit ; } || { cat "$1" ;}
	exit;
fi


start_ub
ls -1 | fzf --preview-window "right:50%:wrap" \
	--preview "sh $0 {}"
stop_ub
```
This is a small script I wrote to debug ueberzug. 
Run this script in a directory with images.
`./ubprev`

**Comment by Kodmod** [comment]
Ran the script in the `thumb` directory. This is the output:
![screenpic](https://user-images.githubusercontent.com/43139541/111911687-d9c81d80-8a66-11eb-934e-550d92903bfb.JPG)

**Comment by pystardust** [comment]
It seems like ueberzug needs to get process info. The script currently relies on ueberzug for thumbnails. We would look into adding  another option to display images, maybe using an external viewer like (sxiv).

**Comment by Kodmod** [comment]
For others experiencing this issue; there may be a workaround using `gid` where you specify a group that can view all processes (see [here](https://www.cyberciti.biz/faq/linux-hide-processes-from-other-users/)), and then running `ytfzf` via `sg` as that group. Haven't been able to get it to work so far, though.

**Comment by Kodmod** [comment]
I'm not exactly sure how or why but thumbnails work now. Maybe `ueberzug` has been updated?

**Comment by pystardust** [comment]
Thats great. It has to be something with ueberzug. Is the above script is working?

**Comment by Kodmod** [comment]
Yea, it's all working, strangely enough. I guess you can go ahead and close the issue.

**Comment by pystardust** [comment]
Maybe someone had raised this issue with Ueberzug.
