### ISSUE TITLE
[Bug] Sample Configuration File Uses /thumb as thumb_dir

### ISSUE THREAD

**Issue by aaronhatesregex** [pystardust/ytfzf#158]
The title may not be very clear.

## Steps to produce

- Download latest ytfzf and sample conf from master branch.
- Move the conf to ~/.config/ytfzf.conf.sh as suggested
- Run ytfzf without any argument
- `mkdir: cannot create directory ‘/thumb’: Permission denied`

## Expected behavior

It should run without issue.

## Additional infomation

It works when I remove the conf elsewhere. A possible workaround is to set the varaibles to the followings:

    # Note the slash "/"
    cache_dir="$HOME/.cache/ytfzf/"
    thumb_dir="${YTFZF_CACHE}thumb"
    # These two doesn't matter
    #history_file="${YTFZF_CACHE}ytfzf_hst"
    #current_file="${YTFZF_CACHE}ytfzf_cur"

But it's kinda ugly. ☹️ Yet another frustrating Shell *feature*™️.

**Comment by Euro20179** [comment]
in .config/ytfzf/conf.sh change `thumb_dir="$YTFZF_CACHE/thumb"` to `thumb_dir="$cache_dir/thumb"`, in conf.sh references to YTFZF_CACHE should be to cache_dir instead

**Comment by aaronhatesregex** [comment]
Oh I see the problem, close the issue now that it's fixed.
