### ISSUE TITLE
Add video looping

### ISSUE THREAD

**Issue by PlanetNoobGotHacked** [pystardust/ytfzf#160]
Please include video looping. Whenever I listen to a song on ytfzf (if its not on spotify) I want it to be looped instead of repeating the command again.

**Comment by pystardust** [comment]
If you are talking about looping a single video/audio then there are 2 ways

1. You could press `L` on the video/audio (mpv) to make it loop.
2.  You could change your `YTFZF_PLAYER` to mpv with the loop option
```sh
# video loop
YTFZF_PLAYER='mpv --loop' ytfzf -t  <Search> 
# Audio loop
YTFZF_PLAYER_FORMAT="mpv --loop --ytdl-format=" ytfzf -m <Search>
```
If you would like to always have these features then export these variables or add them to your the ytfzf config file

**Comment by PlanetNoobGotHacked** [comment]
Oh! I never knew that you could press L for it to loop.
