### ISSUE TITLE
[Question] Preserving column width when using Rofi?

### ISSUE THREAD

**Issue by ceuk** [pystardust/ytfzf#172]
Is there a way to get the columns to line up using rofi? They're all over the place for me

**Comment by pystardust** [comment]
Use a monospace font to make columns align.
If the column in too big for rofi, then you could either modify rofi to make it bigger
```
rofi -dmenu -fuzzy -width 1500
```
Or you could tell ytfzf to reduce the size of the column, by exporting
```
YTFZF_EXTMENU_LEN=160
```
Try doing altering both of this together

**Comment by ceuk** [comment]
ah man it even says that on the rofi man page - sorry. Thanks for the quick reply, completely sorted
