### ISSUE TITLE
nohup / fork

### ISSUE THREAD

**Issue by tamis-laan** [pystardust/ytfzf#174]
I usually search for multiple videos and play them one by one or keep them open for later. 

Currently when starting one or multiple videos the mpv process stays attached to the terminal. It would be nice if we could detach it  as a seperate process for example by using `shift enter`. 

This way the terminal window can be used for the next ytfzf search.

**Comment by pystardust** [comment]
You could use a custom player to achieve this
Using **Task spooler**:
```sh
YTFZF_PLAYER='tsp mpv' ytfzf -tl "search"
```
Using **mpv wrapper**:
Make a script for mpv wrapper as follows 
```sh
#!/bin/sh
setsid --fork mpv $@ 1>/dev/null 2>&1
```
Make it executable in some location, then
```sh
YTFZF_PLAYER='/path/to/script' ytfzf -tl "search"
```

These variables can also be set in the conf.sh or exported in the shell configs

**Comment by tamis-laan** [comment]
For reference:
```
#!/bin/sh

# Fork mpv
fmpv() {
	setsid --fork mpv $@ 1>/dev/null 2>&1
}

# Set forked mpv
YTFZF_PLAYER="fmpv"
```
Works for me but a build in option would be nice. Infact I would expect this to be default behavior and having some short cut to keep the video attached to the shell for debugging purposes.

**Comment by tamis-laan** [comment]
The interesting bit is that adding `YTFZF_PREF="[height <=? 720]"` to the `config.sh` makes `ytfzf` ignore `YTFZF_PLAYER` and the above solution no longer works.

**Comment by pystardust** [comment]
For that you would also need to set the `YTFZF_PLAYER_FORMAT`
Similar to what I have done above but, use `mpv --ytdl-format=`

For example
```sh
#!/bin/sh
setsid --fork mpv --ytdl-format=$@ 1>/dev/null 2>&1
```

and run
```sh
YTFZF_PLAYER_FORMAT=~/mpvwrapper_format' ' ytfzf -t luke smith
```

Notice there should be a space after the path of the script. I used quotes to add a space, you could do something line `"/path/to/script "`, with out the extra space you would get an error.
This is getting really ugly, I think it would be better to let the user define their own player function in the conf.sh

**Comment by tamis-laan** [comment]
Ah I see, in that case I'd rather use it inside `YTFF_PLAYER`

``` bash 
# Fork mpv
fmpv() {
	setsid --fork mpv --ytdl-format="[height <=? 1080]" $@ 1>/dev/null 2>&1
}

# Set forked mpv
YTFZF_PLAYER="fmpv"
```
