### ISSUE TITLE
Devour doesn't work in i3

### ISSUE THREAD

**Issue by Protocol2** [pystardust/ytfzf#176]
When using the optional:
```
export YTFZF_PLAYER="devour mpv"
export YTFZF_PLAYER_FORMAT="devour mpv --ytdl-format="
```
The command 'ytfzf -t' will launch properly with thumbnail support on urxvt. Also, when I select a video and play it, the devour works as intended. However, when I add this line to my i3 config file:

`bindsym $mod+y exec urxvt -e ytfzf -t`

It doesn't work. Whenevery I press my $mod+y keybinding ytfzf launches with thumbnail support, but still outputs redundant information in a terminal window whilst opening the video in a new window, which was what I wanted to avoid using devour.

**Comment by westofer** [comment]
do you use `~/.config/ytfzf/conf.sh` as the config location? 

iirc the variables in `.zshrc` and `.bashrc` dont get sourced when launching a terminal with a command directly (`urxvt -e ytfzf`)

incase you use `~/.config/ytfzf/conf.sh` it doesn't require `export`

(unrelated: look into dmenu/rofi flag `-D` it should be better for binding)

**Comment by Protocol2** [comment]
I did what you said, and somehow it works now. I actually tried your solution before, which at the time did not solve the issue for me, which is why I opened this. I must have done something wrong the last time I tried because it works fine now. Thanks!

**Comment by westofer** [comment]
np!, please close it if it is resloved :D
