### ISSUE TITLE
last colume in search

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#18]
What is the last colume F=$url [0jfa008004eh] displayed for?

Very nice script by the way,  Thanks

**Comment by pystardust** [comment]
It is to uniquely identify a video.
I could have removed it and  researched the field using grep but that doesnt work 100% with some titles having wierd characters.

I will remove the urls and replace them by serial numbers to make it look clean.

One more solution is to alter the width, if the width is big enough the url will be hidden. Ill add this as a default in the fzf version.

**Comment by se7en-x230** [comment]
Excellent idea with the ID looks much cleaner.
My 14" x230 has not much screen :)

Finally a usable solution with the most amount of Info's.
Especially with the youtube-dowoad mpv plugin.

Love the work.

**Comment by pystardust** [comment]
Thankyou,

I am not a programmer, and this is my first proper project.  Please do let me know if you find me making mistakes.

The current version auto resizes the search result fields based on the terminal size.
```
format_fzf () {
	dur_len=7
	view_len=10
	date_len=14
	url_len=12

	t_size="$(stty size | cut -f2 -d' ')"    # This gives you terminal size
	if [ $t_size -lt 75 ]; then
		# title channel
		frac=$(((t_size - 1)/4))
		title_len=$((frac * 3))
		channel_len=$((frac * 1 + 7))
	elif [ $t_size -lt 95 ]; then
		# title channel time
		frac=$(((t_size - 4)/8))
		title_len=$((frac * 5 - 1))
		channel_len=$((frac * 2 - 1))
		dur_len=$((frac * 1 + 10))
	elif [ $t_size -lt 110 ]; then
		# title channel time views
		frac=$(((t_size - 1)/9))
		title_len=$((frac * 5 ))
		channel_len=$((frac * 2 ))
		dur_len=$((frac * 1))
		view_len=$((frac * 1 + 7))
	elif [ $t_size -lt 130 ]; then
		# title channel time views date
		frac=$(((t_size - 5)/11))
		title_len=$((frac * 5 - 1))
		channel_len=$((frac * 2))
		dur_len=$((frac * 1))
		view_len=$((frac * 1))
		date_len=$((frac * 2 + 20))
	else    # all
		frac=$(((t_size - 5 - 12)/11))
		title_len=$((frac * 6 - 1))
		channel_len=$((frac * 3/2))
		dur_len=$((frac * 1))
		view_len=$((frac * 1))
-		date_len=$((frac * 3/2 ))
+		date_len=$((frac * 3/2 + 20 ))
	fi
}
```

One solution could be to push the url to the right by changing the last line as such

**Comment by pystardust** [comment]
I have updated fzf formatting to hide the urls

**Comment by se7en-x230** [comment]
that's how it looks on a 14" 
https://imagebin.ca/v/5slnhrIkHgzP

Thanks

**Comment by pystardust** [comment]
The image doesnt seem to open can you send again.

**Comment by westofer** [comment]
![image](https://user-images.githubusercontent.com/50760091/109028802-3d169800-76d3-11eb-89ad-998092699458.png)

**Comment by pystardust** [comment]
Okay, so the width is too much since your screen size is low.
```sh
YTFZF_EXTMENU_LEN=150 ytfzf -D
```
Run this for different values, till you find something you are comfortable with .
Then export it in your rc files (example: ~/.bashrc)
```sh
export YTFZF_EXTMENU_LEN=150
```

**Comment by pystardust** [comment]
@se7en-x230 
Let me know if this solves the width issue you are facing.
