### ISSUE TITLE
Include invidious instances and Lbry?

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [pystardust/ytfzf#185]
Hello, thanks for the awesome project!

Do you have any plans to add option to use invidious instances  instead of YouTube? Invidious instances are a web frontend to youtube and act like a proxy. People use them to avoid being tracked by YouTube.

What about LBRY? It's a protocol that uses blockchain for users to share media (videos/books/photos/etc). The main frontend website to LBRY is odysee.com, which looks like YouTube.

Since it ytfzf is for youtube. it may not make sense to add LBRY, but I guess it does make sense to add option to use invidious instances.

**Comment by westofer** [comment]
see #59

**Comment by AndreSouzaAbreu** [comment]
Oh I see. It's near the same thing

> see #59
