### ISSUE TITLE
ueberzug not found. Please install it. 

### ISSUE THREAD

**Issue by andradei** [pystardust/ytfzf#189]
Installed ueberzug using `pip`, but ytfzf isn't finding it.

Script I used to install:

```bash
#! /bin/bash

set -e

# Install some dependecies via apt

sudo apt update -y
sudo apt install -y jq mpv fzf python3-pip libx11-dev libxext-dev

# MAYBE I'LL REGRET THIS

ln -s /usr/bin/python3 /usr/bin/python

# Install youtube-dl

sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

# Install ueberzug with python3 pip

pip install ueberzug

# install ytfzf

curl -sL "https://raw.githubusercontent.com/pystardust/ytfzf/master/ytfzf" | sudo tee /usr/bin/ytfzf >/dev/null && sudo chmod 755 /usr/bin/ytfzf
```

But using the thumbnails option won't work:

```
> ytfzf -t 'something'
Scraping Youtube...
Downloading Thumbnails...
ueberzug not found. Please install it.
```

**Comment by aris-sk** [comment]
> Installed ueberzug using `pip`, but ytfzf isn't finding it.
> 
> Script I used to install:
> 
> ```shell
> #! /bin/bash
> 
> set -e
> 
> # Install some dependecies via apt
> 
> sudo apt update -y
> sudo apt install -y jq mpv fzf python3-pip libx11-dev libxext-dev
> 
> # MAYBE I'LL REGRET THIS
> 
> ln -s /usr/bin/python3 /usr/bin/python
> 
> # Install youtube-dl
> 
> sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
> sudo chmod a+rx /usr/local/bin/youtube-dl
> 
> # Install ueberzug with python3 pip
> 
> pip install ueberzug
> 
> # install ytfzf
> 
> curl -sL "https://raw.githubusercontent.com/pystardust/ytfzf/master/ytfzf" | sudo tee /usr/bin/ytfzf >/dev/null && sudo chmod 755 /usr/bin/ytfzf
> ```
> 
> But using the thumbnails option won't work:
> 
> ```
> > ytfzf -t 'something'
> Scraping Youtube...
> Downloading Thumbnails...
> ueberzug not found. Please install it.
> ```

maybe:

sudo -H pip3 install ueberzug

and try again

**Comment by aimad10** [comment]
https://stackoverflow.com/questions/66515192/pip3-failed-to-build-ueberzug

This happened to me yesterday when I was trying to install it. Make sure you have all dependencies. Wish I didn't sound condescending when I wrote this.

**Comment by aris-sk** [comment]
> https://stackoverflow.com/questions/66515192/pip3-failed-to-build-ueberzug
> 
> This happened to me yesterday when I was trying to install it. Make sure you have all dependencies. Wish I didn't sound condescending when I wrote this.

Have u upgraded your system's python version and pip manually?
What is the output of command:

python3 --version

if you have installed more python3 versions in your system (for example 3.7 and 3.8, maybe you need to use the pip version for the active global version. In this case pip3.8 would resolve to pip from the Python 3.8 installation, pip3.7 would resolve to pip from the Python 3.7

So maybe check your systemwide active version with python3 --version command, and use the approriate pip. 

e.g. sudo -H pip3.7 install ueberzug

**Comment by aimad10** [comment]
> > 
> 
> Have u upgraded your system's python version and pip manually?

I think one of the two of us is confused. I was adding on to what you were saying, I'm not the OP. If you did mean to reply to me, I'm confused, but the output of python3 --version is 3.8.6 .

**Comment by aris-sk** [comment]
Ah, nope..my mistake

**Comment by aris-sk** [comment]
> > > 
> > 
> > 
> > Have u upgraded your system's python version and pip manually?
> 
> I think one of the two of us is confused. I was adding on to what you were saying, I'm not the OP. If you did mean to reply to me, I'm confused, but the output of python3 --version is 3.8.6 .

Ah, nope my mistake

**Comment by andradei** [comment]
`sudo -H pip3 install ueberzug` worked. Would be nice if it were documented somewhere (not even ueberzug itself has this documented) for users that aren't acquainted with the python ecosystem.
