### ISSUE TITLE
Support for standard input

### ISSUE THREAD

**Issue by paniash** [pystardust/ytfzf#19]
Hi! Is it possible to add standard input (if not already done) to be used in other scripts?

Great project btw :-)

**Comment by pystardust** [comment]
yes, I will add it.

Is it okay if suppose you put `ytfzf  - ` instead of a query then in take stdin?

**Comment by paniash** [comment]
> Is it okay if suppose you put `ytfzf - ` instead of a query then in take stdin?

Yes. Thanks!

**Comment by pystardust** [comment]
I have added, check the readme for the same
