### ISSUE TITLE
[enhancement] add preferred subtitles and add a sorting method for subscriptions

### ISSUE THREAD

**Issue by aimad10** [pystardust/ytfzf#190]
Hello, I was trying to add the following features but I am terrible at programming and like using keyboard shortcuts. 

1. have a config setting to select preferred subtitles. Right now, I have to add --subt to my query and then choose the video, and then choose the language. It would be nice if I could just have it auto select my preferred language (english) and then just not have subtitles if they aren't available instead of having to choose the same thing from the menu everytime I choose a video. 
2. add a sorting method for the subscriptions. Right now it seems that if I do ytfzf -S, it lists the different channels in a random? order, and then lists the videos that the channel posted in chronological order. It would be nice if it were to display the channels in chronological order based on the most recent video, so if a channel posts, it get bumped up to the top of the order.

How it is right now:
---CHANNEL A--- 
video1 -- 2 min ago
video2 -- 2 weeks ago
video3 -- 1 year ago

---CHANNEL B---
video1 -- 1 week ago
video2 -- 2 months ago
video3 -- 7 years ago

---CHANNEL C---
video1 -- six seconds ago
video2 -- 2 min ago
video3 -- 3 weeks ago

How I propose it should be:

---CHANNEL C---
video1 -- six seconds ago
video2 -- 2 min ago
video3 -- 3 weeks ago

---CHANNEL A--- 
video1 -- 2 min ago
video2 -- 2 weeks ago
video3 -- 1 year ago

---CHANNEL B---
video1 -- 1 week ago
video2 -- 2 months ago
video3 -- 7 years ago

Not sure if this is the right place to do this but really, thanks for making this. I use linux inside of a VM in windows so I can play games and use linux at the same time, and this tool fixed adblock and the framskipping issues at once. Really glad you made this.

**Comment by westofer** [comment]
for number 1
there are few options


## Using "YTFZF_SELECTED_SUB", I didn't test it, it is not stable yet

look at pull request #193 for details


## Using mpv config

add to `~/.config/mpv/mpv.conf` the following line

    slang="your-language-code,second-prefered langauge"
    
    # Example, use english, if not avialble use japanese
    slang="en,jpn"

## Using YTFZF vars

change mpv options ONLY when used with ytfzf

in `~/.config/ytfzf/conf.sh` add the following line

    YTFZF_PLAYER="mpv --slang=en,jpn"

**Comment by spector-9** [comment]
You have to explain how is it unstable. If you encountered a bug/s open a new issue with details.

**Comment by westofer** [comment]
@spector-9 

> You have to explain how is it unstable. 

not merged to master  :p  


for custom files it will be (untested) 

```
YTFZF_PLAYER="mpv --sub-file=/sub/file" ytfzf -t search term
```

> Plus I think slang option is for dvd titles

It works with youtube captions, just checked 👍 , try thses two

```
YTFZF_PLAYER="mpv --slang=ar" ytfzf -a still underground
YTFZF_PLAYER="mpv --slang=en" ytfzf -a still underground

```

**Comment by spector-9** [comment]
@westofer Don't worry I don't mind criticism of my commits they can certainly be bad, I am not a pro by any means. The current version is doing a pretty similar thing for auto. I see that you are saying you want default for user uploaded subs too. Am I right?

**Comment by westofer** [comment]
>  I see that you are saying you want default for user uploaded subs too

yeah 👍 ( I think only user uploaded subs)

> Don't worry I don't mind criticism of my commits they can certainly be bad

I didn't check your code btw :p , I assumed unstability because it is on development branch

**Comment by pystardust** [comment]
TODO: Sorting subscriptions via date

**Comment by pystardust** [comment]
@aimad10 
Sorting has been implemented, you could test it out by updating to the devbranch (either by cloning repo, or 
`ytfzf --update-unstable`)
```
ytfzf -S --sort
```
will sort the subscriptions as per upload date.

**Comment by aimad10** [comment]
> @aimad10
> Sorting has been implemented, you could test it out by updating to the devbranch (either by cloning repo, or
> `ytfzf --update-unstable`)
> 
> ```
> ytfzf -S --sort
> ```
> 
> will sort the subscriptions as per upload date.

poggers
