### ISSUE TITLE
AUR package ytfzf-git moved to ytfzf

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#197]
Arch user who had ytfzf-git installed will get package not found. Remove the -git version and install the yftzf version.

**Comment by westofer** [comment]
The package ytfzf-git [1] was adopted by gmy [2].

[1] https://aur.archlinux.org/pkgbase/ytfzf-git/
[2] https://aur.archlinux.org/account/gmy/

**Comment by Euro20179** [comment]
`ytfzf-git` is now maintained by me, and should always be the latest commit on master branch.
