### ISSUE TITLE
[Feature Request] Add Space After Emojis

### ISSUE THREAD

**Issue by ZachIndigo** [pystardust/ytfzf#199]
A brief suggestion, I might give a go at solving it if no one else wants to.

When printing a title with emoji characters (for example, Luke Smith's video on fish not being a real shell), the | separator does not line up with the other videos.

![ss-unicode-error-ytfzf](https://user-images.githubusercontent.com/43489508/113965686-5dcb2500-981d-11eb-87b3-b6df62a11d73.jpg)

The above picture is using ytfzf 1.1.2, my st build using libxft-bgra, but the problem persists with urxvt as well.

**Comment by pystardust** [comment]
Yes, this is a bug. This has to do with how emojis are being displayed, Since they are not monospace we are having an issue. 
If all emojis take up the same width, we could try to adjust the spaces based on how many emojis are present

**Comment by pystardust** [comment]
I have made use of the column command to fix this. Its in the dev branch currently.

**Comment by pystardust** [comment]
@BenEvolent333  Update ytfzf and check, they should have better formatting now.
