### ISSUE TITLE
Change pup with something more generic,so It can be used somewhere else

### ISSUE THREAD

**Issue by unixbhaskar** [pystardust/ytfzf#2]
Don't you think it is "too arch specific"?? And the whole world is not running Arch alone.So , please.

Oh Btw, appreciate your effort. 

Specifically change the functionality of "pup" to equivalent generic thing.

Just a thought.

**Comment by pystardust** [comment]
I removed pup, I substitued it with sed. Yes pup is too specific.

**Comment by pystardust** [comment]
I have added installation instructions for debian based distros
