### ISSUE TITLE
Discussion for thumbnails

### ISSUE THREAD

**Issue by pystardust** [pystardust/ytfzf#20]
Hi everyone, I need some suggestions and help to implement thumbnails.

Here is what I am able to do so far
* Download all the thumbnails
* Show them in an external viewer (sxiv) while fzf highlights a certain video.

Drawbacks : It doesn't look clean, as  it is using 2 separate windows. 

Feel free to share you ideas on how you would like thumnails implemented.

I can always fallback to a filemanager (like ranger, lf) which will make life much easier.

It would be nice if the dependencies are available in standard debian and arch repos.

**Comment by patdavid** [comment]
Maybe [Sixel](https://saitoha.github.io/libsixel/)?

**Comment by pystardust** [comment]
I looked at Sixel, seems interesting but there are a few caveats
* Doesn't support all terminals ( has specific requirements)
* Not available in standard repositories

**Comment by Eizen** [comment]
You can use Ueberzug. There is an example of how it can be used with fzf preview flag [https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh](fzfimg). I haven't looked too much into it but here is another script that makes use of it [https://github.com/OliverLew/fontpreview-ueberzug/blob/master/fontpreview-ueberzug](fontpreview). Hope that helps, would love to see that feature implemented.

**Comment by pystardust** [comment]
@Eizen <3 thanks for the info, I have added image previews
