### ISSUE TITLE
ncurses: check if installed

### ISSUE THREAD

**Issue by Vouivre** [pystardust/ytfzf#200]
Hello, I have packaged `ytfzf` for kiss linux. Perhaps unlike other distros, the user can choose the menu system and we can't assume that `ncurses` is installed because it's a minimal distribution. I have tested `ytfzf` without `ncurses`. If  only `dmenu` is installed it works fine. But I got the following errors:

````
/usr/bin/ytfzf: line 114: tput: not found
/usr/bin/ytfzf: line 115: tput: not found
````

That's [here](https://github.com/pystardust/ytfzf/blob/master/ytfzf#L119) (the code could change when you'll read this issue). 

Would it be possible to check if `ncurses` is installed before using `tput` ? 

I can propose a PR with a workaround if you want to.

**Comment by pystardust** [comment]
i have added a check if the user is using an external menu.
As long as you use dmenu, you wouldn't get an error now.
`tput`  is used to determine terminal size, to format text for fzf

**Comment by Vouivre** [comment]
Thank you! If it's ok for you, I'll test it tomorrow.
