### ISSUE TITLE
Audio only not working

### ISSUE THREAD

**Issue by qoheniac** [pystardust/ytfzf#203]
When I use the `-m` flag I get an error message saying the requested file format isn't available and then the video is played instead of just audio. If I use the `-f` flag and choose Audio no error shows up but it still plays the video.
```
$ youtube-dl --version
2021.04.01
$ ytfzf -v 
ytfzf: 1.1.2
$ ytfzf -am low-fi
Scraping Youtube...
Opening Player: mpv
[ytdl_hook] ERROR: requested format not available 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
 (+) Video --vid=1 (h264 1920x1080 30.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:02 / 00:00:14 (15%) A-V:  0.000 Cache: 12s/1MB

Exiting... (Quit)
```

**Comment by pystardust** [comment]
This seems to be a livestream.
youtube-dl is trying to get the audio. But since its a livestream, youtube-dl is not able to stream `bestaudio` format.  ytfzf falls back to normal format if youtube-dl fails to play video in the specified format. 
I just check the available formats. There doesn't seem to be any audio only version of a livestream using youtube-dl.

**Comment by qoheniac** [comment]
Then how about using `mpv`'s `--no-video` flag for streams? Like this:
```
mpv --no-video 'https://www.youtube.com/watch?v=5qap5aO4i9A'
```

**Comment by pystardust** [comment]
yes we could do that,
As a temporary fix. Parse the env variables
```sh
YTFZF_PREF=  YTFZF_PLAYER="mpv --no-video"  ytfzf -a low-fi
```
Or add it to the conf.sh

**Comment by qoheniac** [comment]
Thanks. Apart from that, I was wondering why it shows an error message for the `-m` flag but not for the `-f` flag after choosing `Audio` and I think it's because in [this line](https://github.com/pystardust/ytfzf/blob/be24919df838aaf4badffab77f77a716be9fcdb0/ytfzf#L1080) we should have `"bestaudio/best"` instead of just `"bestaudio"`.

**Comment by pystardust** [comment]
The PR works great. We can  close this issue if its resolved.

**Comment by qoheniac** [comment]
Sure, thank you for swift feedback! :)
