### ISSUE TITLE
-m option 

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#213]
the -m (audio only) in combination with -d (download) is downloading a video file *mp4 converts it to m4a and deletes the m4a audio file ...

**Comment by pystardust** [comment]
Thanks for the notice, I have reworked the audio, downloading part. Its currently in the dev branch. To update
```
ytfzf --update-unstable
```
> Or clone the repo, switch to the development branch and copy the script.

It seems to be working fine now, I will merge it to master after a lil more test. Help in testing would be appreciated :) 

commit: 753c457af751810be96ae5b8a22a0d3b5ba69c1b

**Comment by se7en-x230** [comment]
nope tried both update versions but cant get it to work. 
Still deletes the m4a file

**Comment by se7en-x230** [comment]
https://pastebin.com/UGCuVzea

**Comment by pystardust** [comment]
```sh
ytfzf --update-unstable
ytfzf -md sonata
# select an song
# this should download a .webm (audio-only)
```

**Comment by pystardust** [comment]
```sh
~_o $ ytfzf -mdt                                                                                 14:55
Search Youtube: bloom audiobook
Scraping Youtube...
Downloading Thumbnails...
[youtube] uTLWayYYXbQ: Downloading webpage
[youtube] uTLWayYYXbQ: Downloading MPD manifest
[download] Destination: BLOOM, Chapter 1, read aloud by Kenneth Oppel-uTLWayYYXbQ.m4a
[download] 100% of 11.42MiB in 00:03
[ffmpeg] Correcting container in "BLOOM, Chapter 1, read aloud by Kenneth Oppel-uTLWayYYXbQ.m4a"
```

> https://pastebin.com/UGCuVzea

It has downloaded audio only ( make sure to have `ytfzf --update-unstable`)

**Comment by se7en-x230** [comment]
Great works now. Thanks
