### ISSUE TITLE
Download Dir in config

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#215]
Would it be possible to add a custom download dir to the config file?
Same would be nice for video/audio format. To download per default mp4/mp3 IF available.

**Comment by Euro20179** [comment]
i think you can use cd (although this is kinda clunky) in config
`cd directory` and it should download there because the entire script will run there

there's probably a better way to do this, but this is what i've done

**Comment by se7en-x230** [comment]
Oh yes it does :) that was too "clunky" for my brain :)

**Comment by pystardust** [comment]
We could add a flag or something in the config, to change directory to the download dir when `-d` is used

**Comment by se7en-x230** [comment]
For me the cd ~/Downloads/yt/ in the config is just fine.
I rather have it in the config as I don't need to change it anyway every single download 
I just don't like it to end up either all over the place or mess up my ~/

**Comment by darnellkeithj** [comment]
It uses youtube-dl to download so you can make youtube-dl.conf with 
--output "~/desired/path/%(title)s.%(ext)s"

And it will just place all of your downloads there. Would be nice if there was a way to separate audio/video.
