### ISSUE TITLE
Documentation should mention shuf as a required dependency

### ISSUE THREAD

**Issue by 0mp** [pystardust/ytfzf#216]
As I am porting ytfzf to FreeBSD, I've spotted that it requires shuf to be present on the system. The shuf utility is not one of the portable utilizes you can expect your UNIX-like system to ship with by default.

It would be cool if the documentation mentioned that ytfzf requires shuf (I am not sure if there are any other utilities like that being used).

Cheers!

**Comment by 0mp** [comment]
It looks like the only shuf option used is `-n`, which seems to be portable across other implementations of shuf, e.g., https://github.com/ibara/shuf

**Comment by pystardust** [comment]
Yes, we could add it as an optional dependency. 
Hey since you use FreeBSD, if possible could you give a command to install all the packages required, just like the ones, in the install page for debian/arch based
https://github.com/pystardust/ytfzf/blob/master/docs/INSTALL.md/#dependencies

**Comment by 0mp** [comment]
> Yes, we could add it as an optional dependency.
> Hey since you use FreeBSD, if possible could you give a command to install all the packages required, just like the ones in the install page for debian/arch based
> https://github.com/pystardust/ytfzf/blob/master/docs/INSTALL.md/#dependencies

Sure! Done in #222
