### ISSUE TITLE
Add numbered queued videos

### ISSUE THREAD

**Issue by TomBT** [pystardust/ytfzf#229]
Add numbers next to queued videos by order in which they were queued. Say the user queues up videos, switches to another desktop, switches back to the queued videos and forgets the order of the queue. Numbers next to the videos would make that order apparent. I made a crude [photoshop](https://raw.githubusercontent.com/TomBT/imge/main/2021-04-23-195026_1366x768_scrot.png) of what my suggestion might look like.

**Comment by pystardust** [comment]
The program first makes an ordered list of url and parses it into the player. We could display this ordered list in another file maybe? I am not quite sure on how we could do it the way it is in the photoshop but it is possible to give that ordered list to any other program(notification)/store it in a file for the viewer to view.

**Comment by TomBT** [comment]
I was thinking instead of putting a little marker ( > ) next to the queued videos the number of the queue order would show up. So when the first video is queued a number 1 shows up next to it, then when the second video is queued a number 2 shows up, and the third a 3, and the fourth a 4, etc. instead of the marker ( > ).

**Comment by TomBT** [comment]
Oh and rather than saving the order in a list or seperate file I was thinking it would just be temporary and only be displayed when the search results are displayed.

**Comment by pystardust** [comment]
The tui is managed by [`fzf`](https://github.com/junegunn/fzf). I tried looking for such a feature in fzf but unfortunately `fzf` doesnt seem to have such feature to show the order of multiselect as you mentioned.
You could try opening an issue requesting for multiselect order numbering for `fzf`.
