### ISSUE TITLE
YT API support (option?)

### ISSUE THREAD

**Issue by BeyondMagic** [pystardust/ytfzf#23]
I love the script, but at least for me, YT API is way faster than using only youtube-dl. It would be lovely to have an option like that or even just enabling it in the script itself.

**Comment by pystardust** [comment]
I don't use youtube-dl to search for youtube videos, I intead scrape the website for name, views. etc. ( which is as fast faster than opening the website in the browser)

When you use yt api, how do you watch the videos?
yt-dl is only used for playing the video

**Comment by BeyondMagic** [comment]
Oh, I meant, YT API to get the data (name, video ID, channel, date) and running mpv normally. Probably something like this to get the data

```bash
APIKEY="........."
nresults=15 #number of results
search=$(echo "" | dmenu -p 'Search')
query="part=snippet&maxResults=$nresults&q=$search&type=video&key=$APIKEY"

curl -s -i -G -d "$query" "https://www.googleapis.com/youtube/v3/search" > yt.search
```

**Comment by westofer** [comment]
@BeyondMagic currently you can get Name, Video Id, Channel and Date without an API
![image](https://user-images.githubusercontent.com/50760091/109046126-76580380-76e5-11eb-89e4-77e3f94d85e8.png)

and with previews looks like:
![image](https://user-images.githubusercontent.com/50760091/109046200-866fe300-76e5-11eb-9b08-e6989fefffa7.png)

**Comment by BeyondMagic** [comment]
I mean, I'm pointing out performance here :|
Using YT API I can get the results in 0.02 seconds, 0.01 if I'm lucky.

The data is something like this:
```json
 {
      "kind": "youtube#searchResult",
      "etag": ".......................",
      "id": {
        "kind": "youtube#video",
        "videoId": "...........ID......."
      },
      "snippet": {
        "publishedAt": "2021-02-23T13:00:08Z",
        "channelId": "...CHANNELID......",
        "title": "....TITLE.....",
        "description": ".....DESCRIPTION....",
        "thumbnails": {
          "default": {
            "url": "https://i.ytimg.com/vi/...VIDEOIMAGEID.../default.jpg",
            "width": 120,
            "height": 90
          },
          "medium": {
            "url": "https://i.ytimg.com/vi/...VIDEOIMAGEID.../mqdefault.jpg",
            "width": 320,
            "height": 180
          },
          "high": {
            "url": "https://i.ytimg.com/vi/...VIDEOIMAGEID.../hqdefault.jpg",
            "width": 480,
            "height": 360
          }
        },
        "channelTitle": ".....CHANNELNAME....",
        "liveBroadcastContent": "none",
        "publishTime": "2021-02-23T13:00:08Z"
      }
}
```

**Comment by BeyondMagic** [comment]
it's completely fine

**Comment by pystardust** [comment]
@BeyondMagic  the json you showed seems much different to the one I am getting in this script. we would have to completely rewrite the script for it.
Currently there is no plans of adding api support case one of the main reason of this script is to avoid google. 
You can look at one of friends repos, he used youtube with api
https://github.com/Bugswriter/myyt

**Comment by BeyondMagic** [comment]
I don't think you need to rewrite your whole script if it was added as an option, I think I'll just add it myself when I have time. Thanks, anyway, nice script.

**Comment by pystardust** [comment]
@BeyondMagic  depending on how the api gives you data try modifying the `scrape_yt` function
This line has to be modified to suit the api formatting
```sh
jq '.title.runs[0].text,.longBylineText.runs[0].text,.shortViewCountText.simpleText,.lengthText.simpleText,.publishedTimeText.simpleText,.videoId' 
```
I would be happy to help out if you face any problems
