### ISSUE TITLE
--upload-time should support and filter subscribed channels

### ISSUE THREAD

**Issue by meissnol** [pystardust/ytfzf#231]
I called 
 `ytfzf --subs=1 -t --today --upload-date --fancy-subs=0` 
to see all videos from subscriptions file that were uploaded today. 
This doesn't work, so ytfzf shows up the very last uploaded video from each channel listed in the subscriptions file in an order I haven't figured out, but it's definitely not --upload-date: (2 days ago, 6 months ago, 6 days ago, 1 year ago, 22 hours ago)
There should be a way to list only videos from subscribed channels given by --upload-time
(Nearly like https://www.youtube.com/feed/subscriptions)

**Comment by pystardust** [comment]
Those filters are only for search queries and won't work for subscriptions as of now.
You could try out the sort subscription feature. Its currently in development branch
To update to dev branch
```sh
ytfzf --update-unstable
```
To view subscriptions via sort
```sh
ytfzf -S --sort
```
This would show all of today's videos on the top
Sort option would even work with normal searches

**Comment by meissnol** [comment]
That's exactly what I wanted.

Thanks.
