### ISSUE TITLE
thumbnails option not working

### ISSUE THREAD

**Issue by lordofwizard** [pystardust/ytfzf#235]
```ytfzf -t sadhguru
Illegal option -t
Option not found!
Usage: ytfzf <search query>
     'ytfzf -h' for more information
     ```
     terminal : - alacritty , gnome-term
     xorg
     ytfzf github clone install
every dependency is installed perfectly
os pop-os 20.10

I changed to developement branch but still i am not getting new thumbnail preview.. i guess it's ueberzug's issue.. can you help me with that?
i am getting the new UI tho

**Comment by pystardust** [comment]
Are any other options working?
Which shell are you using?

Did you manually install the script before? Maybe that script is being used instead of the new one.

Try
```
git clone "https://github.com/pystardust/ytfzf"
cd ytfzf
./ytfzf -t test
```
