### ISSUE TITLE
Struggling to switch player

### ISSUE THREAD

**Issue by user98765446** [pystardust/ytfzf#238]
Thank you for ytfzf. It is GREAT.

Sometimes, mpv video stalls while the audio continues. I have experienced this before when streaming from youtube-dl. For me, I have had better luck with VLC.

However I am struggling to change my ytfzf player to vlc. The following values (in my conf.sh) cause vlc to run but no video plays.

video_player="vlc"
video_player_format="vlc --ytdl-format="
audio_player="vlc --no-video"

Perhaps I have done something stupid. If that is the case, I apologise in advance.

**Comment by Euro20179** [comment]
i tried this with only vlc-bin installed and the same thing happened, make sure all of vlc is installed.

try running `ytfzf --update` or cloning the newest version

make sure you're not using -m (audio_only)

i don't think --ytdl-format= is a valid argument for vlc, i could be wrong.
