### ISSUE TITLE
Information about code

### ISSUE THREAD

**Issue by cybarspace** [pystardust/ytfzf#24]
### Hello there. I'd like to understand your code a bit better in order to drop the features I don't need from my fork of your script. If you're willing to help with that...

1. In the below image, what exactly is the variable `main` doing in lines `43` and `68-69`? Is that really necessary?
(also note that using a loop for dep check makes the code easier to modify - just add/remove names to the dep variable)

![image](https://user-images.githubusercontent.com/50134239/108959613-d5465a00-769e-11eb-9021-3afa3a3b3452.png)

2. Another thing is, I'd like to remove this if-else block and the `*_len` variables if it isn't required if I use your `-a` flag to autoplay stuff, since I'm not displaying the names. Are any of these required nonetheless for searching the video or playing it, or can I just remove them? (I removed the fzf parts already btw)

![image](https://user-images.githubusercontent.com/50134239/108958827-babfb100-769d-11eb-9100-fd7c5db428d9.png)

**Comment by pystardust** [comment]
yes, if you want just option `-a` then I  you don't need 90% of the code.
the main is the most important part of the code. Here we get the url and all the details of the videos. 
I put a flag for main to skip main when history is called for. I will clean the code sometime and include your suggestion of checkdep loop.
I have added many commits after this one. So check the newer commit. These stuff are in functions and itll be easier for you to understand.
Thanks

**Comment by cybarspace** [comment]
Marvelous. I'll check the latest commit for documentation. Thanks.

**Comment by cybarspace** [comment]
@pystardust Sorry to bother again but is line 81 needed for autoplay without menu? I'm also not saving history or currently playing information.

![image](https://user-images.githubusercontent.com/50134239/109019575-51fb2780-76e3-11eb-95be-88d3c23e5682.png)

**Comment by pystardust** [comment]
No you can remove it. 81 is used to get back the truncated display fields like name.

**Comment by cybarspace** [comment]
Thanks. Sorry for the trouble.

**Comment by pystardust** [comment]
np, let me know if you have other queries

**Comment by cybarspace** [comment]
Kind of unrelated to your project, but very helpful for me.

I found [this article](https://www.codeproject.com/articles/873060/python-search-youtube-for-video) that fits the scope of my project perfectly. It's extremely simple and concise, and uses just the standard Python library tools (other than mpv and youtube-dl ofc).

I'll try to convert my fork to Python completely now. Thanks for the help and inspiration 😊
