### ISSUE TITLE
[FIX] [ytdl_hook] /usr/bin/env: ‘python’: No such file or directory

### ISSUE THREAD

**Issue by thenerdsuperuser** [pystardust/ytfzf#240]
For people getting the following error

```
[ytdl_hook] /usr/bin/env: ‘python’: No such file or directory
[ytdl_hook] mpv - file format is wrong
```

The issue is because of the file referencing to python, instead of python3.

Solution:

1. For ubuntu 20.04 you can use following package to python command. And it is python 3.

    ```sudo apt-get install python-is-python3```

2. For other OS, 

    ```sudo ln -s /usr/bin/python3 /usr/bin/python```

**Comment by Euro20179** [comment]
Closing to keep issue tracker clean.
