### ISSUE TITLE
Find and play playlists?

### ISSUE THREAD

**Issue by tamis-laan** [pystardust/ytfzf#242]
Is it possible to search for playlists instead of individual video's?

**Comment by Bugswriter** [comment]
@pystardust BUMP!!!!

**Comment by pystardust** [comment]
f61012b15054d1c192ab19a76f20382709d59fe1

**Comment by pystardust** [comment]
update to dev branch(`ytfzf --update-unstable`, version : `ytfzf: 1.2.0_dev`), its functional without thumbnails.
Playlists show up in normal searches as
```
[Playlist] title
```

**Comment by tamis-laan** [comment]
> update to dev branch(`ytfzf --update-unstable`, version : `ytfzf: 1.2.0_dev`), its functional without thumbnails.
> Playlists show up in normal searches as
> 
> ```
> [Playlist] title
> ```

Nice! No need for thumbnails, most of the time they show clickbait anyway. Better to keep focus on the information your looking for.
