### ISSUE TITLE
Search result encoding

### ISSUE THREAD

**Issue by HotscriptGG** [pystardust/ytfzf#25]
Hi,

I'm on iTerm2 on MAC (which has a pretty good unicode support) and polish diactrics look kind of wonky in search results.

![Zrzut ekranu 2021-02-24 o 10 57 37](https://user-images.githubusercontent.com/1574210/108985830-c7d6a300-7691-11eb-8840-e3e4ee321ee9.png)
Eg.
first line should say: Pal Hajs TV - 43 -  Dożynki W Nidzicy
last line should be: Pal Hajs TV - 124 -  Święto Kwiatów Owoców i Warzyw 2020
Cheers,

**Comment by pystardust** [comment]
Do you have polish fonts installed? I would need to look into this. Try installing a monospace polish font.
I get indian languages on my system with their fonts.

**Comment by HotscriptGG** [comment]
Yes. FiraCode Nerd Font Mono. I can typa all polish characters just fine in prompt or in nvim. Maybe it's my config. Hard to tell. I'll take a look later on second machine with Ubuntu, Alacrity Terminal and different font settings.

Don't get me wrong this script is awesome :)

**Comment by pystardust** [comment]
Any update from your ubuntu box?

**Comment by HotscriptGG** [comment]
I've cloned repo today on Ubuntu and it works nice. I'll try to debug on Mac then. If I find something I will let you know.

**Comment by pystardust** [comment]
Oh thats great. If you find a solution for mac do let me know. We can add it to the readme.
