### ISSUE TITLE
Dmenu and thunbails

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#26]
Amazing script.

the -D -t switch doesn't work.
I guess thats too much for dmenu.

Also uberzug has this bug that the thumbnail doesnt get deleted or updated once it was cached.
Have a look at lfimg and lf-ueberzug here in git they found a solution for the file manager lf + ueberzug.

hmmm was a one time thing I guess ... not doing it anymore ... you are very fast :)

**Comment by pystardust** [comment]
I don't know where to add thumbnails for dmenu.
If you have ideas let me know.
The script manually deletes thumbnails once done. If there is an issue I will look into it thanks for warning.

**Comment by pystardust** [comment]
@se7en-x230 
If you have any suggestions on how we can use thumbnail along side dmenu do let me know. 
Mostly we would have to use an external image viewer like sxiv. And still dmenu might cover up the thumnails depending on where the window spawns

**Comment by se7en-x230** [comment]
I sadly have not.
Nice about the dmenu solution is that I can start it from anywhere without districting my workflow.

I think an external viewer is too messy.

My workaround is to add a key binding to spawn a new terminal with a search request to display in my terminal which then feeds ytfzf -t.

**Comment by pystardust** [comment]
You can bind a dmenu prompt to take in search queary and open the results with your terminal using xargs.

**Comment by se7en-x230** [comment]
I did bind a key to DWM opening a "dropdown" terminal.

![ytfzf](https://user-images.githubusercontent.com/69777713/109266534-c7c5d700-783a-11eb-9cf2-c3fbd51277ba.gif)


Only problem I have now assuming export YTFZT_MENU_ is not helping.

**Comment by pystardust** [comment]
@se7en-x230 
Thanks for informing, I have fixed it now.
Also now you can do 
```
st -e ytfzf -t
```
And it will prompt you in the terminal for input just like you have shown.

**Comment by pystardust** [comment]
@se7en-x230 
If I am closing this issue, let me know if you have more queries

**Comment by CMOISDEAD** [comment]
is there any way to add a keybind in dwm that executes this command `ytfzf -D`, for a strange reason that I cannot understand this does not work, it shows dmenu and when I select one of the searches dwm does not execute mpv.
![2023-03-20-17:21:24-screenshot](https://user-images.githubusercontent.com/51010598/226478859-d171634a-818c-41be-ab08-cdff45f44949.png)
