### ISSUE TITLE
[enhancement] Show how many likes a video has

### ISSUE THREAD

**Issue by TomBT** [pystardust/ytfzf#260]
Show the likes and dislikes on a video beneath the View or Date. I made an [image](https://raw.githubusercontent.com/TomBT/imge/main/image.psd.png) for how it might look like.

Also, over at Invidious there is a like rating shown as a percentage with the likes but I'm not sure how it's calculated.

**Comment by Euro20179** [comment]
this will be a bit challenging to implement for 2 reasons, 
1. the code currently doesn't handle video information very well
2. likes and dislikes can only be found at the video itself, (this is a lesser problem)

but it is possible so i will be trying to implement this
