### ISSUE TITLE
/usr/bin/ytfzf: 1: eval: column: not found

### ISSUE THREAD

**Issue by 123jimenez99** [pystardust/ytfzf#261]
Debian testing, all the dependencies installed, youtube-dl git. When I search something it does not bring any results, only a blank prompt.

Thank u.

**Comment by Euro20179** [comment]
do you have anything in your config file?

**Comment by 123jimenez99** [comment]
> do you have anything in your config file?
No I don't, but I never neded it before.

> and are you on the latest ytfzf version
Yes, I'm on the latest ytfzf version.

**Comment by 123jimenez99** [comment]
You know what?, I'm going to install Arch on this machine, my other machines run ytfzf flawlessly with it. Thanks for the info BTW.
