### ISSUE TITLE
About formats

### ISSUE THREAD

**Issue by Battleman** [pystardust/ytfzf#263]
Hi! Thanks for this tool, I really appreciate that. I've been using for a while, and I've noticed a few things, in particular about format (I'll open dedicated issues for other things).

Not sure if **bug** or **feature request**:  the `-f` option doesn't work for a direct URL. For example `ytfzf -f https://www.youtube.com/watch?v=dQw4w9WgXcQ` (with an empty config file): I'd expect it to open the interface to select the quality, but instead it straight up ignores the option and plays directly. 

**[feature request]**: allow to specify an ordered list of preferred format: Then about preferred formats: It's nice to be able to provide them, but providing only 1 is limiting. For example, I have simple full-HD, 1920x1080 screens, so I'd rather avoid higher resolutions (which create artifacts). I found the formats 299, 137 and 303 (and probably also others) to match that resolution; they differ in FPS and file format for instance . But obviously, one rarely occurs everywhere. Right now, I'm unable to specify a "preferred order" rather that "preferred format". Interestingly, specifying two (or more) numbers comma-separated doesn't throw an error but (if one of them is valid) will play the video without sound. I tried adding audio formats as well, or `bestaudio`, which didn't work (at least in the configurations I tried).

**Comment by Euro20179** [comment]
i have created a pr for the -f with urls, as for priority you can update to the development branch and add 
```sh
handle_urls () {
    selected_urls="$1"
   #gets the formats for the video from youtube-dl
    formats=$(youtube-dl -F "$(printf "$selected_urls")")
   #for each format,
    for line in $video_pref; do
       #check if video has format
        l="$(printf "%s" "$formats" | grep "$line")"
        #if so set video_pref to it and stop
        [ -n "$l" ] && video_pref="$line" && break
    done
}
```
to your config file in `~/.config/ytfzf/conf.sh`

to update to the development branch run `ytfzf --update-unstable`

**Comment by Battleman** [comment]
I confirm the fix works flawlessly for 1 URL. And as suspected, putting 2 URLs results in an error
 ```
/usr/bin/ytfzf: 883: printf: %3D: invalid directive
/usr/bin/ytfzf: 884: printf: %3D: invalid directive
```
and the formats menu opening, without any choice.

**Comment by Euro20179** [comment]
Apparently youtube-dl has this feature. To have priority, separate each preference with a `/`
