### ISSUE TITLE
Verified music channels show "null" as upload date

### ISSUE THREAD

**Issue by TomBT** [pystardust/ytfzf#266]
I included a [screenshot](https://raw.githubusercontent.com/TomBT/imge/main/minions-reference.png) to hopefully make what I talk about easier to understand. 

Uploads on verified music channels (the ones with the music notes next to them) show "null" instead of the upload date because YouTube automatically hides them when they are in the search results. The actual upload date would have to be scraped from the video description/details. Also in the description there's a line that says "Released on: " which shows the actual release date of the song. Maybe that could be used instead of the upload date since it's more accurate.

One last thing, I highly suggest you listen to the [song I used](https://www.youtube.com/watch?v=kSC_IoD-Bxw) for an example if you haven't already. It's really good. :)

**Comment by Euro20179** [comment]
The null thing also happens with livestreams, in order to scrape the description and anything on the video you either have to scrape the video itself which would be slow, or you have to scrape the same information twice which is still slow. this comment also applies to #265.

**Comment by TomBT** [comment]
Would this also apply to #260 since getting the likes would also have to load both the search results and video info?

**Comment by Euro20179** [comment]
yes

**Comment by TomBT** [comment]
Is it still possible to scrape the brief description from the YouTube search results? [It looks like](url) its from the search results page and not the video itself, or would scraping the brief descriptions for that many videos also slowdown the program too?

**Comment by pystardust** [comment]
It is possible to scrape the description. I have made a refactor on how the data is being managed to be displayed. Before we relied completely on the tsv that was passed by fzf. Now I have implemented it in a way that the whole json object can be accessed while displaying the information.

Check out the description branch and the pr.

**Comment by TomBT** [comment]
So it's still possible to show the likes as well since it scrapes the json?

**Comment by TomBT** [comment]
Alright I've downloaded that and it works for the most part but some descriptions are cut shorter than they should be for seemingly no reason. I've been trying to see what is in common but [I can't see much.](https://raw.githubusercontent.com/TomBT/imge/main/short_descrpt.jpg)

Also the date for the all of the official music channels say ["Provided to YouTube by [whichever music company]"](https://raw.githubusercontent.com/TomBT/imge/main/fuck_UMG.png) and don't have a description (but I'm not sure how important that is for music.

**Comment by Euro20179** [comment]
what's in common is that, the description gets cut off when it reaches a bolded word, words are bolded in the description when they match the search.

**Comment by TomBT** [comment]
Sorry for responding so late but is it still possible to get the likes as well from the JSON? It makes it a lot easier to see which videos are worthwhile and which ones aren't from the terminal.

**Comment by Euro20179** [comment]
It would be nice to get likes from the json, but It doesnt appear that they are in the json

**Comment by TomBT** [comment]
Ah, I see. Anyways I just wanna thank you guys for the work you put into this project and hearing out the recommendations suggested by its users.
