### ISSUE TITLE
unknown action: first

### ISSUE THREAD

**Issue by re4388** [pystardust/ytfzf#27]
May I know is it supposed to work for win10 WSL? :) 
After many dependency installations, when I type `ytfzf` then I got this output.
Only `ytfzf -h` works for me.

**Comment by pystardust** [comment]
I have not tested It on win10 WSL.
What output did you get?

**Comment by KVAnton-WEB** [comment]
I also get this error on ubuntu 20.04 (KDE Neon 5.21)

**Comment by cboxdoerfer** [comment]
The `first` action is part of fzf and was only introduced with one of the latest fzf versions (0.25). In earlier versions the action was called `top`.

So to fix this you either need to update fzf to  version >= 0.25 or change `change:first` to `change:top`in the ytfzf script.

**Comment by westofer** [comment]
that was an extremely smart pull request from me lol (assuming it fixes the issue)

thanks @cboxdoerfer
