### ISSUE TITLE
Search again hotkey

### ISSUE THREAD

**Issue by p1839251** [pystardust/ytfzf#274]
Hello,
It would be useful if there were a search again hotkey.
I use `ytfzf` with `-l `(loop) so I could stay inside the program.
I look something up, browse a little, watch a couple of videos then I sometimes want to modify the search terms.
Right now, I have to exit and type `ytfzf` again, which isn't very convenient.

**Comment by Euro20179** [comment]
#289 and update to the development branch with `ytfzf --update-unstable` (alt-s is the hotkey to search again)
