### ISSUE TITLE
[Suggestion] Swallow terminal when playing a video

### ISSUE THREAD

**Issue by Kabouik** [pystardust/ytfzf#275]
I just found out about `ytfzf` and I really like it, thanks to you and all contributors for this awesome script.

What would you think about an option to automatically hide the terminal during play back and restoring it when the video ends? This is something I submitted for [`termv`](https://github.com/Roshan-R/termv/pull/7#issuecomment-846188766) and I think it works pretty well with minimal dependencies. I have looked at the code for `ytfzf` and it's a bit complex for my limited coding skills, but since it's POSIX it should be relatively easy to implement in a similar way.

**Comment by tamis-laan** [comment]
You can add this feature by adjusting the config file.

https://github.com/pystardust/ytfzf/issues/174

**Comment by qoheniac** [comment]
xdo would be another Xorg-only dependency in addition to Überzug for the thumbnails.

**Comment by tamis-laan** [comment]
@Kabouik 

Might I suggest not swallowing the terminal but forking the mpv player. This way you can do multiple searches and have multiple videos open. https://github.com/pystardust/ytfzf/issues/174 

You can also try to modify that example and introduce swallowing.

**Comment by pystardust** [comment]
> forking the mpv player.

This has been implemented here #291 
You could press `alt-enter` to open the video as a forked process and continue the menu selection.
( Update to the development branch using `ytfzf --update-unstable` )

**Comment by tamis-laan** [comment]
@pystardust 
`alt-enter` is the most commonly used shortcut for opening a new terminal in window managers, might I suggest using `ctrl-enter`?

**Comment by pystardust** [comment]
unfortunately `ctrl-enter` isn't in the list of hotkeys supported by fzf.
The list of hot keys available from fzf (man fzf)
```
   AVAILABLE KEYS: (SYNONYMS)
       ctrl-[a-z]
       ctrl-space
       ctrl-\
       ctrl-]
       ctrl-^      (ctrl-6)
       ctrl-/      (ctrl-_)
       ctrl-alt-[a-z]
       alt-[*]     (Any case-sensitive single character is allowed)
       f[1-12]
       enter       (return ctrl-m)
       space
       bspace      (bs)
       alt-up
       alt-down
       alt-left
       alt-right
       alt-enter
       alt-space
       alt-bspace  (alt-bs)
       tab
       btab        (shift-tab)
       esc
       del
       up
       down
       left
       right
       home
       end
       insert
       pgup        (page-up)
       pgdn        (page-down)
       shift-up
       shift-down
       shift-left
       shift-right
       alt-shift-up
       alt-shift-down
       alt-shift-left
       alt-shift-right
       left-click
       right-click
       double-click
       or any single character
```
Yes `alt-enter` seems like a poor default choice. You could edit the shortcuts in the config https://github.com/pystardust/ytfzf/blob/f9b519f04bfcaed6e5b3392e713cd775aa56b146/docs/conf.sh#L226
Do suggest a better default. I will modify it.

**Comment by pystardust** [comment]
There is also an option `--detach` that does the same (without any shortcut). You could add `detach_player=1` in your config to make it permanent

**Comment by tamis-laan** [comment]
`shift-enter` ?

More shortcuts should be added, this is way to sparse.

**Comment by pystardust** [comment]
nope doesn't work
```
unsupported key: shift-enter
```
The key must be present in the above list according to fzf's manual

**Comment by Kabouik** [comment]
Great news, but I agree that alt-enter is not ideal (one of my devices has no Super key so I have to use Alt as my i3 modifier, and I think many people do that too). I'm still happy with the --detach option anyway, but would be great if fzf could support ctrl-enter or shift-enter in the future.

**Comment by Euro20179** [comment]
I thought ctrl-enter was valid

**Comment by plasmoduck** [comment]
#!/bin/sh
xdotool windowunmap "$WINDOWID"
$@
xdotool windowmap "$WINDOWID"

This will swallow the terminal when launching a process. You could use this code.
