### ISSUE TITLE
Only download thumbnails if they're going to be displayed

### ISSUE THREAD

**Issue by JojiiOfficial** [pystardust/ytfzf#28]
I usually want to show thumbnails, so i aliased `ytfzf="ytfzf -t"` in my .zshrc to not always having to add the `-t`. Now it always takes up 1-2s to download them, even when I run ytfzf with `-a`, which is useless. It would be nice if ytfzf would download the thumbnails only when a fzf menu is going to be opened.

**Comment by pystardust** [comment]
Done :smile:

**Comment by JojiiOfficial** [comment]
Fastest patch in the West
thanks!
