### ISSUE TITLE
How can I set the format?

### ISSUE THREAD

**Issue by stupid-question** [pystardust/ytfzf#280]
Every time I watch videos, I get 1280x720p in low bitrate. Instead I would like to set --ytdl-format=337+140 constantly. After exploring some docs, I understood that I must set YTFZF_PREF enviroment variable with my definitive parameters. So YTFZF_PREF=337+140 (tried this one too YTFZF_PREF='337+140') has been wrote to /etc/enviroment. Nothing changed. Might you explain how can I achieve this without rewriting the script by a "legal" way? Thanks for the answer.

**Comment by Euro20179** [comment]
try exporting it in your shell's rc file `export YTFZF_PREF="337+140"` or, in `~/.config/ytfzf/conf.sh` add `video_pref="337+140"`

**Comment by stupid-question** [comment]
I have redownloaded the last version of the app. It works. So, it wasn't your fault. Apparently I just broke something by myself. Thank you.
