### ISSUE TITLE
Format selection not working while using a link..

### ISSUE THREAD

**Issue by IDontKnow2Code** [pystardust/ytfzf#287]
It seems like function `get_video_format` is not being called while using `-f` and a `link`.
Issue:
`ytfzf -f https://www.youtube.com/example` 
not calling the function `get_video_format` resulting in direct playing of video.
BTW Thank you! for this great tool! 😊

**Comment by Euro20179** [comment]
try updating to the development branch, run `ytfzf --update-unstable`

**Comment by IDontKnow2Code** [comment]
I tried it, it didn't solve the problem.

**Comment by Euro20179** [comment]
try running `YTFZF_CONFIG_DIR="/dev/null" ytfzf -f [link]`, if this fixes it there is probably a problem with your config file, and make sure you're on the development version because links with format don't work on the main branch.
You can confirm the version you have by running `ytfzf -v` and it should be 1.2.0_dev

**Comment by IDontKnow2Code** [comment]
That solved the issue, but there is no conf.sh file in the config directory, I only added Subscriptions file. should I copy the docs/conf.sh from git to config dir?

**Comment by Euro20179** [comment]
docs/conf.sh is just default settings it is equivalent to an empty config file. I'm not sure if thats the cause but if you want you can create an empty config and see if that helps

**Comment by IDontKnow2Code** [comment]
Ok let me check now

**Comment by IDontKnow2Code** [comment]
Yeah! Creating a empty `conf.sh` file solves it, what could possibly be the reason for it?

**Comment by Euro20179** [comment]
I have no idea what the cause of that is, but I dont like the idea of forcing someone to have an empty file for this, I'll look into it when I can.

**Comment by IDontKnow2Code** [comment]
I m using zsh

**Comment by Euro20179** [comment]
what is the output of `file /bin/sh`

**Comment by IDontKnow2Code** [comment]
bash

**Comment by Euro20179** [comment]
What happens when you use version 2.1
