### ISSUE TITLE
Cooler looking gif

### ISSUE THREAD

**Issue by pystardust** [pystardust/ytfzf#30]
I want to add a cooler looking gif to the readme. 
I am not very good at ricing.
It would be really nice if someone with a really cool rice makes a gif :sunglasses: 
@westofer

**Comment by westofer** [comment]
https://user-images.githubusercontent.com/50760091/109028252-aba72600-76d2-11eb-8fa9-353471a63e02.mp4

for some reason, image preview didn't work in fish 

any edits on the video? (will convert after we agree if it is good)

**Comment by pystardust** [comment]
@westofer  It looks great. The only issue is with the capitol J and small j instruction. Those are mpv defaults I don't know if that would go well in our read me gif.
The second one looks lil tiny. Can you many another one like your first video with out the instructions.
You shell looks amazing!
