### ISSUE TITLE
Select Playlist items

### ISSUE THREAD

**Issue by piotryordanov** [pystardust/ytfzf#302]
ytfzf currently plays [Playlists]. 

But, it is possible that before the playlist is played, for me to choose which song from the playlist to play?

**Comment by Euro20179** [comment]
currently it is not possible to do this, although I wonder if YouTube-DL can download each video from a playlist individually

**Comment by timsofteng** [comment]
Playlists will be great feature.

**Comment by Euro20179** [comment]
In the rewrite branch, you can do something like
```sh
ytfzf --type=playlist <search>
```
and when you select it it will scrape the playlist so you can pick the videos.
