### ISSUE TITLE
add option to print video name only

### ISSUE THREAD

**Issue by windowswithoutborders** [pystardust/ytfzf#303]
Please consider adding an option to print out the video name selected. It would function similarly to the -L, --link-only option (no video is played, only a printout is given), and it's main use would be to be paired with -L, where you can print out multiple links and their associated name together. This would be very helpful for archiving/scripting purposes.

**Comment by Euro20179** [comment]
there is an option in the `playlists-queue` branch (although this branch is not up to date) called `-R` which prints the selected video. (currently this does not work with `-L` but it wouldn't be hard to make it work with `-L`). It would take an extra step to get the title specifically from this, because `-R` also includes the views, channel, etc. But it wouldn't be too hard.
The `playlists-queue` branch is a bit off from being merged, but even if it doesn't get merged, I would also like an option like `-R` to be available.

**Comment by windowswithoutborders** [comment]
@Euro20179 
`-R` sounds perfect and even preferred to print the full 
`<title> |<channel name> |<viewcount> |<duration> |<upload date> |<youtube id> ` 
format as, like you said, it would only take an extra step to grab the title, but should any of the other elements be useful those too are available to be used. 

As a matter of fact, it doesn't even need to work with -L as a bit of shell script will still accomplish everything/anything anyone would need with that information:

```
$ cat ytfzf_videoline
EmacsConf 2020 - 39 - NonGNU ELPA - Richard Stallman    |EmacsConf and Emacs hangouts   |4.9K views     |6:57   |6 months ago   |2bQ-0dkQytE

$ cat ytfzf_videoline | awk -F "|" '{print $1,"\nhttps://youtu.be/"$NF}'
EmacsConf 2020 - 39 - NonGNU ELPA - Richard Stallman
https://youtu.be/2bQ-0dkQytE
```

`-R` as is in the playlists-queue branch sounds perfectly adequate and would be immediately useful right now. I'd love to see that feature merged soon.

**Comment by Euro20179** [comment]
Cool, glad that solves the issue, and yes you are right -R would work perfect without -L.
I will keep this open until something like -R gets added but if you want you can close it.

**Comment by Euro20179** [comment]
it's been a while but, in the rewrite of this script there is this option
```sh
ytfzf -I VJ <search>
```
This will print a json object with a bunch of information about he selected video.

I plan on making the rewrite the main version of this script soon, but you can update now with `ytfzf --update-unstable=rewrite` (despite the command, the rewrite branch is (i hope) as stable as master branch)
