### ISSUE TITLE
[BUG] sort_video_data_fn removes first result

### ISSUE THREAD

**Issue by simonhughcom** [pystardust/ytfzf#306]
As already mentioned in #305, the `sort_video_data_fn`  has a bug where it currently removes the first line of video data.
This affects the functionality of a few ytfzf features such as not returning the first result when searching.

**Comment by Euro20179** [comment]
I can't seem to replicate this, the first video appeared when i searched `ytfzf hi` and `ytfzf --sort hi`, the total amount of videos did vary, but that seemed to be a product of inconsistent search results.

**Comment by simonhughcom** [comment]
Try putting `echo "$videos_data" | wc -l; exit` before and after the 
`[ "$sort_videos_data" -eq 1 ] && videos_data=$(printf "%s" "$videos_data" | sort_video_data_fn)` line in `scrape_yt` function,  you will notice that one line is consistently missing afterwards.

**Comment by Euro20179** [comment]
#309
