### ISSUE TITLE
[Suggestion] Prospect of using invidiou.site

### ISSUE THREAD

**Issue by thecashewtrader** [pystardust/ytfzf#312]
# What
invidiou.site is a bloat-less frontend for youtube, and the URL format is the same.
# Why
I think that by using https://www.invidiou.site instead of https://www.youtube.com, we could lessen the amount of junk downloaded by mpv/youtube-dl/the script which is used to get the thumbnails.

**Comment by Euro20179** [comment]
Currently we are rewriting the script, so this may not be merged into master for a while, but check out #400
