### ISSUE TITLE
`--audio-only` won't let you choose the url when used inside a script

### ISSUE THREAD

**Issue by anishmittal2020** [pystardust/ytfzf#313]
`ytfzf -t under pressure` lets me choose which url, I want to play, but `ytfzf --audio-only -t under pressure` won't let me choose the particular url to be played. I guess it plays the first match by default. I think, the default behavior should let us choose the particular audio url we want to listen.

**Comment by Euro20179** [comment]
Maybe because you're selecting the playlist? Playlists will play the entire playlist, there is no way to select an individual item in a playlist currently.

**Comment by anishmittal2020** [comment]
> Maybe because you're selecting the playlist? Playlists will play the entire playlist, there is no way to select an individual item in a playlist currently.

I don't understand your reply. I am not able to choose anything. I don't get fzf list of youtube titles that I could choose from!

**Comment by Euro20179** [comment]
Does it say any errors?
And do you have anything in your configuration file?

**Comment by anishmittal2020** [comment]
It got fixed when I reinstalled.
