### ISSUE TITLE
Using external mpv (devour) errors out

### ISSUE THREAD

**Issue by Albonycal** [pystardust/ytfzf#318]
adding `devour` using ENV variables errors out
`sh: line 2: 428][vcodec!=?vp9]+bestaudio/best: No such file or directory`

**Comment by Euro20179** [comment]
This looks like the error message I got when I used zsh as my shell. Although the program doesnt really work with zsh.

For the mean time instead of using devour use the --detach option

**Comment by westofer** [comment]
open an issue in devour's repo, the issue is this https://github.com/salman-abedin/devour/pull/24
