### ISSUE TITLE
"Argument list too long" for to many subscription

### ISSUE THREAD

**Issue by OlMon** [pystardust/ytfzf#319]
Greetings,

Thank you for this awesome software.

With the last update the -S parameter throws an error with more then 36 subs.
I have 120 subs and this worked fine with the last version. Now every time I have more than 36 subs in the list I get following messages.
I don't use any custom config.sh, so it should be the default one.

```
ytfzf -S
/usr/bin/ytfzf: line 1329: /usr/bin/cat: Argument list too long
/usr/bin/ytfzf: line 907: /usr/bin/sed: Argument list too long
/usr/bin/ytfzf: line 575: /usr/bin/fzf: Argument list too long
/usr/bin/ytfzf: line 575: /usr/bin/column: Argument list too long

ytfzf -tS
/usr/bin/ytfzf: line 1329: /usr/bin/cat: Argument list too long
/usr/bin/ytfzf: line 907: /usr/bin/sed: Argument list too long
/usr/bin/ytfzf: line 464: /usr/bin/mkfifo: Argument list too long

ytfzf -tS --sort
/usr/bin/ytfzf: line 1303: /usr/bin/cut: Argument list too long
/usr/bin/ytfzf: line 1294: /usr/bin/sort: Argument list too long
/usr/bin/ytfzf: line 1287: /usr/bin/date: Argument list too long
/usr/bin/ytfzf: line 907: /usr/bin/sed: Argument list too long
/usr/bin/ytfzf: line 464: /usr/bin/mkfifo: Argument list too long
```

System:
Arch Linux 5.12.14-arch1-1

If I can help with more information please let me know.

Cheers

**Comment by GSquad934** [comment]
I can confirm having the same issue with 57 subscription s, also using Arch Linux. Issue started with release v1.2.0. I reverted back to the previous one in the meantime.
I will keep digging what the issue might be and come back if I find anything

**Comment by Euro20179** [comment]
interestingly something in my config fixes this problem.
Im going to see if i can figure out what.

**Comment by Euro20179** [comment]
ok so, i think i've found what fixes it, in my config i have `sub_link_count=1` which seems to fix it. Now I need to figure out why.

**Comment by Euro20179** [comment]
> If I can come up with a clean solution, I will submit a PR.

if you do this, please work on the master branch, because I would like to merge a fix to master asap.

**Comment by Euro20179** [comment]
ok, for some reason the issue is line `1324` specifically.

**Comment by Euro20179** [comment]
#322

**Comment by GSquad934** [comment]
> #322
> 
> you can update with `ytfzf --update`.

You were faster than me lol. I can confirm the issue is fixed: it works fine for me now.
Good job 👍 and thank you.

**Comment by Euro20179** [comment]
cool
