### ISSUE TITLE
Bitchute and others

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#321]
Since yt is protecting us from "harmful content" would it be possible to include other from YouTube-dl supported sites?

**Comment by Euro20179** [comment]
currently the only non-youtube supported site is peertube, but it would be nice to support odysee.

**Comment by trueauracoral** [comment]
> currently the only non-youtube supported site is peertube, but it would be nice to support odysee.

I am working on a small script to search odysee. I am just not so good at programing. One of the scripts is for dmenu and the other uses fzf:
https://gitlab.com/TrueAuraCoral/otv-odysee-terminal-viewer

**Comment by Euro20179** [comment]
ahh, I was looking for an api to use for lbry, because scraping html with grep (we dont want to use pup do to installation difficulties on arch) is *not the best*

**Comment by odnar-dev** [comment]
i working on something like that, check it out : [vids](https://github.com/myos-archlinux/vids)

**Comment by trueauracoral** [comment]
> ahh, I was looking for an api to use for lbry, because scraping html with grep (we dont want to use pup do to installation difficulties on arch) is _not the best_
> 
> edit:
> although this api does not provide a lot of information about each video.
> 
> edit 2:
> i think there are too many limitations to use this viably
> 
> * search must be larger than 2 characters (like seriously why)
> * no information except video title.

That was the exact same concern I had. so I emailed the developer of lighthouse.  Here was his response:

when you are searching for something with lighthouse you can add a parameter to show more information. Take this api call for example:

https://lighthouse.lbry.com/search?s=odysee&include=channel,title

If you want to better understand what information you can get from a lighthouse search request you can use this example of what it has available:

{
    "bid_state": "Controlling",
    "cert_valid": true,
    "certificate_amount": 1054171020000,
    "channel": "@LBRY-Español",
    "channel_claim_count": 208,
    "channel_claim_id": "842e1e953dee991fffd2fa12c677043e7aed94c0",
    "claimId": "af33af7da3c83da3b3026c37d6f4132b358aeacb",
    "claim_cnt": 208,
    "claim_type": "stream",
    "content_type": "video/mp4",
    "cq_created_at": "2021-07-03T08:41:53Z",
    "description": "**ODYSEE RSS NOVEDADES**\n✅ *Bienvenid@s al Canal y Comunidad de “LBRY / Odysee en ESPAÑOL”* ✅\n**En el video de hoy, os Presentamos la NOVEDAD de las RSS en ODYSEE*\n___________________________________________________________________________________________________\n\n⭕ **COMUNIDAD \"LBRY | ODYSEE en ESPAÑOL\"** ⭕:\n 👉 **【 https://discord.gg/d8GmaWT 】**\n\n🔸 CANAL \"ODYSEE CAFE\"**🔸: \n👉【 http://bit.ly/OdyseeCafe 】\n\n🔸🔹 CANAL \"LBRY | ODYSEE en ESPAÑOL\"** :\n 👉 **【 http://bit.ly/Odysee-Español 】**\n__________________________________________________________________________________________________\n\n🟢 **ODYSEE CAFE** | LiveStream **COMUNIDAD LBRY | Odysee en Español** \n😍 *Cada Viernes a:*\n🇪🇸 | 🇪🇺 🕖 7*pm*\n🇲🇽 | 🇨🇴 🕛 12 *mediodia*\n🇻🇪 |   🕐 1*pm*\n🇦🇷 |   🕑 2*pm*\n🇺🇸 |   🕘 10*am* *[Arizona]*\n\n📽️👉 **【 http://bit.ly/OdyseeLive 】** \n__________________________________________________________________________________________________\n\n📕📚📘 **TUTORIALES ESENCIALES LBRY | ODYSEE en Español** [ Playlist ]  💼📗📋\n\n🎬 👉 **【 http://bit.ly/ODYSEE_PLAY 】**\n________________________________________________________________________________________________\n\n📲 **NUESTRAS REDES SOCIALES:**\n✔️ *Twitter:* @LBRYEspanol | @OdyseeEspanol\n",
    "duration": 170,
    "effective_amount": 103224877079,
    "fee": 0,
    "frame_height": 1080,
    "frame_width": 1920,
    "id": 16317654,
    "language": "es",
    "name": "ODYSEE-RSS",
    "release_time": "2021-07-03T08:41:39Z",
    "stripped_name": "ODYSEERSS",
    "sub_cnt": 0,
    "tags": [
      "Lbry",
      "lbry español",
      "odysee",
      "odysee español",
      "rss"
    ],
    "thumbnail_url": "https://spee.ch/9/4c4ff6a2cbcea7bb.png",
    "title": "🔴 ODYSEE | RSS ✅【 NOVEDADES 】",
    "transaction_time": "2021-07-03T10:02:02Z",
    "view_cnt": 0
  }
Each of these fields you could potentially include. Don't include many, just what you need, because it can be taxing to return this information. 

But basically you have a lot of info you can grab with this API. So I think it's viable to use.

**Comment by Euro20179** [comment]
This seems like a sufficient (quite much more than we need) amount to get this working!

**Comment by Euro20179** [comment]
> i working on something like that, check it out : vids

this is actually quite cool, and seems extremely extensible, which I would like to do with this script more.

**Comment by se7en-x230** [comment]
Looks promising.
Maybe both projects should combine forces to creat the one ring who controls them all.

**Comment by Euro20179** [comment]
#336 
I recommend to try it before I merge, if you want to try it
instructions
```sh
git clone https://github.com/Euro20179/ytfzf
cd ytfzf
git switch lbry
./ytfzf -O search
```

**Comment by se7en-x230** [comment]
NICE!!!
Works here but I had to change `video_pref="22" to ""` in my config as Odysee doesn't have this video quality indicator. 

Is there a way to just search across multiple video platforms as the default?
Meaning to use the -O switch if I ONLY want to search Odysee ... but the default just looks for "search term" through YT Odysee, Bitchute ... ?

**Comment by Euro20179** [comment]
> Works here but I had to change video_pref="22" to "" in my config 

does it not work otherwise?

> Is there a way to just search across multiple video platforms as the default?

I looked into implementing being able to search multiple platforms at once when I added -P, TBH I forget why I dropped it, I can look into it again.

**Comment by se7en-x230** [comment]
mpv throws an error 
![selected-21-07-18-11:29-36](https://user-images.githubusercontent.com/69777713/126055652-6a8fecf0-3b20-4305-870c-4fc7a2d39f7e.png)

Multiple platforms would be excellent as most people would not care where they find the infos.

**Comment by Euro20179** [comment]
I think it's video specific which formats work or not (which also applies to youtube), so i'll leave it as it is.

**Comment by se7en-x230** [comment]
For now it works IF the yt video quality format is left open as Odysee probably doesn't use the same system so label video quality.

**Comment by se7en-x230** [comment]
I would also want to change the fzf default show 30 results to 50 IF the -P option searches across multiple platforms. I can set `dmenu -l 50` but I can't find a setting that would do the same for the fzf option.

**Comment by Euro20179** [comment]
you can set `enable_fzf_default_opts=` in the config file, then you can export `FZF_DEFAULT_OPTS` in the config file or your shell's startup/rc file
