### ISSUE TITLE
[Feature Suggestion/Request] Display only a certain amount of most recent videos

### ISSUE THREAD

**Issue by jaredreardon** [pystardust/ytfzf#324]
As of now, you can set ytfzf to display your subscriptions by upload date, which I vastly prefer. The only issue is you can only set it to show the most recent videos _per channel_. So if you have a channel that uploads a video a day and you have it set to display 10 most recent videos per channel then you will see that channel's previous 10 days of videos. Alternatively, if you're subscribed to a channel that rarely uploads and have it set to show the most recent 10 videos per channel, then those videos may go back years. My suggestion or request would be to add an option to filter _strictly_ by upload date, regardless of channel. I.e. if you set it to display the 100 most recent videos form your subscriptions, it will show the 100 most recent videos, regardless of which channel. So depending on how often a channel uploads, there could be a dozen videos displayed or none. I think this just makes more sense for sorting subscriptions personally, and I'd be more than glad for this feature to be taken into consideration!

**Comment by Euro20179** [comment]
try using the `--sort` option

**Comment by jaredreardon** [comment]
> try using the `--sort` option

Yep, that's what I'm using now and I vastly prefer it to the default, personally. I more meant the ability to limit it to displaying only the most recent certain number of subscription videos, like displaying only the last 100 videos from channels you're subbed to, also allowing for channels that upload more frequently to have more items in said list than ones that may not. The way it works with the sort option is that every channel you're subbed to shows the same number of videos regardless of when they were uploaded. I hope this clarifies what I was suggesting a bit!

**Comment by Euro20179** [comment]
> allowing for channels that upload more frequently to have more items in said list than ones that may not

this will probably not happen as it would take a long time to compute.

> like displaying only the last 100 videos from channels you're subbed to

I will work on this.

**Comment by jaredreardon** [comment]
> > allowing for channels that upload more frequently to have more items in said list than ones that may not
> 
> this will probably not happen as it would take a long time to compute.
> 
> > like displaying only the last 100 videos from channels you're subbed to
> 
> I will work on this.

I may have phrased the part about channels uploading more frequently showing up more wrong. What I meant was to remove the limitation of how many videos per channel can show up if ytfzf is limited to only displaying the last X videos of all your subscriptions. So if you set it to only display you're last 100 subscriptions, and a channel uploads say 20 videos in that time, all 20 of those would be shown since it's sorted specifically by just the upload date. And thanks for looking into this!

**Comment by Euro20179** [comment]
> So if you set it to only display you're last 100 subscriptions, and a channel uploads say 20 videos in that time, all 20 of those would be shown since it's sorted specifically by just the upload date

ah, I think this should work if i get displaying the last x videos to work.

**Comment by Euro20179** [comment]
I have added `--video-limit` sadly it still has to download all the thumbnails if they are enabled, because subscriptions are downloaded out of order.
I will create a pr, and make an edit to this, you can try my pr and see if it's good or not.

**Comment by jaredreardon** [comment]
> I have added `--video-limit` sadly it still has to download all the thumbnails if they are enabled, because subscriptions are downloaded out of order.
> I will create a pr, and make an edit to this, you can try my pr and see if it's good or not.
> 
> Edit:
> #325
> 
> how to try it:
> 
> ```shell
> git clone https://github.com/Euro20179/ytfzf
> cd ytfzf
> git checkout video-limit
> ./ytfzf --video-limit=5 -S --sort
> ```

This does pretty much exactly what I was looking for. Plus I figured out how to get the whole showing as many videos per channel as may happen to have been uploaded in the most recent X videos, which is to just set the "sub_link_count" to some absurdly high number like 50. I don't know whether or not that degrades performance, but it seems to work for what I want of it. I set it to display my most recent 100 videos and with that setting it shows that correctly, and with my afforementioned setting, certain channels don't get artificially capped at 10 videos displayed in this 100 video period. Thanks for implementing this, especially so quickly! Hope to see it merged into the upstream at some point!

**Comment by Euro20179** [comment]
> I don't know whether or not that degrades performance

it might a little, also i believe the max is somewhere around 30-40 per channel because it can't scrape more than 1 page.

**Comment by jaredreardon** [comment]
> > I don't know whether or not that degrades performance
> 
> it might a little, also i believe the max is somewhere around 30-40 per channel because it can't scrape more than 1 page.

Good to know about that. Just playing around with the settings, at the 150 most recent videos from my subs, I noticed anything above 30 is drastically overkill anyways, since none of the channels monopolize that much of the most recent 150 videos list. So thanks again. Unless you see some reason to keep it open, I'd say this issue can be closed now? Especially with a pr already created.
