### ISSUE TITLE
ytfzf doesn't seem to work with some youtube URLs. The behaviour is random and unpredictable.

### ISSUE THREAD

**Issue by kibybyte** [pystardust/ytfzf#330]
I'm on Arch Linux so I have the latest version of everything including dependencies and such. I am using i3-gaps on Xorg. I am using xfce4-terminal although issue happens in alacritty, kitty, lxterminal and st(Luke Smith's build) as well.

https://user-images.githubusercontent.com/85624218/125832730-5fb0596b-b334-4fe4-ba34-f7b15b37bf8c.mp4

This video demonstrates one such example. I am using ytfzf in a script I made to stream youtube audio from the CLI minimally and efficiently. This is how I cam e to know of the issue, it had happened in the past too.

```sh
#!/bin/sh
query="$@" 
[ "$query" = "" ] &&  read -p "Input query: " query
url="$(ytfzf -t -L "$query")"
mpv --ytdl-format=bestaudio "$url"
```

**Comment by Euro20179** [comment]
I know what the problem is, but I'd just like to know if it happens on any other videos that aren't a playlist.

**Comment by Euro20179** [comment]
you can try #331 by running 
```sh
git clone https://github.com/Euro20179/ytfzf
cd ytfzf
./ytfzf -t -L 80s playlist
```

**Comment by kibybyte** [comment]
> you can try #331 by running
> 
> ```shell
> git clone https://github.com/Euro20179/ytfzf
> cd ytfzf
> git checkout fix-links
> ./ytfzf -t -L 80s playlist
> ```

Thank you this worked. Could you please tell me what the issue under the hood was?? I'm not very proficient but I'd be interested in knowing.

**Comment by kibybyte** [comment]
>also maybe you don't want to use it but ytfzf has a -m option which plays audio only.

This might have saved me quite some time, but I guess I was just a bit too lazy 😅

**Comment by Euro20179** [comment]
>  Could you please tell me what the issue under the hood was?? I'm not very proficient but I'd be interested in knowing.

the problem, was that to check what kind of link you selected it checks the length of the id length of 11, playlists (i thought) have a length of 34 but, your issue showed that sometimes they can be a length of 18, and peertube videos have a length of 36.
 
> This might have saved me quite some time, but I guess I was just a bit too lazy to read ytfzf -h fully

i usually skim things unless i am really looking for something lol.
