### ISSUE TITLE
Add support for bemenu

### ISSUE THREAD

**Issue by Mederim** [pystardust/ytfzf#332]
since wayland is a option to xorg, will be good to add suport to wayland programs like bemenu.

**Comment by Euro20179** [comment]
from my testing setting `external_menu="bemenu -l 30"` in `~/.config/ytfzf/conf.sh` or running `YTFZF_EXTMENU="bemenu -l 30" ytfzf search` seems to work.

**Comment by Mederim** [comment]
thats works just need to use extra -D option
