### ISSUE TITLE
Change resolution when cache speed is slower than playing speed

### ISSUE THREAD

**Issue by anishmittal2020** [pystardust/ytfzf#335]
Sometimes the internet is not reliable, it would be nice if it is possible to automatically change resolution when cache speed is slower than playing speed (saying continuously for 5 seconds) and when the difference between max cache position and current playing position is less than 30 seconds. 

And may be it could step up resolution if the internet has good connection.

**Comment by Euro20179** [comment]
this is a good idea, but impossible to code into ytfzf, you should look into mpv's config.
