### ISSUE TITLE
Is there a way to reload subscriptions without exiting ytfzf?

### ISSUE THREAD

**Issue by har5ha** [pystardust/ytfzf#341]
Hello,

Thanks! for a wonderful application/script. I was wondering if there is a way(shortcut key?) to "reload" all my subscriptions without exiting ytfzf (I have set it up to return back to ytfzf window after a video ends).

Cheers! and Thanks in advance!

**Comment by Euro20179** [comment]
In config check if you have the `shortcuts` variable set, otherwise add this line `shortcuts="alt-l,alt-t,alt-o,alt-v,alt-d,alt-m,alt-s,alt-enter"`

then at the end of the string add `,$your_keybind_here`, where your_keybind_here is any keybind that will work with fzf eg: alt-r.

then add this function

```sh
handle_custom_shortcuts () {
    case "$selected_key" in
        alt-r)
            clean_up
            #put whatever you use to launch fzf with subscriptions here
            ytfzf -S --sort
            ;;
    esac
}
```

be aware that in the next update `shortcuts` is being renamed to `key_binds` and `handle_custom_shortcuts` is being renamed to `handle_custom_keybinds`

**Comment by har5ha** [comment]
Thanks! for a quicks reply.

It looks like the following are already taken, so I added alt-y to the following list, and set the `return 1` , in the function . 



`shortcuts="alt-l,alt-t,alt-o,alt-v,alt-d,alt-m,alt-s,alt-enter,alt-y"`

```
handle_custom_shortcuts () {
    case "$selected_key" in
        # Using alt-l to load/reload my subscriptions
        alt-y)
            clean_up
            #put whatever you use to launch fzf with subscriptions here
            ~/bin/ytfzf -S --sort
            ;;
    esac
return 1
}
```
As I use DWM window manger, which uses "alt" extensively. Is there a list where I can find alternate keys, available for binding?

TIA

**Comment by Euro20179** [comment]
`man fzf` has a list of available keys

sadly most of the binds start with alt.

**Comment by har5ha** [comment]
> `man fzf` has a list of available keys
> 
> sadly most of the binds start with alt.

Thanks a lot!

**Comment by har5ha** [comment]
Replaced the above function :

```
handle_custom_shortcuts () {
    case "$selected_key" in
        # Using alt-l to load/reload my subscriptions
        alt-y)
            clean_up
            #put whatever you use to launch fzf with subscriptions here
            ~/bin/ytfzf -S --sort
            ;;
    esac
return 1
}

```
With this :

```
handle_custom_shortcuts () {
    case "$selected_key" in
        # Using alt-l to load/reload my subscriptions
        alt-y)
            clean_up
            #put whatever you use to launch fzf with subscriptions here
            ~/bin/ytfzf -S --sort
            return 1
            ;;
    esac
return 0
}
```

For More Info on : [why?](https://github.com/pystardust/ytfzf/issues/342)

**Comment by Euro20179** [comment]
actually this function shouldn't be called with -D (in external menus) because it wouldn't work with them.

**Comment by Euro20179** [comment]
In addition, there is a slight difference between return 1 and return 0,

return 0 says do nothing
return 1 says exit
return 2 says restart the main loop

I will fix the -D bug in the development branch, so if you want to use it, you should update and change the variable names (ytfzf should give you a warning and exit if you dont change them)

**Comment by har5ha** [comment]
> actually this function shouldn't be called with -D (in external menus) because it wouldn't work with them.
Yes, I experienced it when I returned 0 inside the case statement or) when return 0 or) 2 at the end/return from the function.

So I finally had to settle for the above. Now My Keybinding works with -D option too, so far.
