### ISSUE TITLE
Video stops after 3minutes audio continues

### ISSUE THREAD

**Issue by JostBrand** [pystardust/ytfzf#348]
When i watch any yt video the mpv video playback stops at 3 1/2 minutes and only the audio continues.

In the browser I can watch them normally. 

artix everything up2date

Any suggestitions what i should do ?

**Comment by trueauracoral** [comment]
I would suggest making sure your mpv and ytdl are up to date. If those programs aren't then weird stuff happens.

**Comment by JostBrand** [comment]
Sorry it was related to ytdl video prefs
