### ISSUE TITLE
Feature request: restore list after closing mpv

### ISSUE THREAD

**Issue by timsofteng** [pystardust/ytfzf#349]
Hello. Is it possible to back to the list of results when mpv has been closed?

**Comment by westofer** [comment]
yeah just `-l`

```
     -l, --loop                             Loop: prompt selector again after video ends
```

**Comment by timsofteng** [comment]
> yeah just `-l`
> 
> ```
>      -l, --loop                             Loop: prompt selector again after video ends
> ```

great!
Closed
