### ISSUE TITLE
History results are messed up!

### ISSUE THREAD

**Issue by lamyergeier** [pystardust/ytfzf#350]
```bash
$ /usr/bin/ytfzf --version
ytfzf: 1.2.0
youtube-dl: 2021.06.06
fzf: 0.27.2 (brew)
```

- When we type `ytfzf -H` the history displayed is completely messed up by fzf! The lines starts to get stuck in the display:

![image](https://user-images.githubusercontent.com/42092626/127686396-75087e98-5a19-4f64-9b57-d725c7600ca4.png)

```bash
$ ytfzf -H
column: Invalid or incomplete multibyte or wide character
```

As you can see the cursor is in the middle blinking !

**Comment by Euro20179** [comment]
I think this is a simliar problem to #372
