### ISSUE TITLE
use sxiv as an external menu

### ISSUE THREAD

**Issue by odnar-dev** [pystardust/ytfzf#351]
i was tying to find a way to show thumbnails in my script [vids](https://github.com/MyOS-ArchLinux/vids/tree/thumbs).
so i thought why not `sxiv`.
i think it can be implemented in your script to.

![image](https://user-images.githubusercontent.com/73726132/128048928-81d2707f-c270-48a1-805c-603eff3a0872.png)
![image](https://user-images.githubusercontent.com/73726132/128049010-80922e1a-664b-4106-9a3e-04862885f34f.png)

**Comment by pfr-dev** [comment]
@odnar-dev this is pretty cool. I just thought I'd ask if you managed to find a way to incorporate this with ytfzf?? 

I've taken a look at your `vids` script and it looks cool but I cant see `sxiv` as a dependency anywhere?

**Comment by Euro20179** [comment]
put [this script](https://github.com/pystardust/ytfzf/blob/master/addons/interfaces/sxiv) in `~/.config/ytfzf/interfaces`, and run `ytfzf --interface=sxiv`.
I'm not sure how odnar-dev did it though, since he did it before I made it easier to do.
