### ISSUE TITLE
add '-i' arguments to ignore "Sign in to confirm your age" error

### ISSUE THREAD

**Issue by HexorCatZ** [pystardust/ytfzf#352]
just had an error on "Sign in to confirm your age" while downloading a playlist and it makes the program run on a loop.
basically, start from the start of the playlist until it meets the error video and it restart from the start.
running `youtube-dl` with `-i` arguments works.

i want to fork this project but im just too tired (and lazy) atm. sorry.
maybe later. :wink: 

edit : sorry for my bad eng. its past midnight. :sleeping:

**Comment by pirate486743186** [comment]
you may want to try yt-dlp
it works with most (not all) age restricted videos

**Comment by Euro20179** [comment]
In 2.x you can use `ytfzf --ytdl-opts='-i' ...`
