### ISSUE TITLE
Issue with subscriptions lately

### ISSUE THREAD

**Issue by Kabouik** [pystardust/ytfzf#357]
I don't use subscriptions very often so I don't know when this started to happen, but I am getting the following error with subscriptions on both the latest stable and unstable versions of `ytfzf`:

```bash
$ ytfzf -S --sort
sed: can't read /subscriptions: No such file or directory
ERROR[#01]: Couldn't curl website. Please check your network and try again.
Check for new versions and report at: https://github.com/pystardust/ytfzf
```

This is my `~/.config/ytfzf/subscriptions` file, and I also tried commenting out all URLs but one to check if the issue would be with just some URLs:

```bash
# Tech/Linux channels
https://www.youtube.com/channel/UC2NXVB__-v-hf-l6wcg1zjQ/videos # tom on the internet
https://www.youtube.com/channel/UCJetJ7nDNLlEzDLXv7KIo0w        # gavin freeborn
https://www.youtube.com/c/DistroTube/videos                     # distrotube
#https://www.youtube.com/c/LukeSmithxyz/videos                   # luke smith
https://www.youtube.com/channel/UCngn7SVujlvskHRvRKc1cTw/videos # bugswriter
https://www.youtube.com/c/MentalOutlaw/videos                   # mental outlaw
https://www.youtube.com/c/gotbletu/videos			# gotbletu
https://www.youtube.com/c/BrodieRobertson/videos		# brodie robertson
```

**Comment by Euro20179** [comment]
try adding `subscriptions_file="$HOME/.config/subscriptions"` to `~/.config/ytfzf/conf.sh`

**Comment by Kabouik** [comment]
Thanks! That should be `subscriptions_file="$HOME/.config/ytfzf/subscriptions` in my case, and I can confirm it works.

Any reason why `subscriptions_file=$YTFZF_CONFIG_DIR/subscriptions` no longer works? `$YTFZF_CONFIG_DIR` is indeed empty when I check my env, but at some point `ytfzf` could find my subscriptions without me tempering with that option.

**Comment by Kabouik** [comment]
Alright, silly me. I just found this in the configuration file:

```
###################
#  ENV VARIABLES  #
###################

#this variable should be set somewhere other than here or it will not work

#YTFZF_CONFIG_DIR=$HOME/.config/ytfzf
```

I don't know why it used to work before doing it, but I sure now what I should do now! Sorry for the noise.
