### ISSUE TITLE
Please make the --update function actually update the script and not install it in /usr/bin/ 

### ISSUE THREAD

**Issue by pitsi** [pystardust/ytfzf#361]
So, I was searching the output of `ytfzf --help-all` for anything useful to add on my conf.sh and I came accross the `--update` function.
And I gave it a shot
```
$ ytfzf --update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55169  100 55169    0     0   117k      0 --:--:-- --:--:-- --:--:--  117k
[sudo] password for user: 
```
As seen in lines 1261 to 1278, the function tries to install the script in /usr/bin. 

That is not what it should do. Why install it system wide? I have all sorts of scripts in ~/bin and, the ones that have an update function (e.g. yt-dlp), simply download the new version of themselves in there and not anywhere system wide.

**Comment by odnar-dev** [comment]
i think this can be solved by checking where ytfzf is installed (using `which ytfzf`) than using that as target for update

**Comment by pitsi** [comment]
Not what I hoped for. Now, instead of /usr/bin/, the --update function installs to /usr/local/bin/. 
I didn't mean that! For my situation, it should update the binary in my ~/bin/ and leave the system's folders intact. Why don't you make an --install function that does that, for the ones that actually want to install it that way?  

Long story short, that commit only solves issue #368 and not this one. And I would reopen it if it was possible.

**Comment by Euro20179** [comment]
it installs to $0 which is the path to the script thag is running.

**Comment by pitsi** [comment]
You are right.
```
$ ytfzf --update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55162  100 55162    0     0  98679      0 --:--:-- --:--:-- --:--:-- 98679
ytfzf successfully updated.
```
This commit here confused me and I did not test it yesterday when I made the post.
https://github.com/pystardust/ytfzf/commit/9bed019b64de4a08366c9d4211ae1bc13b6c7b52
