### ISSUE TITLE
How to use Yt-dlp instead of youtube-dl?

### ISSUE THREAD

**Issue by fossimprove** [pystardust/ytfzf#372]
As the title says, been hearing good review on yt-dlp being very efficient with loads of improvements, so Can anyone let us know how to use yt-dlp instead of youtube-dl ?

**Comment by Ramiferous** [comment]
I came here to ask the same thing. Perhaps `ytfzf` might repace `youtube-dl` with `yt-dlp` as a dependency in the furutre. It certainly looks like a worthwhile replacement.

**Comment by Euro20179** [comment]
You could edit the source code and just replace youtube dl, or yould make a symlink `sudo ln -s "$(which yt-dlp)" /usr/bin/youtube-dl`

> Perhaps ytfzf might repace youtube-dl with yt-dlp as a dependency in the furutre

We are currently rewriting the script, there is an option `--ytdl-path` (or something like that), you could run `ytfzf --ytdl-path=yt-dlp` and it will use yt-dlp instead

**Comment by Ramiferous** [comment]
> We are currently rewriting the script, there is an option `--ytdl-path` (or something like that), you could run `ytfzf --ytdl-path=yt-dlp` and it will use yt-dlp instead

Would you mind reporting back here when it is updated to include this functionality? Please and thanks you :)

**Comment by Ramiferous** [comment]
> We are currently rewriting the script, there is an option `--ytdl-path` (or something like that), you could run `ytfzf --ytdl-path=yt-dlp` and it will use yt-dlp instead

Would you mind reporting back here when it is updated to include this functionality? Please and thanks you :)

**Comment by Euro20179** [comment]
yt-dlp is the default in the new update.
