### ISSUE TITLE
adding subtitles?

### ISSUE THREAD

**Issue by westofer** [pystardust/ytfzf#4]
maybe an option  check subtitles ?

**Comment by pystardust** [comment]
Press capitol "J" while watching a youtubevideo on mpv. If subs available then they will be shown

**Comment by anishmittal2020** [comment]
@pystardust  

> Press capitol "J" while watching a youtubevideo on mpv. If subs available then they will be shown

Nothing happens!

```bash
$ ytfzf --version
ytfzf: 1.2.0
youtube-dl: 2021.06.06
fzf: 0.27.2 (brew)
```

- On pressing J it says no subtitles:

```bash
ytfzf https://www.youtube.com/watch?v=w4sLAQvEH-M
````

- On pressing J subtitles are displayed

```bash
mpv --no-config --fs --ytdl-raw-options=ignore-config=,sub-lang='en',write-sub=,write-auto-sub= https://www.youtube.com/watch?v=w4sLAQvEH-M
````

**Comment by westofer** [comment]
@anishmittal2020 subtitles are /only/ work 'automatically' when they are not auto generated!
if you want them to work on autogenerated subs, use the flag `--subt`

`ytfzf --subt <search term>`

you can also add this to you config, which you can check the documentation for, 

hope it works!

**Comment by anishmittal2020** [comment]
@westofer The link that I mentioned has a normal subtitle along with autogenerated ones!

**Comment by westofer** [comment]
@anishmittal2020 apologizes! didnt see the link

it werks :)

![watch?v=w4sLAQvEH-M-00 00 03 170-#1](https://user-images.githubusercontent.com/50760091/127736529-950501f9-fa3d-4024-9fcb-bc301a1817ae.png)


didn't even know that one can use links directly

**Comment by anishmittal2020** [comment]
@pystardust 

For me the subtitles are not displayed. Could it be due to `~/.config/mpv/mpv.conf`? Does ytfzf uses it? Any suggestions?

**Comment by LinArcX** [comment]
Hello,
`--subt` doesn't work for me also.

**Comment by MuhammadKotb** [comment]
--subt does not work for me too
