### ISSUE TITLE
Thumbnails only shown with sudo

### ISSUE THREAD

**Issue by jjanella** [pystardust/ytfzf#401]
As said i can only see thumbnails if i run with sudo.
Tried with ueberzug from pacman/pip3 it doesnt change anything or seem to be the issue.
afaik fzf is fully updated `0.27.2 (8255aa2)`

Arch
fully updated
i3wm
urxvt

**Comment by Euro20179** [comment]
is there any error, or do thumbnails just not work?

**Comment by die-MS** [comment]
no errors

**Comment by Euro20179** [comment]
I'm honestly not sure what's happening here, you could try updating ytfzf by running `ytfzf --update`, or switching to the development or rewrite branch
```sh
#change to rewrite for rewrite branch
ytfzf --update-unstable=development
```

Another solution would be to change the line with
```sh
FIFO="/tmp/ytfzf-ueberzug-fifo-$PROC_ID"
```
to
```sh
FIFO="$HOME/.cache/ytfzf-ueberzug-fifo-$PROC_ID"
```

You could also try adding `chmod +xrw "$FIFO"` after the line `[ -e $FIFO ] || { mkfifo "$FIFO" || exit 1 ; }`.

Sometimes weird things happen with shells, so you could try running `bash $(which ytfzf)`.

Id recommend doing these 1 at a time in case it works.

**Comment by die-MS** [comment]
`ytfzf --update` nothing changed


`ytfzf --update-unstable=developement` 
```
On the dev branch these errors are shown
Scraping Youtube...
/usr/bin/ytfzf: line 954: /tmp/ytfzf-subjson: Permission denied
Downloading Thumbnails...
/usr/bin/ytfzf: line 495: kill: (1003560) - No such process
```
permissions for /tmp/ytfzf-subjason are `-rw-r--r--`

`ytfzf --update-unstable=rewrite`
no errors, no thumbnails again

now i try as sudo again and there are no thumbnails as sudo!
it does however spit out the line `/usr/bin/ytfzf: line 861: /tmp/ytfzf-subjson: Permission denied`
so i `chmod 775 /tmp/ytfzf-subjson` and still complains about not having permissions to open that file so idk why not. running it with sudo now also has a very distorted output with random lines showing 
![image](https://user-images.githubusercontent.com/90074403/135500044-6cc6c910-2180-43b1-97c2-1ba2e701c463.png)
 before i do more tests i want to revert everything back to how it as before i did this so i know what fixed it

**Comment by Euro20179** [comment]
to revert back, you can do
```sh
git clone https://gtihub.com/pystardust/ytfzf
sudo make install
```

> /usr/bin/ytfzf: line 954: /tmp/ytfzf-subjson: Permission denied

I had a feeling it'd be related to this, but it's odd that you gave it 755 and it's still an error,
you should try changing the FIFO path to something in your $HOME directory.

> with sudo now also has a very distorted output with random lines showing

That error is saying it can't find ueberzug, try reinstalling it with `pip3 install ueberzug`, maybe try `sudo pip3 install ueberzug` as well.

You can test if ueberzug is working just by running `ueberzug` in a terminal to see if there are errors.

**Comment by die-MS** [comment]
just to refresh the current state of things, i did 
```
chmod 777 /tmp # not ideal ik but idc
git clone https://github.com/pystardust/ytfzf
cd ytfzf
sudo make install
```
`./ytfzf -t search` -> no errors, no thumbnails
`sudo ./ytfzf -t search` -> `./ytfzf: line 861: /tmp/ytfzf-subjson: Permission denied` and thumbnails work

ueberzug is working from pip3
```
$ ueberzug
Usage:
    ueberzug layer [options]
    ueberzug library
    ueberzug version
    ueberzug query_windows PIDS ...
```

now im going to edit FIFO again hopefully that works

**Comment by Euro20179** [comment]
If you have a configuration file set, try
`YTFZF_CONFIG_DIR=. ytfzf -t search`
if this fixes it it might be something in your config, then again,
> `sudo ./ytfzf -t search -> ./ytfzf: line 861: /tmp/ytfzf-subjson: Permission denied`

this is very odd

> i just noticed this idk if it was there before, when i run with sudo and the thumbnails are showing, the little loading lights dont show but they do show when i dont run with suo (and thumbnails arent showing). idk if thats any help in debugging its just something i noticed

Interesting.... this is an `fzf` feature, in `fzf` you can make it run a script when a new item is selected, it may be that ueberzug or ytfzf is hanging.

try creating a script with this and running it:

```sh
file_path="./test-fifo"
image_to_test="path-to-image-to-test-wtih"
mkfifo "$file_path"
ueberzug layer --parser json --silent < "$FIFO" &
exec 3>"$file_path"
{
    printf '{ "action": "add", "identifier": "test", "path": "%s",' "$image_to_test"
    printf '"x": %d, "y": %d, "scaler": "fit_contain",' 0 0
    printf '"width": %d, "height": %d }\n' "20" "20"
} > "$FIFO"

**Comment by die-MS** [comment]
```
file_path="./test-fifo"
image_to_test="$HOME/Pictures/Piggies/reese.jpg" # I think i did this right? its a valid path
mkfifo "$file_path"
ueberzug layer --parser json --silent < "$FIFO" &
exec 3>"$file_path"
{
    printf '{ "action": "add", "identifier": "test", "path": "%s",' "$image_to_test"
    printf '"x": %d, "y": %d, "scaler": "fit_contain",' 0 0
    printf '"width": %d, "height": %d }\n' "20" "20"
} > "$FIFO"
```
produces `line 4: : No such file or directory`


I noticed the description of the video does a flash then disappears as soon as a video is selected without sudo, and shows as expected with sudo

**Comment by Euro20179** [comment]
yeah, that's my fault, $FIFO is nothing special, just a variable, forgot to change it to $file_path
and yes you did do the image path thing correct.

I have to debug that script since it may or may not work, and i was away from my computer so i couldn't before.

You might also want to try deleting ~/.Xauthority and then restarting xorg (log out, log back in)

**Comment by die-MS** [comment]
![image](https://user-images.githubusercontent.com/90074403/135541892-433ab9a1-fcac-4d45-8564-6b784129a1db.png)

looks bugged

**Comment by Euro20179** [comment]
I'm running out of ideas, I'm pretty sure it's a problem with ueberzug, but i'm not sure,
try uninstalling ueberzug and reinstalling it, also try updating fzf, not sure how it would be outdated considering you're running arch lol.

**Comment by die-MS** [comment]
ah well thanks for your help. sudo isnt that bad of an issue i just thought it was unnessecary

**Comment by Euro20179** [comment]
@jjanella idk if you still have this issue, but if you installed `ueberzug` with `sudo pip install ueberzug` try uninstalling it, then reinstalling it with `pip install ueberzug` (no sudo)
