### ISSUE TITLE
search channels

### ISSUE THREAD

**Issue by henkmet** [pystardust/ytfzf#403]
I think it would be really useful if it is possible to get a list of all videos in a channel (uploaded by the same user). Maybe it's already possible but I haven't found how to do it.

**Comment by Euro20179** [comment]
Currently its not possible to get *all* the videos from a channel, but it is technically possible to get a lot, but its not very elegant.

First, put the channel you want to get the videos from in ~/.config/ytfzf/subscriptions, then run ytfzf --subs=1000.
If you use the subscriptions file, make a backup of it, and get rid of all the other links in it.

You wont end up with 1000 videos, probably only like 20 or 30.

**Comment by Euro20179** [comment]
in the rewrite of this script, you can use `ytfzf --type=channel search` which will search youtube for channels, then you can select a channel. if you want to search a channel directly you can do
`ytfzf -cinvidious-channel 'channel-link'`
