### ISSUE TITLE
Error in getting subscriptions

### ISSUE THREAD

**Issue by keyb0ardninja** [pystardust/ytfzf#404]
I'm getting this error:
```
$ ytfzf -S

sed: can't read /subscriptions: No such file or directory
ERROR[#01]: Couldn't curl website. Please check your network and try again.
Check for new versions and report at: https://github.com/pystardust/ytfzf
```

There are certainly no problems with my network because I can search and watch videos through `ytfzf` itself.

Also:

```
$ cat ~/.config/ytfzf/subscriptions

# file : ~/.config/ytfzf/subscriptions
## tech channels

https://www.youtube.com/c/LukeSmithxyz/videos                   # luke smith
https://www.youtube.com/channel/UCngn7SVujlvskHRvRKc1cTw/videos # bugswriter
https://www.youtube.com/c/DistroTube/videos                     # distrotube
https://www.youtube.com/c/MentalOutlaw/videos                   # mental outlaw
```

**Comment by Euro20179** [comment]
add this to `~/.config/ytfzf/conf.sh`
`subscriptions_file="$HOME/.config/ytfzf/subscriptions"`,
if that doesn't work try `ytfzf --update`

**Comment by keyb0ardninja** [comment]
> ytfzf --update

I had already tried that before and that didn't work.

I figured out the problem. I had been using the sample file provided while making edits to it along the way. See this line [here](https://github.com/pystardust/ytfzf/blob/318bca34d778c5da45c57d5ee972cdc7a2843d0c/docs/conf.sh#L321):

`subscriptions_file=$YTFZF_CONFIG_DIR/subscriptions`

The correct line should be:

`subscriptions_file=$config_dir/subscriptions`

I can confirm that it works now with that change. I hope someone updates the sample file to correct this mistake.

**Comment by Euro20179** [comment]
> I can confirm that it works now with that change. I hope someone updates the sample file to correct this mistake.

We are moving everything into a man page in the rewrite of the script, so that default settings like these can be fixed by updating the script, instead of telling everyone there's a bug in conf.sh.
