### ISSUE TITLE
ytfzf behaving slowly

### ISSUE THREAD

**Issue by luispengler** [pystardust/ytfzf#418]
Some weeks ago, when I started using ytfzf to watch some videos, it was even faster when caching the youtube, I never wanted to get back.
But recently, my download rate in ytfzf is extremely low, and it takes a lot of time to buffer hd and full hd videos.
(I have a 100Mbps internet and youtube is working normally)

**Comment by se7en-x230** [comment]
Issue is.with youtube-dl. Switch to yt-dlp and you get the old speed back.

**Comment by NoRMaNxLLy** [comment]
same thing here, this speed throttle is caused by youtube-dl.

**Comment by VarLad** [comment]
@Euro20179 Any ETA on when there'll be playing from playlist feature in the rewrite?

**Comment by Euro20179** [comment]
@VarLad you can create a playlist, in the rewrite although it's not the most user friendly, basically you create a file with `[]` in it, then you can run `ytfzf -I VJ <search>` then take the output and add it inside the list in the file. Then you can run `ytfzf -cp <path-to-playlist>`, if you want to see an example of a playlist, just look at `~/.cache/ytfzf/watch_hist` (but it needs to be the new watch_hist from the rewrite)
