### ISSUE TITLE
What Causes the -l Function to not Work with Swallow Patch?

### ISSUE THREAD

**Issue by amarakon** [pystardust/ytfzf#420]
I use the DWM swallow patch. It says that there is a bug where if you use -l with the swallow patch, the thumbnails won't load. This is true, the thumbnails don't load after I close mpv and go back to the TUI. I'm curious, what causes this bug. Also, do you think there is a way to fix it? If not, that's fine, since I prefer using ytfzf in dmenu most of the time.

**Comment by Euro20179** [comment]
Bit late, but, I have no idea what causes the bug, it probably has to do with dwm swallowing ueberzug, so if you used a different thumbnail viewer it'd probably work.
