### ISSUE TITLE
I Suggest Using yt-dlp Instead of youtube-dl

### ISSUE THREAD

**Issue by Amarakon55** [pystardust/ytfzf#421]
By default this script uses youtube-dl. Youtube-dl is awful for streaming youtube videos in mpv. It buffers every two seconds. It's impossible to watch videos this way. yt-dlp, however, is really smooth and does not buffer for me. I can easily replace youtube-dl with yt-dlp in this script, but I'm suggesting for you to default to yt-dlp.

**Comment by Euro20179** [comment]
Considering that youtube-dl is not being updated, this seems like a very sensible thing to do,

I will implement this in the rewrite

**Comment by kibybyte** [comment]
I second this suggestion, in fact just earlier this day I was thinking of opening an issue so thanks to @Amarakon55 :)

However I'd suggest keeping yt-dlp and youtube-dl as deps instead of forcing everyone on yt-dlp because lots of distros probably don't have yt-dlp in their official repos just yet.

 Also after this is done I'll have to ask the aur maintainer to not have youtube-dl as a hard dep, unless this is decided upstream?

**Comment by Amarakon55** [comment]
There is a package in the aur called yt-dlp-drop-in which emulates youtube-dl for yt-dlp. So if any package you use wants youtube-dl, it will use yt-dlp instead. There is also a package in the aur called ytfzfim which claims to be a slightly improved ytfzf but I'm not sure if that's true because even the readme on the person's GitHub doesn't explain it.

**Comment by Amarakon55** [comment]
ytfzfim has fewer lines of code than ytfzf.

**Comment by kibybyte** [comment]
ytfzfim still does use youtube-dl :(
in fact i have ytfzfim lol

**Comment by Amarakon55** [comment]
What error did ytfzfim give you? I'm curious.

**Comment by pirate486743186** [comment]
This is actually urgent!
youtube-dl relatively regularly brakes on youtube, and this time, no one will fix it.
So this should be implemented in the current version also.

**Comment by beefandcheesepie** [comment]
Hi folks, I have a couple of tools dependent on youtube-dl like [iina](https://github.com/iina/iina), symlink could be a workaround.  I'm on Mac so you may need to tweak the code if you are on a different OS. This should be fine even if you use homebrew. 

1. remove youtube-dl. If you don't have mysophobia just `rm /usr/local/bin/youtube-dl`
2. create a symlink. Assuming you already have ytb-dlp installed `ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl`
3. problem solved, enjoy streaming the video at your full bandwidth. :)

**Comment by is0n** [comment]
I use `mpv` and using the following in my `mpv.conf` allows me to use yt-dlp...
```
script-opts-append=ytdl_hook-ytdl_path=yt-dlp
```
I imagine it would be similar for other video players

**Comment by kibybyte** [comment]
@is0n from mpv ver 0.34, mpv auto detects and uses yt-dlp when available. What you've written is necessary for ver 0.33 and before.

**Comment by kibybyte** [comment]
@Amarakon55 

>What error did ytfzfim give you? I'm curious.

I don't remember exactly now, but the script would fail complaining about missing something at some line, like a "line X Y not found" and i tried looking for it a bit but then decided ytfzf just works fine for me and i gave up on digging 😀

**Comment by GabrieleRisso** [comment]
> script-opts-append=ytdl_hook-ytdl_path=yt-dlp

works great with youtube-dl 2021.06.06 + yt-dlp 2021.12.01-1 + mpv 1:0.34.0-2
thanks @is0n, I was running into problems lately with ytfzf stating that my youtube-dl version was severly outdated.

**Comment by Euro20179** [comment]
Bit late, but, in the next version, yt-dlp will be preferred, if it's not installed, it'll use youtube-dl, unless you use the `--ytdl-path` option to set the path to a youtube-dl esk program manually.

Also since yt-dlp is now used in the current version i'll close this.
