### ISSUE TITLE
ytfzf search crashes my terminal

### ISSUE THREAD

**Issue by one618** [pystardust/ytfzf#422]
I'm on arch Linux and i have all dependencies installed
ueberzug
fzf
youtube-dl
mpv
jq

every time i try to search my terminal crashes,
any ideas what might be causing this issue ?

**Comment by parallelqw** [comment]
Should not every time, but you should expect crashing from search. I figured out, if it tries to show long results more than the ytfzf script supports, it crashes.

**Comment by Euro20179** [comment]
> export YTFZF_EXTMENU="dmenu -l 30"

This has been changed to a function so, you can add this to `~/.config/ytfzf/conf.sh` instead of that variable.
```sh
external_menu () {
    dmenu -l 30
}
```

**Comment by Euro20179** [comment]
If you're using st it might be because it's trying to display non-ascii characters

**Comment by Quuinnn** [comment]
> If you're using st it might be because it's trying to display non-ascii characters

I am using st, and my terminal crashed very often

**Comment by Euro20179** [comment]
you should try using a different terminal, or patching st to have unicode support.

If youve alreasy patched st I would just try a different terminal

**Comment by 3009aksingh** [comment]
Yeah, ytfzf didn't worked in kitty, while it worked flawlessly in GNOME terminal. Thanks @Euro20179  :)
