### ISSUE TITLE
Ability to start download in background of loop mode

### ISSUE THREAD

**Issue by novoid** [pystardust/ytfzf#426]
Hi,

I'm using `ytfzf -t -l` and I would love to have a keyboard shortcut to start a `youtube-dl`-process (or actually any user-configurable external tool) on the current video.

Sometimes I just want to pre-download videos for later usage and sometimes ytfzf does have issues with streaming and buffering so I prefer using `ytfzf` for browsing and searching videos and playing local videos instead afterward.

**Comment by Euro20179** [comment]
Try using alt-d while in fzf.

**Comment by novoid** [comment]
This starts the download but does quit ytfzf after the download.

**Comment by Euro20179** [comment]
use `-l`
