### ISSUE TITLE
Option to use yt-dlp as a replacement for youtube-dl

### ISSUE THREAD

**Issue by novoid** [pystardust/ytfzf#428]
Hi,

youtube-dl has some issues such as it gets [throttled by Google](https://www.reddit.com/r/youtubedl/comments/q6r74m/youtubecom_downloads_with_youtubedl_are_slow/). 

https://github.com/yt-dlp/yt-dlp seems to be a reasonable replacement. Therefore, I would love to see an option to choose this alternative download tool in ytfzf.

**Comment by Theory-of-Everything** [comment]
yt-dlp should work exactly the same if you just simlink the `yt-dlp` binary to `youtube-dl`
I have yt-dlp installed via the AUR (for arch) and did the above.

**Comment by novoid** [comment]
Hi Theory,

While this workaround may for for most use-cases (I wanted to write "in theory" but I decided not to do this pun - oh I did it anyway. Damn), it doesn't if I need to keep `youtube-dl` around in parallel for some reasons.

**Comment by uestueab** [comment]
It is not a good idea to make users have two redundant binaries. Just make it read from a list of providers (ytdl, ytdlp, etc..)

**Comment by leoperegrino** [comment]
`mpv` by itself supports changing the default ytdl path, either by config file or command line arguments. 
`mpv` config file can be found in `$XDG_CONFIG_HOME/mpv/mpv.conf`, `$HOME/.mpv/mpv.conf` or `$MPV_HOME`, on recent builds.

One can simply place in the config file:
```bash
# mpv config
# here i use /usr/bin/yt-dlp as replacement
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
```
or run `mpv --script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp` directly in the command line.

placing in the config file will ensure mpv runs with that binary, even when using `ytfzf`.

**Comment by uestueab** [comment]
> script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

I have that exact line in my config. When i run the script i tells me "youtube-dl not found. Please install it."

**Comment by leoperegrino** [comment]
@uestueab what is the output of `which yt-dlp` in your system?

**Comment by novoid** [comment]
@leoperegrino I'm afraid, when I do `ytfzf -d`, search for a video and confirm with return, ytfzf still uses youtube-dl althought I do have following mpv.conf:

```
user@host ~ % cat .config/mpv/mpv.conf 
osd-bar-align-y=1
osd-duration=2000

# here i use /usr/bin/yt-dlp as replacement: https://github.com/pystardust/ytfzf/issues/428#issuecomment-987519184
script-opts=ytdl_hook-ytdl_path=/usr/local/bin/yt-dlp
user@host ~ % 
```

**Comment by leoperegrino** [comment]
@novoid 
Yes, I tried with the `-d` option and it still uses `youtube-dl` instead of `yt-dlp`. That actually makes sense because `ytfzf` hardcoded `youtube-dl`,  and it's `-d` flag downloads directly instead of using `mpv`, therefore your `mpv.conf` will be useless.
As cited in previous issues you could uninstall `youtube-dl` and symlink `yt-dlp` to it with `sudo ln $(which yt-dlp) /usr/local/bin/youtube-dl`.

If you don't want to make system wide changes, there is also the possibility of command substitution within your shell with the `-L` flag:
`yt-dlp $(ytfzf -L 'text to search for')`

**Comment by novoid** [comment]
Thanks @leoperegrino ,

That trick does solve many of my issues.

While this is still a workaround and not addressing the original feature request above, I may now close the issue. If ytfzf is offering a future simple-to-use configuration option in addition, some will hopefully link this to that request here.

Have a nice day!

**Comment by leoperegrino** [comment]
@novoid 
You can also consider creating a shell function to automate this process, such as:
```bash
function ydl() {
    # invoke with search string as argument
    # ydl some search string
    yt-dlp $(ytfzf -L "${@}")
}
```

**Comment by novoid** [comment]
Actually, my setup is even more complicated:

Shell script: `yd` (short for youtube download)
```
#!/bin/sh

URL="${1}"
FORMAT="${2}"

if [ -f "/usr/local/bin/yt-dlp" ]; then
    YDBIN="/usr/local/bin/yt-dlp"
    Y_QUERY_OPTIONS="--no-check-certificate --compat-options list-formats -F"
    Y_DL_OPTIONS="--write-info-json --no-check-certificate -f"

elif [ -f "/usr/bin/youtube-dl" ]; then
    YDBIN="/usr/bin/youtube-dl"
elif [ -f "/usr/local/bin/youtube-dl" ]; then
    YDBIN="/usr/local/bin/youtube-dl"
else
    echo "no youtube downloader tool found."
    exit 1
fi

if [ "${YDBIN}" = "/usr/bin/youtube-dl" ] || [ "${YDBIN}" = "/usr/local/bin/youtube-dl" ]; then
    Y_QUERY_OPTIONS="--no-check-certificate -F"
    Y_DL_OPTIONS="--write-info-json --no-check-certificate -f"
fi

if [ -z ${FORMAT} ]; then
    "${YDBIN}" ${Y_QUERY_OPTIONS}  "${URL}" | grep -v only
    echo
    read -p 'Please enter the desired version to download: ' FORMAT
    echo
fi

"${YDBIN}" ${Y_DL_OPTIONS} ${FORMAT} "${URL}"

~/src/misc/guess-filename-for-info-json-mp4-files.sh

#end
```

I can go into details on `~/src/misc/guess-filename-for-info-json-mp4-files.sh` if somebody is interested. Basically, it generates file names like `2021-08-31 youtube - Community Conversations | Staking & Neurons - xVNSxFFAYUo.mp4` which I prefer.

Then I do have `ydl` (short for youtube download low resolution)
```
#!/bin/sh

yd "${1}" 18

#end
```

Then I do have `ydh` (short for youtube download high resolution)
```
#!/bin/sh

yd "${1}" 22

#end
```

Now I do have `yth` (short for youtube browsing high resolution) thanks to your trick:
```
#!/bin/sh

yd $(ytfzf -L "${1}") 22

#end
```

(`ytl` accordingly)

As you can see, I prefer downloading all YT files and watching from local disk instead of streaming.

HTH
