### ISSUE TITLE
Support for captions

### ISSUE THREAD

**Issue by the-anonymous-raven** [pystardust/ytfzf#43]
Liked your project very much.
Can you add caption feature ?

**Comment by pystardust** [comment]
captions are already being provided by youtube-dl
press `j` and `J` while the video is playing to cycle between different captions. Captions will be displayed if they exist for the video.

**Comment by westofer** [comment]
README.md needs work, expect it by tomorrow btw

**Comment by pystardust** [comment]
@westofer thanks, redesign it how everyou like.
Im currently busy due to exams.

**Comment by the-anonymous-raven** [comment]
I meant captions while viewing videos. 
By default your script does not load captions and hence, can't be cycled.
You can use captions in mpv using 'mpv --sub-create-cc-track=yes link'.
Perhaps you can add a feature in your program to enable it.
Cheers!

> captions are already being provided by youtube-dl
> press `j` or `J` while the video is playing to cycle between different captions. Captions will be displayed if they exist for the video.
