### ISSUE TITLE
Suggestion, when we play a video from history it starts from where we left off

### ISSUE THREAD

**Issue by VG08** [pystardust/ytfzf#433]

**Comment by Euro20179** [comment]
I would look into doing something like [this](https://unix.stackexchange.com/questions/414639/is-it-possible-to-continue-movies-from-where-one-leaves-in-mpv-as-can-be-done-in)

```sh
echo "save-position-on-quit" >> ~/.config/mpv/mpv.conf
```

**Comment by VG08** [comment]
but will doing it in the mpv config also have the effect on videos played ytfzf?

**Comment by Euro20179** [comment]
ytfzf uses mpv to play videos, so yes.

**Comment by VG08** [comment]
Oh i thought mpv might treat the videos as different videos because they aren't downloding

**Comment by Euro20179** [comment]
Actually I didn't think about that, let me know if it works though.

**Comment by Euro20179** [comment]
Tested it myself (cause i forgot about this issue), and it works.
