### ISSUE TITLE
whats wrong with my conf.sh? 

### ISSUE THREAD

**Issue by onlyvip** [pystardust/ytfzf#439]
heres the error ![error](https://i.imgur.com/9fmrjuX.png) i get, heres my [conf.sh](https://ezup.dev/p/mey6wp). ytfzf version is 
![image](https://user-images.githubusercontent.com/76858994/147811908-c35b31e9-3d76-4f58-a21c-82bf1547528c.png)

**Comment by ionenwks** [comment]
```
$show_thumbnails=1
```
`$name` with `$` is used to expand the variable, if you want to set a variable in shell it's done as:
```shell
show_thumbnails=1
```
So what happened here is that it tried to expand a variable that's currently unset (resulting in nothing), then tried to run `=1` as a command.

That aside, for someone used to shell, that the ytfzf(5) man page is showing `$name` may look natural but maybe it'll be confusing to others that try to copy/paste it?

**Comment by onlyvip** [comment]
> ```
> $show_thumbnails=1
> ```
> 
> `$name` with `$` is used to expand the variable, if you want to set a variable in shell it's done as:
> 
> ```shell
> show_thumbnails=1
> ```
> 
> So what happened here is that it tried to expand a variable that's currently unset (resulting in nothing), then tried to run `=1` as a command.
> 
> That aside, for someone used to shell, that the ytfzf(5) man page is showing `$name` may look natural but maybe it'll be confusing to others that try to copy/paste it?

Yeah a definite mention of $ should be enough for a noob like me and majority of others
