### ISSUE TITLE
Scrap more than two videos per channel with subscriptions.

### ISSUE THREAD

**Issue by 123jimenez99** [pystardust/ytfzf#440]
Hello everyone and happy new year. Today I updated ytfzf and to my surprise it seems that a few things have changed. I just have one problem tho. Before the change I could see the last three videos of each channel where I'm subscribed to by doing "ytfzf --subs = 3". I have read the documentation a bit and now I have to do "ytfzf -c S" but with it I only lists two videos per channel. Is there an equivalent to "ytfzf --subs = 3" with the new option syntax? Thanks in advance!

Sorry for my broken english lol :P

**Comment by Euro20179** [comment]
Happy new year!
You have 3 options to scrape more than 1 video, either run this command
`sub_link_count=3 ytfzf -c S` or add `sub_link_count=3` to your config (change 3 to whatever)

you could also add this to your config, and this will return the `ytfzf --subs=` functionality

```sh
on_opt_parse () {
    option="$1"
    argument="$2"
    case "$option" in
        subs)
            #uncomment the line below to make --subs also enable the -c S scraper.
            #scrape="S"
            sub_link_count="$argument"
            return 1;;
    esac
 
}
```

Also, your English is just fine lol.

**Comment by 123jimenez99** [comment]
Yay! Now it works. Thank you very much!
