### ISSUE TITLE
Makefile: add installation of conf.sh

### ISSUE THREAD

**Issue by Vouivre** [pystardust/ytfzf#446]
After installing `ytfzf`I wanted to use my own external menu. It's only after reading the file `conf.sh` that I was
able to customize the menu. But I had to look in the github repo, I find it would be convenient to also add a configuration example in the release. I would like to add it for the kisslinux package. 

As a package maintainer, I can simply copy the file. But the man pages and the script is installed with the Makefile, so it would be better to also install it with the Makefile.

I can do some proposal and a PR.

What do you think about it ?

**Comment by Euro20179** [comment]
I think it should go in `/etc/ytfzf/conf.sh` if we install it with the make file, cause we don't want to override the user conf.sh, however my goal is to make it so that `conf.sh` is unnecessary and, whatever you are looking for should be in `ytfzf(5)`

**Comment by Vouivre** [comment]
After reading again `ytfzf(5)`, yes it's explained, but I know now what is expected. Normally in a configure file I don't define some functions, So I have tried the following for example:

    external_menu=bemenu

Of course, it makes no sense and doesn't work, but with an example I would have understood immediately that I need to define a shell function. 

`conf.sh` is in `docs`, so why could we not install it in `/usr/share/doc/ytfzf/conf.sh` for example ? I understand it as a documentation file that you can use or not. I use for example `mpv` which provides a configuration file in `/usr/share/doc/`. In the past I have also used `sxhkd` which also provides an example. 

I don't know if the other users don't need an example and the man pages are enough.

**Comment by Euro20179** [comment]
> Of course, it makes no sense and doesn't work, but with an example I would have understood immediately that I need to define a shell function.

Fair enough.

`/usr/share/doc/ytfzf/conf.sh` is good, it might also be a good idea to mention `conf.sh` in `ytfzf(5)` as an example. (If you don't know how to write man pages I can do it.)

**Comment by Euro20179** [comment]
I think we put it in `/usr/share/doc/ytfzf/conf.sh` and mention it (maybe near the top i'm not sure) of `ytfzf(5)`, that way they mention each other. I think it'll be more organized to do it that way, plus I want to do the 2 things mentioned below.

While we're at it we should also put the LICENSE in `/usr/share/licenses/ytfzf/LICENSE`, and the README in `/usr/share/doc/ytfzf/README.md` for completeness.

**Comment by Vouivre** [comment]
So before I do a PR, I take the following source as a guideline:

https://www.gnu.org/software/make/manual/html_node/Directory-Variables.html

1. At the moment we have the following in the Makefile:

```
man:
	mkdir -p ${DESTDIR}${MANDIR}/man1
	mkdir -p ${DESTDIR}${MANDIR}/man5
	install docs/man/ytfzf.1 ${DESTDIR}${MANDIR}/man1
	install docs/man/ytfzf.5 ${DESTDIR}${MANDIR}/man5
```

If we install something in `/usr/share/doc`it's not related to the rule `man`. So I would create a new rule named `doc` to install the files related to doc: `conf.sh`, `README`, `LICENSE`. Probably it's not bad to use the same rule to install `LICENSE`. Or we rename the rule `man` to `doc` and that rule install the man pages and the doc related files. The user has less flexibility, but in some packages some files are deleted with `rm`, so the user can choose what he can install. For the following I will assume we have only one rule named `doc`. Just tell me if you want two rules (`doc` and `man`). 

2. If I understand right, to use the standard, we should write something like

```
PROG=ytfzf
PREFIX=/usr/local
DATAROOTDIR=${PREFIX}/share
BINDIR=${PREFIX}/bin
MANDIR=${DATAROOTDIR}/man
DOCDIR=${DATAROOTDIR}/doc/ytfzf

doc:
	mkdir -p ${DESTDIR}${MANDIR}/man1
	mkdir -p ${DESTDIR}${MANDIR}/man5
	mkdir -p ${DOCDIR}
        install docs/man/ytfzf.1 ${DESTDIR}${MANDIR}/man1
	install docs/man/ytfzf.5 ${DESTDIR}${MANDIR}/man5
        install docs/conf.sh ${DESTDIR}${DOCDIR}
        install LICENSE ${DESTDIR}${DOCDIR}
        install README ${DESTIDR}${DOCDIR}

install:
	chmod 755 ${PROG}
	mkdir -p ${DESTDIR}${BINDIR}
	install ${PROG} ${DESTDIR}${BINDIR}/${PROG}

uninstall:
	rm -f ${DESTDIR}${MANDIR}/man1/ytfzf.1
	rm -f ${DESTDIR}${MANDIR}/man1/ytfzf.5
	rm -f ${DESTDIR}${BINDIR}/${PROG}
        rm -f ${DESTRID}${DOCDIR}

.PHONY: install uninstall man
```

I have to test, but probably we can change

```
        install docs/conf.sh ${DESTDIR}${DOCDIR}
        install LICENSE ${DESTDIR}${DOCDIR}
        install README ${DESTIDR}${DOCDIR}
```

to 

    install docs/conf.sh LICENSE README ${DESTDIR}${DOCDIR}

3. In don't understand the difference between `DATAROOTDIR` and `DATADIR` in the standard (often they are the same). We could simply define a new variable `DOCDIR`:

```
PROG=ytfzf
PREFIX=/usr/local
BINDIR=${PREFIX}/bin
MANDIR=${PREFIX}/share/man
DOCDIR=${PREFIX}/share/doc/ytfzf
```

and adapt the rest. 

What is your favorite ? I would rename the rule `man` to `doc` and define only a new variable `DOCDIR`.

**Comment by Euro20179** [comment]
>What is your favorite ? I would rename the rule `man` to `doc` and define only a new variable `DOCDIR`.

I agree that we should rename `man` to `doc`.

**Comment by Vouivre** [comment]
I have tested the modifications: are you sure you want to include the `README` ? It's in markdown format. Usually it's a `txt` file. The markdown file is not the best format to be read in a terminal.

**Comment by Euro20179** [comment]
> The markdown file is not the best format to be read in a terminal.

fair enough, we don't need it.

**Comment by Vouivre** [comment]
PR ready to review.
