### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by d1nuc0m** [pystardust/ytfzf#448]
I've found another difference between 1.x and 2.x branches, when trying to start a new search: alt shortcuts ( if I didn't make mistakes in reading the scripts)

**1.x**
| Shortcut | Action |
| --- | --- |
|alt-l | urls/print links| 
|alt-t | title | 
|alt-o| open browser |
|alt-v| watch video |
|alt-d| download |
|alt-m| audio |
|alt-s|search|
|alt-enter|detach|

**2.x**
| Shortcut | Action |
| --- | --- |
|alt-l | urls/print links|
|alt-v| watch video |
|alt-d| download |
|alt-m| audio |
|alt-e|detach|
|alt-f|show formats|

**Diff**
| Version | urls | title | browser | video | download | audio | search | detach | formats |
| --- | --- |  --- |  --- | --- | --- | --- | --- | --- | --- |
| 1.x | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | 
| 2.x | :heavy_check_mark: | :x: | :x: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :x: | :heavy_check_mark: |:heavy_check_mark: |

As this is obviously due to some features not being available, will these be implemented in the future? I really appreciate the refactoring with Invidious, that also allows for way more results, but I also miss the search shortcut XD

**Comment by Euro20179** [comment]
The search shortcut was not there, cause I didn't implement `-s`, I will add it.
Browser shortcut is too niche, if you want it back you can add this to `~/.config/ytfzf/conf.sh`

```sh
custom_shortcut_binds="alt-b"

open_with_browser () {
    $BROWSER "$@"
}

handle_cutom_keypresses () {
    keypress="$1"
    case "$keypress" in
        alt-b) url_handler=open_with_browser ;;
    esac
}
```

As for the title, I'm not going to add *specifically* title, instead i'll add the equivalent of (probably) `-I VJ`, that way you can get anything from it.

**Comment by Euro20179** [comment]
>  they work but using alt+i outputs the information and exits from the script, is this the expected behavior?

Yes because `ytfzf -I VJ ...` does the same thing (with -l and -s disabled)

**Comment by d1nuc0m** [comment]
> > they work but using alt+i outputs the information and exits from the script, is this the expected behavior?
> 
> Yes because `ytfzf -I VJ ...` does the same thing (with -l and -s disabled)

Perfect, thanks, I think we can close this issue then
