### ISSUE TITLE
Preview does not work in Endeveavor OS

### ISSUE THREAD

**Issue by pannet1** [pystardust/ytfzf#453]
I am trying to get the thumbnails work in my Qtile, Xonsh, Kitty combo. When i run
`ytfzf -t --thumb-viewer=kitty`
the terminal is vertically split and a new kitty terminal is  opened but no preview. when i exit the new terminal, i get the list of videos pictured below but with lot of errors on the left.

[thumb-view](https://i.imgur.com/uEdMJW4.jpg)
any idea why this occurs.

**Comment by Euro20179** [comment]
`xonsh` is not a posix compliant shell, try using `bash` or smth to run it

(theres another bug related to kitty where the image appeara on the wrong side that you might run into)

**Comment by yoogui** [comment]
Same here with another Endeavour OS flavour, bspwm Community Edition.
If I rename the .Xauthority file to .Xauthority.bak breaks one Polybar section and still thumbnails doesn't work at all

**Comment by Euro20179** [comment]
what is the output of `ls -l /bin/sh`, are you using the kitty terminal?
you could try `bash ytfzf ...`

**Comment by yoogui** [comment]
For me is solved, sorry, was my fault. I'm noob on Linux

**Comment by shakakibara12** [comment]
hey you don't have to be sorry!
