### ISSUE TITLE
Kitty thumbnail appears on the wrong side

### ISSUE THREAD

**Issue by Euro20179** [pystardust/ytfzf#454]
Sometimes when using `--thumb-viewer=kitty` the thumbnail appears on the wrong side (only happens with `--preview-side={right,left}`).
This only seems to happen when my terminal is maximized or in full screen.

To reproduce:
1. open terminal in fullscreen
2. `ytfzf --thumb-viewer=kitty --preview-side=left hi`
3. scroll (it happens more often if you scroll quickly)

Example:
![image](https://user-images.githubusercontent.com/56898436/148566249-4f5ba137-f38b-4bc8-917a-cae33997f53f.png)

**Comment by ionenwks** [comment]
I think it's some kind of race condition with the clear command not having finished, personally I don't get this unless my CPU is under heavy load, which is what makes me think race -- and fullscreen may increase the CPU requirement impact.

Optimally it'd be nice to just remove --clear (removes the annoying blanking), but unless all thumbnail have the same aspect ratio (e.g. odysee not so good with this), it causes images to badly overlap (also wouldn't clear if there's no thumbnail, but that could be done only when the thumbnail file is missing).

Unsure for a good way to handle this.

**Comment by Euro20179** [comment]
> Optimally it'd be nice to just remove --clear (removes the annoying blanking),

Got rid of the clear and...
![image](https://user-images.githubusercontent.com/56898436/149434599-383840c0-a449-4f83-9f1a-e76f2b449013.png)
so yeah no (also my test search is `hi` if you're wondering about the thumbnails lol)

> but unless all thumbnail have the same aspect ratio (e.g. odysee not so good with this),

again without the clear command, but this time on odysee
![image](https://user-images.githubusercontent.com/56898436/149434707-afc4f86f-a3ac-462e-9ff1-42514830af8d.png)


But I just removed kitty for now, and i'm feature freezing 2.1, cause i'd like to make sure it works. But if we can get it working i'd like to add it.

**Comment by ionenwks** [comment]
I see, was starting to think could convert the images so it works without clear, but if still happens with --clear I guess it's no good.

Originally I was also trying other image viewers with kitty support but they break under fzf or force-fallback to using blocks.

Guess I'll keep it locally for myself until find a better option then (this is more a rare annoyance than something I get frequently, originally I didn't notice it happened at all).

**Comment by Euro20179** [comment]
> Guess I'll keep it locally for myself until find a better option then (this is more a rare annoyance than something I get frequently, originally I didn't notice it happened at all).

Do you have a gpu, if so is it like good? I have a pretty basic amd gpu, i notice this bug CONSTANTLY. It could possibly be a hardware thing cause kitty is gpu accelerated.

**Comment by ionenwks** [comment]
> Do you have a gpu, if so is it like good? I have a pretty basic amd gpu, i notice this bug CONSTANTLY. It could possibly be a hardware thing cause kitty is gpu accelerated.

While it is gpu accelerated, but pretty sure this bit is cpu related. I notice this when my cpu is under load, e.g. compiling things. But I'm using a nvidia 1070 and a i7-8700

Anyhow, if it's going to get this messy on some hardware it makes sense to remove it for now.

**Comment by Euro20179** [comment]
> While it is gpu accelerated, but pretty sure this bit is cpu related. I notice this when my cpu is under load, e.g. compiling things. But I'm using a nvidia 1070 and a i7-8700

Fair enough.

**Comment by Euro20179** [comment]
> Guess I'll keep it locally for myself until find a better option then (this is more a rare annoyance than something I get frequently, originally I didn't notice it happened at all).

This made me realize that custom thumbnail viewers are useless cause they are given no information, but i fixed it in the commit i pushed like a minute ago

```sh
#!/bin/bash
[ "$1" = "view" ] && {
    command -v "kitty" &> /dev/null  || die 3 "\nkitty is not installed\n"
    kitty +kitten icat --clear --transfer-mode stream
    kitty +kitten icat --place "${5}x${6}@${3}x${4}" --scale-up --transfer-mode stream "$2" 
}
```

if you put that in `~/.config/ytfzf/thumbnail-viewers/kitty-viewer` you can then use `ytfzf --thumb-viewer=kitty` without having to have a custom patch of ytfzf.

**Comment by Euro20179** [comment]
changed it to `--transfer-mode file`, still broken. (maybe less? but this could easily be placebo)

**Comment by ionenwks** [comment]
> changed it to `--transfer-mode file`, still broken. (maybe less? but this could easily be placebo)

I see, oh well. Out of ideas right now.

Thanks for the custom viewer changes, tried it just now and it works, I'll use it to be spared from patching until find a way to solve this.

**Comment by engjpacheco** [comment]
# Same but with st. Any suggestion?

**Comment by Euro20179** [comment]
How did you even get kitty images to work in st,
Other than that no i don't have suggestions because it seems to be a hardware issue.

**Comment by engjpacheco** [comment]
Well, naybe I choose the wrong issue, I use st and have the thumbnails in other position

**Comment by Euro20179** [comment]
> Well, naybe I choose the wrong issue, I use st and have the thumbnails in other position

Open a new issue, and provide more details, 
* what thumbnail viewer are you using (if you don't know then probably ueberzug)

**Comment by engjpacheco** [comment]
Allright thanks.

**Comment by Euro20179** [comment]
I'm closing this in favor of making `kitty` an addon
