### ISSUE TITLE
[Feature request] Option to sort a certain number of videos exclusively by upload date?

### ISSUE THREAD

**Issue by jaredreardon** [pystardust/ytfzf#455]
I'm aware of the --sort flag, which is what I'm using now, but was wondering if there was any plans to add a feature that would allow a user to only display a certain number of videos, and sort them by upload date, regardless of who the subscription is. 

So for example, in this hypothetical flag if you were to set it to display the last 100 videos, it would show the last 100 videos of your subscriptions regardless of how frequently or infrequently a subscription uploaded. I.e. a certain channel could show up 50 times in this list or not show up at all depending on upload frequency, as opposed to the current --sort flag, which sorts by upload date but also displays at least 2 videos per subscription, regardless of whether they were uploaded way in the past.

**Comment by Euro20179** [comment]
Although this is a good idea, I dont think that its technically possible to implement.

if this flag were to be added as described wed have to scrape every video from every subscription wich would take forever.

**Comment by jaredreardon** [comment]
> Although this is a good idea, I dont think that its technically possible to implement.
> 
> if this flag were to be added as described wed have to scrape every video from every subscription wich would take forever.

I understand that! Thanks for considering it, though. If there isn't anything to do here, you can feel free to close this request!
