### ISSUE TITLE
No notification options

### ISSUE THREAD

**Issue by leoperegrino** [pystardust/ytfzf#456]
I've recently changed to ytfzf 2.0 and was not able to disable notifications. I've scrapped the source but it does not seem to be a direct flag to disable, only `is_ext_menu` function to short-circuit `notify_info` function, but this messes with others functionalities.
Is there a way to disable `notify-send "Ytfzf Info" $@`?

**Comment by Euro20179** [comment]
in your config file you can put `notify_playing=0` or you can run `ytfzf --notify-playing=0 ...`

**Comment by yoogui** [comment]
Hi @Euro20179 
Congrats for your job and this awesome program. In my case, I installed from AUR. Where I do search for my config file??

Thanks again.

**Comment by Euro20179** [comment]
The aur version seems to have been updated, but just to make sure, run `ytfzf --version` and make sure you're on 2.x.
The config file is in the same place either way, however the solution to this issue only works in 2.x

The config file isn't created by deafult so, you'll have to make a folder in `~/.config` called `ytfzf`, then in that folder create a file called `conf.sh`
this command will do that:
`mkdir ~/.config/ytfzf; touch ~/.config/ytfzf/conf.sh`

**Comment by yoogui** [comment]
Thank you so much!

**Comment by leoperegrino** [comment]
> in your config file you can put `notify_playing=0` or you can run `ytfzf --notify-playing=0 ...`
> 
> If it doesn't work you might have to update by doing this
> 
> ```shell
> git clone https://github.com/pystardust/ytfzf
> cd ytfzf
> #if onlinux run the command below
> sudo make uninstall-old
> #run this even if not on linux
> sudo make install doc
> ```

Yeah, AUR's PKGBUILD uses release 2.0, which does not have `notify_playing` variable, altough master branch has it. Guess I will clone and `make` it.
