### ISSUE TITLE
Play selected audio/video hotkey chaos

### ISSUE THREAD

**Issue by p1839251** [pystardust/ytfzf#460]
Hello,
Something isn't right with these two hotkeys. https://github.com/pystardust/ytfzf/pull/288#issue-924138616
I sometimes run `ytfzf` without `-m` and later I change my mind and want only music, and sometimes I want the opposite.

Here's the issue:
```
$ytfzf ytfzf
Scraping Youtube...
Downloading Thumbnails...
Opening Player: mpv --ytdl-format=22/18 https://www.youtube.com/watch?v=Ml55xp--ahA
```

**Alt+m**
`Opening Player: mpv --no-video https://www.youtube.com/watch?v=Ml55xp--ahA`

So far so good. However, It was unexpected that the change remained permanent.

The next time I hit enter on the same title, I got again:
`Opening Player: mpv --no-video https://www.youtube.com/watch?v=Ml55xp--ahA`

And here comes the tricky part. I want to watch the video again, I hit **Alt+v** on the very same title and that's what I see
`Opening Player: mpv --ytdl-format=bestaudio https://www.youtube.com/watch?v=Ml55xp--ahA`
I can't watch the video anymore.

I think **Alt+v** and **Alt+m** should be a just temporary switch.
( I also think that **Alt+l** (link) and **Alt+t** (title), shouldn't quit the program.
It should just wait for a user input to return to the main screen, so they could be copy/pasted. I guess that's what they are for
Probably **Alt+o** is also affected, but I haven't tested it yet)

**Comment by Euro20179** [comment]
> I think Alt+v and Alt+m should be a just temporary switch.

I agree, but I've not been able to add this in a clean way.

> ( I also think that Alt+l (link) and Alt+t (title), shouldn't quit the program.

I wanted it to match the functionality of `-L` and `-IVJ` respectively.
However your idea of waiting for user input is a good idea, and i'll look into it.

**Comment by p1839251** [comment]
Thank you Euro20179 :)

Could you reproduce the `--ytdl-format=bestaudio` issue? I have no idea why it does that :S

**Comment by Euro20179** [comment]
> Could you reproduce the `--ytdl-format=bestaudio` issue? I have no idea why it does that :S

It's probably because bestaudio is an audio only format, if you want video you need to do something like `--ytdl-format=bestvideo+bestaudio`

**Comment by p1839251** [comment]
I think we misunderstand each other.
I didn't type those commands, `ytfzf` did.

Run `ytfzf` either with `-m` or without it.
Start the first video. 
`mpv --ytdl-format=22/18 link`. Close the video.
Choose the opposite option. In my case it's `Alt+m` now
Now I see `mpv --no-video link`, which is still good. Close the video again.
I want video now, so `Alt+v` on the video:
`mpv --ytdl-format=bestaudio link`
And there's no video playback anymore. I have to quit the program and start again so I could see it.

**Comment by Euro20179** [comment]
> I think we misunderstand each other.
> I didn't type those commands, ytfzf did.

Ah, yes you're right, sorry.

I believe this is just an issue with how 1.x handles `-m` and shorcuts, try updating ytfzf

```sh
git clone https://github.com/pystardust/ytfzf
cd ytfzf
sudo make uninstall-old #run this only if on linux
sudo make install doc
```

**Comment by p1839251** [comment]
Oh, it's my fault for not noticing that a newer version came out, which is working perfectly.
Thank you!

**Comment by Euro20179** [comment]
> Oh, it's my fault for not noticing that a newer version came out

All good, there's not really any announcements when a new update comes out, you kinda just have to check.
