### ISSUE TITLE
Choosing formats for live streams is broken

### ISSUE THREAD

**Issue by kickerofelves** [pystardust/ytfzf#465]
Looks like formatting is hardcoded to be "%s+bestaudio/best".  However, it seems if there is no separate audio stream (e.g. live streams)  "bestaudio" fails and "best" is always chosen.

**Comment by Euro20179** [comment]
> Looks like formatting is hardcoded to be "%s+bestaudio/best"

>  However, it seems if there is no separate audio stream (e.g. live streams) "bestaudio" fails and "best" is always chosen.

Interesting, I basically did this as a shortcut, this may force me to seperate `video_pref` and `audio_pref` into 2 different variables (which is probably a good idea anyway).

**Comment by kickerofelves** [comment]
None of the live streams I looked at had separate audio streams. [This for example](https://www.youtube.com/watch?v=SkfsQ3Ki4es).

**Comment by Euro20179** [comment]
```diff
diff --git a/ytfzf b/ytfzf
index 386f205..aac9598 100755
--- a/ytfzf
+++ b/ytfzf
@@ -1268,7 +1268,8 @@ get_video_format(){
        case 1 in
                $is_audio_only) ${ytdl_path} -F "$1" | sed -n '4,$p' | grep 'audio only' | quick_menu_wrapper "Audio format: " | awk '{print $1}' ;;
                1)
-                       printf "%s+bestaudio/best" "$(${ytdl_path} -F "$1" | sed -n '4,$p' | grep -v 'audio only' | quick_menu_wrapper "Video Format: "| awk '{print $1}')" ;;
+                       fmt=$(${ytdl_path} -F "$1" | sed -n '4,$p' | grep -v 'audio only' | quick_menu_wrapper "Video Format: "| awk '{print $1}')
+                       printf "%s+bestaudio/%s" "$fmt" "$fmt" ;;
        esac
 }
 ```

seems it can be fixed by making it "%s+bestaudio/%s"

**Comment by kickerofelves** [comment]
That works! Thanks for the quick fix and the project. I'm going to incorporated it into one of my own.

**Comment by Euro20179** [comment]
> That works!

Great, i'll merge it into master then!

**Comment by kkatz151** [comment]
Thank you
