### ISSUE TITLE
Thumbnails not in the position that should be in ST(simple terminal) 

### ISSUE THREAD

**Issue by engjpacheco** [pystardust/ytfzf#466]
The thumbnails apperas upper the rectangle of preview overlapping the text, and a bit smallers. I use the image preview ueberzug.
Other functionalities works just fine.

Thanks.

**Comment by Euro20179** [comment]
> The thumbnails apperas upper the rectangle of preview overlapping the text,

Show a screenshot?
however a lot of the time the image will overlap the description if it is long. I've tried fixing this by auto shifting the thumbnail down when the thumbnail is long, but this causes bugs.

**Comment by engjpacheco** [comment]
Maybe is normal as you say, let me upload a screenshoot later, cus' im on work.

**Comment by engjpacheco** [comment]
![pic-selected-220117-1732-48](https://user-images.githubusercontent.com/77270456/149848284-eae1f49f-fd19-4f8d-8fe5-c186eccfc80f.png)
it seems that thumbnails dont appear, but is weird because last week or so works fine, just the position that I mentioned in the issue.

**Comment by Euro20179** [comment]
> it seems that thumbnails dont appear

try `killal ueberzug`, and `killall ytfzf`
try deleting `~/.Xauthority` and restarting Xorg.

**Comment by engjpacheco** [comment]
Try it but same result,

**Comment by engjpacheco** [comment]
![Screenshot_20220118-083328_Telegram.jpg](https://user-images.githubusercontent.com/77270456/149957581-c1022f6b-7dc6-4b80-8dda-c527faa45bed.jpg)
Here is another picture that proof that thumbnails works but overlapping the text, but since yesterday that I check ytfzf now the thumnbnails disapears

**Comment by Euro20179** [comment]
I think it has to do with the fact that the preview doesn't take up the full height of the screen, do you have any fzf opts set that would make it do that?

**Comment by engjpacheco** [comment]
Noup, i inky download the repo and install as the readme says. Ex ytfzf -t <example>

And i didn't  update ytfzf.

**Comment by Euro20179** [comment]
You could try `bash ytfzf ...`
You could also try updating ytfzf but i doubt that'll fix anything

```sh
git clone https://github.com/pystardust/ytfzf
cd ytfzf
sudo make uninstall-old
sudo make install doc
```

**Comment by engjpacheco** [comment]
Allright gonna check that out, thanks for the quick response this project is awesome btw.

Regards.

**Comment by engjpacheco** [comment]
Hi, just try unimstall it and reinstalling and adding the patch but no good results, im going to figure it out, maybe is something wrong with my st, but is weird  because it used to works
![20220119_093712.jpg](https://user-images.githubusercontent.com/77270456/150163888-7ad0e924-cbf8-434d-b2ed-9df6d968ce0d.jpg)

**Comment by Euro20179** [comment]
> Hi, just try unimstall it and reinstalling and adding the patch but no good results, im going to figure it out, maybe is something wrong with my st, but is weird because it used to works

Although the thumbnails aren't showing, they should be in the right position now (which is what i was trying to fix)

> but is weird because it used to works

Ueberzug is very funky.

### Ideas
* using a different terminal, like kitty (kitty seems to just work with everything 
* `rm -r ~/.cache/ytfzf` (if you're ok with removing search and watch history)
* `killall ueberzug`
* Try using a different window manager (ik this is a lot of effort, and it probably won't even work)
* if you installed ueberzug with `sudo pip` maybe try uninstalling that in instsalling it without `sudo`, if you installed it without `sudo`, try installing it with `sudo`.

**Comment by engjpacheco** [comment]
Allright thank you, I install ueberzug without sudo so its ok i guess, I also try it in xmonad same result, maybe is something with ueberzug, i dont know maybe in a few days or so is gonna be working i guess, thank you  again.

**Comment by shervinsahba** [comment]
My thumbnails would clip the preview text when my default `FZF_DEFAULT_OPTS` setting included `--height=80%`. Increasing the height to the full terminal prevented clipping.

**Comment by engjpacheco** [comment]
I remember see that env variable in my zprofile, im gonna check that out but i dont know why thumbnails  dont appear since las month or so, thanks for the tip.

**Comment by engjpacheco** [comment]
Ok, im gonna downgrade an try ( i use st) if not i can live without thumbnails i guess.. thanku

**Comment by Euro20179** [comment]
> if not i can live without thumbnails i guess.. thanku

you could use [imv](https://git.sr.ht/~exec64/imv), it's a seperate window, but at least it's thumbnails.
You'll probably be able to install it w/ package manager

**Comment by shervinsahba** [comment]
> That variable is no longer used in ytfzf, since 2.0, but in the 2.2 beta versions there is a `--fzf-opts` option though.

Interesting. My FZF_DEFAULT_OPTS seems to be respected by ytfzf (version 2.1.rc-4) on my system. I'm only calling `ytfzf -t --thumb-viewer=<option> <search terms>`. The menu that opens has all my fzf styles intact.

The thumbnail seems to be placed with respect to the terminal size and not the fzf "window", which is why the height change back to 100% worked for me. The kitty-viewer script is nice by the way. It let me get rid of my ueberzug dependency. The same thumbnail placement issues occurred with both ueberzug and kitty for me, though.

Let me know if I can add more info. I'm happy with how it works though! Nice work.

**Comment by Euro20179** [comment]
> . My FZF_DEFAULT_OPTS seems to be respected by ytfzf (version 2.1.rc-4) on my system

Interesting. This means that fzf just uses this by default, and there is no need for `fzf_opts` or `fzf_thumbnail_opts`. I'll do some testing to be sure though.

> The thumbnail seems to be placed with respect to the terminal size and not the fzf "window", which is why the height change back to 100% worked for me.

fzf reports it's window size as 2 environment variables: `FZF_PREVIEW_COLUMNS` and `FZF_PREVIEW_LINES`, the placement is based on those 2 variables. 
If you want to see the placement "algorithm" (not really an algorithm), see lines `1298-1333`

**Comment by engjpacheco** [comment]
![20220305_161125.jpg](https://user-images.githubusercontent.com/77270456/156901444-ddeae40d-a3d0-4f9a-9b52-ab684b612e33.jpg)

Solved whit the patch with st propped patche too

**Comment by Euro20179** [comment]
nice!

**Comment by wesleyjrz** [comment]
![screenshot-20221224-194734](https://user-images.githubusercontent.com/60184588/209452687-505d2d83-6ea5-4b4f-99f1-6fb5c5f0a3a2.png)


![screenshot-20221224-195252](https://user-images.githubusercontent.com/60184588/209452795-1b7d0ce6-9fbb-48ba-ab86-8379bbd260ab.png)

I was facing the same problem with st, termite and tym. Then I set `FZF_DEFAULT_OPTS` to include `--height=100%` (It was set to 40% before) and it worked.
