### ISSUE TITLE
ALT+D don't download videos.

### ISSUE THREAD

**Issue by Casul51** [pystardust/ytfzf#467]
Instead of downloading videos ALT+D plays them.
Tested in git version and 2.0

**Comment by Euro20179** [comment]
What do you mean by git version?, you installed with make?
Do you have a config file?
what happens when you do `ytfzf -d ...`

**Comment by Casul51** [comment]
> What do you mean by git version
I'm on Arch, so I tried regular ytfzf and ytfzf-git from AUR, thou it's probably just downloads latest release.

> Do you have a config file?
No, I don't.

> what happens when you do ytfzf -d ...
It downloads selected video (as it expected).

**Comment by Euro20179** [comment]
`ytfzf` is outdated by a version, `v2.1` fixes the `alt-d` bug, `ytfzf-git` stopped existing a long time ago.
Try installing with make.

**Comment by Casul51** [comment]
Yep, everything works!
