### ISSUE TITLE
release ytfzf 2.1: wrong version displayed

### ISSUE THREAD

**Issue by Vouivre** [pystardust/ytfzf#471]
I wanted to package `ytfzf` 2.1 and when I checked the version, I got:

```
$ ytfzf --version
ytfzf: 2.1.rc-4 
```

You forgot to update `YTFZF_VERSION="2.1.rc-4" ` in your code.

**Comment by Euro20179** [comment]
Yes, I realize. I push everything to master branch so I cant really fix it. I could add a note to the update log. I could start using the dev branch again. Either eay next time ill be more careful.

Idk if this matters but, 2.1.rc-4 is exaxtly the same as 2.1.

**Comment by Vouivre** [comment]
I'll patch the version for the kisslinux package. For me you don't need to do something else.

The problem it's to avoid a lot of questions/issues. I mean as a user if I see something  doesn't work as expected and I notice it's a release candidate, not the final version, I could be tempted to do a bug report. When I switched to the 2.1 version, I didn't find how to use an external menu at first. I did some tries which where right..... in my mind ;-). If I see it's a release candidate, I could think: ok, I did it right, there is a bug ;-). 

There is an issue, so I wouldn't do much more. I let you decide if you want to add a note in the update log. 

I let you close this issue when you know if there is something to do. 

Thank you for your comment!

**Comment by Euro20179** [comment]
> I didn't find how to use an external menu at first. I did some tries which where right..... in my mind

How did you try using an external menu?

**Comment by Vouivre** [comment]
> How did you try using an external menu?

Before version 2.0, I had to set the variable `YTFZF_EXTMENU`. So in my mind I had to do something similar. 
So I tried to set 

    external_menu=bemenu

in my config file. Of course, after reading the `conf.sh` I understood that I really had to define a shell function `external_menu()`. It's the first time I have to customize a function in a config file, excepted for the shell. It's clearly written in the documentation, but for me it was so unexpected, I thought: "No, it should be the same as defining a variable".......

That's the reason why I wanted to include an example of the `conf.sh` in the installation. With it, I understood immediately how to use an external menu.

**Comment by Euro20179** [comment]
> in my config file. Of course, after reading the conf.sh I understood that I really had to define a shell function external_menu(). It's the first time I have to customize a function in a config file, excepted for the shell. It's clearly written in the documentation, but for me it was so unexpected, I thought: "No, it should be the same as defining a variable".......

Ah, right I think youve mentioned this before when we were redesigning the Makefile.

**Comment by Vouivre** [comment]
> Ah, right I think youve mentioned this before when we were redesigning the Makefile.

Exactly!
