### ISSUE TITLE
Empty line or title between youtube subscription results

### ISSUE THREAD

**Issue by cv1618** [pystardust/ytfzf#472]
I'm using ytfzf 2.1-1, I was wondering if there's something I can add to conf.sh that would make it so when I do a youtube subscriptions search {ytfzf -cS -t}there's an empty line between each channel in the results so it's easier to tell where each channel ends and begins. Or to have it display the title of the channel above each channel like it used to in Version 1.

**Comment by Euro20179** [comment]
> here's an empty line between each channel in the results so it's easier to tell where each channel ends and begins. Or to have it display the title of the channel above each channel like it used to in Version 1.

Not gonna to lie, I forgot about this feature, I'll try to re implement it in 2.2.

**Comment by Euro20179** [comment]
Has been commited in 2a3f1c9c91aebd459b61c1fa966a8e7b5462f97e
