### ISSUE TITLE
Thumbnails are not loading and also the video is not playing on EndeavourOs

### ISSUE THREAD

**Issue by AvAkanksh** [pystardust/ytfzf#474]
I am using Konsole as my terminal, and bash as my shell but yet the thumbnails are not being loaded and the video is not being played. So is there any reason why the thumbnails are not loading even though I have installed the ueberzug package for the thumbnails to be displayed.

Thank you in advance

**Comment by Euro20179** [comment]
what is the output of `ytfzf --version`, There have been some buggy versions I've pushed to master recently, if it's an alpha version you could try this:

```sh
git clone -b v2.1 https://github.com/pystardust/ytfzf
cd ytfzf
sudo make install doc
```

Are you on Wayland? Ueberzug doesn't work on Wayland. If you don't know, `echo $XDG_SESSION_TYPE` might tell you.
Either way you could use the `imv` thumbnail viewer, it's not as good but it's still a real image viewer.

try running `bash -x ytfzf -D <search>` then copy the output here.
Although thumbnails won't be tested with -D, it'll test why the videos aren't playing.

**Comment by yoogui** [comment]
Ok, in a fresh install of my system, now works.

Thanks a lot for your work

**Comment by Euro20179** [comment]
> Ok, in a fresh install of my system, now works.

I wonder why resinstalling your system fixed it. I feel like it has something to do with `ueberzug` caching but I can't even find cache files for it, so idk.
