### ISSUE TITLE
Limited search results 

### ISSUE THREAD

**Issue by alan5901** [pystardust/ytfzf#475]
I have recently installed ytfzf on Mint 20.3. Everything seems to be working just fine, however when I search for something it only returns 20 results. 

I have have run into this issue with other terminal biased YouTube programs such as mps-youtube and yewtube. I have tried switching form Konsole to xfce4-terminal and still run into the same issue. Iv'e also tried a number of searches but still only receive 20 results. 

I think that there should be a simple fix, but would appreciate any suggestions. Please let me know if I can provide any additional information

![image](https://user-images.githubusercontent.com/98901924/152198683-e30f1e11-1c58-4512-9059-2869926357d8.png)

**Comment by Euro20179** [comment]
> I search for something it only returns 20 results.

> I have have run into this issue with other terminal biased YouTube programs such as mps-youtube and yewtube.

This is not your fault, when scrping youtube, youtube only loads 20 results, long story short use `--pages=<amount>` to get around this

**Comment by Euro20179** [comment]
Actually, I could be mistaken, but you appear to be on a rather old version of `ytfzf`, if `ytfzf --version` says a version lower than 2.0, `--pages` wont work,

you can update with

```sh
git clone -b v2.1 https://github.com/pystardust/ytfzf
cd ytfzf
sudo make uninstall-old
sudo make install doc
```

**Comment by alan5901** [comment]
@Euro20179  Thanks so much for the quick reply!!

Using --pages=(amount) really seemed to help. Now instead of getting 20 results I get 500.

I am currently using ytfzf: 2.2.alpha-9, I installed it with git clone https://github.com/pystardust/ytfzf.

Also if I can pick your brain on one more thing, it seems like I might have a decoding issue. When the video is paused I get download speeds of over 2MB, however when I play the video the speed drops to around 300KB. Once again any help would be greatly appreciated.  

When video is paused: 
![image](https://user-images.githubusercontent.com/98901924/152216434-9154ae37-36f1-4ce7-9738-6517bf4c00d5.png)

When video is playing:
![image](https://user-images.githubusercontent.com/98901924/152218140-449dabed-5798-4842-81d2-cabd0ca43101.png)

I don't think that it would be an issue with my hardware:
*-memory
          description: System memory
          physical id: 0
          size: 24GiB
     *-cpu
          product: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 3771MHz
          capacity: 4GHz
          width: 64 bits

**Comment by Euro20179** [comment]
Are you using `youtube-dl` or `yt-dlp`,
it might be worth uninstalling youtube-dl and installing yt-dlp (with pip) and `sudo ln -s $(which yt-dlp) /usr/bin/youtube-dl` in case any programs require youtube-dl

**Comment by alan5901** [comment]
I had both installed through pip3. I was using youtube-dl-2021.12.17 but uninstalled it so I could switch to only using yt-dlp-2022.1.21.

I had yt-dlp installed with my package manager, but removed it so it was only installed though pip3.

Now when I try it I get the following error and the video won't play:
![image](https://user-images.githubusercontent.com/98901924/152229984-433eb025-99ee-472e-af8c-ad1bae564ea6.png)

**Comment by Euro20179** [comment]
> I had yt-dlp installed with my package manager, but removed it so it was only installed though pip3.

did you use sudo to install?
and did you run the `ln` command, because i believe mpv relies on there being a `youtube-dl` file.

**Comment by alan5901** [comment]
Opps, I did run the ln command, I forgot to mention it. I'll do some digging into what's going on with the [vaapi] libva: /usr/lib/x86.../iHD_drv_video.so init failed error that I am getting.

Thanks again for all your help in getting this figured out.

**Comment by Euro20179** [comment]
The original question has been answered, and the new question is out of scope of this project, so I'll close it.
