### ISSUE TITLE
"is not a scrapable link" warning when running `ytfzf -l -c SI --sort` but fzf list is displayed correctly afterwords

### ISSUE THREAD

**Issue by kevenwyld** [pystardust/ytfzf#476]
When running `ytfzf -l -c SI --sort` I receive the following warning for all subscriptions listed in `.config/ytfzf/subscriptions`:

```
https://www.youtube.com/c/<name>/videos is not a scrapable link run:
/usr/local/bin/ytfzf --channel-link='https://www.youtube.com/c/<name>/videos'
to fix this warning
```

The command works however and correctly scrapes all the channels after displaying the warning.  Did I miss something in the docs about setting up subscriptions?

Also thank you all for developing this really great tool!

**Comment by kevenwyld** [comment]
Nevermind, I'm a moron....  It's telling me to use `--channel-link=` to FIND the channel-link.... sigh.

**Comment by Euro20179** [comment]
It shows the warning because it's inconvenient for `ytfzf` to convert the links to the proper format, and it could get it wrong, it's better to have the correct link.

**Comment by kevenwyld** [comment]
Thanks, yeah that makes sense.  I've updated the links in my subscription file and everything is working now.
