### ISSUE TITLE
Having a quote causes thumbnail viewer to stop working

### ISSUE THREAD

**Issue by i-a-m-a-k** [pystardust/ytfzf#477]
Issue description: 
1. When the search query contains a single quote `'`, the thumbnail viewer gets a bug. Doesn't matter if video name has it. 
    Thumbnail viewer shows `Unexpected EOF error`
2. When the search query contains a double quote `"`, downloading the thumbnails via curl fails. So the info is shows but thumbnail is missing.
    curl error: `unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 3`

Tested with `bash` and `fish` shells. 

Possible fix: Escape the quotes

**Comment by Euro20179** [comment]
Fixed, it had to do with the fact that the cache directory contained quotes when you use a quote in search, so i just made it so that the cache directory can't have quotes in it. (6e1a7a2c5acf7c4dd4c67ff31acb5bdf26887382)

**Comment by i-a-m-a-k** [comment]
Seems to have fixed it
