### ISSUE TITLE
Termux & ytfzf, jobs_file="${session_cache_dir:-/tmp}, $TMPDIR variable

### ISSUE THREAD

**Issue by stl3** [pystardust/ytfzf#481]
If you are trying to use Termux on Android with ytfzf, the /tmp setting in session_cache_dir needs to use the $TMPDIR variable, and doing a --version is the quickest way to see the error.
>    ytfzf   git:(master) ✗ ./ytfzf --version
> ytfzf: 2.2.beta-4
> ./ytfzf: 109: cannot create /tmp/the-jobs-need-to-be-written-to-a-file.list: Directory nonexistent
> ./ytfzf: 110: cannot open /tmp/the-jobs-need-to-be-written-to-a-file.list: No such file

For Termux users, Line 109 must be changed from:
```jobs_file="${session_cache_dir:-/tmp}/the-jobs-need-to-be-written-to-a-file.list"```
To:
```jobs_file="${session_cache_dir:-$TMPDIR}/the-jobs-need-to-be-written-to-a-file.list"```

Nothing crazy I know, but I did not know where else to post this. $TMPDIR and $PREFIX/tmp can both be used interchangeably.

**Comment by Euro20179** [comment]
Hopefully [fixed](d6f1bd5a61606f5d7323556ddeb52d998b18a1f2)

**Comment by stl3** [comment]
Working now

>    ytfzf   git:(master) ✗ ytfzf --version
> ytfzf: git-1336.950b53a
