### ISSUE TITLE
weird thumbnail placing (arch/dwm/st)

### ISSUE THREAD

**Issue by se7en-x230** [pystardust/ytfzf#484]
The thumbnail preview is all over the place in st.

![image](https://user-images.githubusercontent.com/69777713/154825168-d1fcc5ab-318c-4a9b-bfd7-4e0416f4f16f.png)

**Comment by Euro20179** [comment]
Try running `FZF_DEFAULT_OPTS="--height=100%" ytfzf -t ....`
if this works you can add `FZF_DEFAULT_OPTS="--height=100%"` to `~/.config/ytfzf/conf.sh`

**Comment by se7en-x230** [comment]
thanks works
