### ISSUE TITLE
Don't need the best video quality streaming for any video.

### ISSUE THREAD

**Issue by durwankurnaik** [pystardust/ytfzf#487]
Since I have a slow internet connection, whenever a video is available in 4K, it automatically streams it in that quality. This is not a great experience for me. It buffers alot. I want a way to change it to 1080p at max streaming.

**Comment by durwankurnaik** [comment]
Sorry for not looking around. Got the right flag to select the quality.

**Comment by kohane27** [comment]
For those who are wondering, add the following line to `~/.config/ytfzf/conf.sh`:

`ytdl_pref="bv*[height<=1200]+ba/b[width<2000] / wv*+ba/w"`

This selects up to 1080p videos. Cheers.
