### ISSUE TITLE
Can't default at 1440p by default anymore

### ISSUE THREAD

**Issue by 123jimenez99** [pystardust/ytfzf#491]
### Describe the bug
Hi Everyone, it's me again. This time I have some questions about the quality of the scraped content by ytfzf. Some time ago ytfzf defaulted all the content to my monitor native resolution by using "--ytdl-format=bestvideo[height<=?1440][fps<=?60]+bestaudio/best" in my mpv config. 

For some time now it defaults at 720p and it's very annoying. At first I thought it was a limit to where ytfzf scraped content from  "https://vid.puffyan.us" in my case.  But using the flag "--video-pref=bestvideo" this gets fixed this until the video ends.
I've tried to use "video_pref=bestvideo" in the ytfzf config file to try to fix every time, but it doesn't seem to work. 

Is there a way to ideally apply the same idea of "--ytdl-format=bestvideo[height<=?1440][fps<=?60]+bestaudio/best" in the ytfzf config file? I would be very grateful since this is my only problem with GNU/Linux.

### Information
 - OS:debian sid
 - Terminal:gnome-terminal 
 - Version:41.x
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): lrwxrwxrwx 1 root root 4 feb 21 23:17 /usr/bin/sh -> dash

### Additional context
Thanks in advance and much encouragement to the devs.

**Comment by Euro20179** [comment]
> Version:41.x

guess I should be more specific about what I mean by version, I meant ytfzf's version lol.


> Is there a way to ideally apply the same idea of "--ytdl-format=bestvideo[height<=?1440][fps<=?60]+bestaudio/best" in the ytfzf config file? I would be very grateful since this is my only problem with GNU/Linux.

In ytfzf v2.2.beta-7 or higher: `ytdl_pref="bestvideo[height<=?1440][fps<=?60]+bestaudio/best"`,
Prior to v2.2.beta-7, `video_pref` and `audio_pref` are treated as the same thing, so you'd just use `video_pref="bestvideo[height<=?1440][fps<=?60]+bestaudio/best"`

> I've tried to use "video_pref=bestvideo" in the ytfzf config file to try to fix every time, but it doesn't seem to work.

This is very odd, try putting that in your config file, and tell me the output of `ytfzf -IF -a hi`

**Comment by 123jimenez99** [comment]
So, neither setting video_pref="bestvideo[height<=?1440][fps<=?60]+bestaudio/best" nor --video_pref="bestvideo[height<=?1440][fps<=?60]+bestaudio/best" in the ytfzf config file worked for me. If I put it in the mpv.conf file it complains with an error related to that but it starts playing at 720p. If I just use ytfzf --video-pref="bestvideo[height<=?1440][fps<=?60]+bestaudio/best" it works but only until the video ends.

I think maybe my config file is misnamed? I mean, it's called config and it's next to subscriptions in .config/ytfzf. Maybe it should be called ytfzf.conf or something like that?

Version: 2.1.rc-4 :P

**Comment by Euro20179** [comment]
its supposed to be called conf.sh

**Comment by 123jimenez99** [comment]
Sooooo, yeah... My bad, I stupidly assumed the configuration filename. Considering that the subscriptions file has a very simple filename I assumed that the configuration file for ytfzf would have to follow the same form. 
I'm sorry for wasting your time with dumb mistakes. I'll close the issue.

Have a nice day!
