### ISSUE TITLE
[Feature request]: Navigate input history

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#492]
### Background

[x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
It would be very convenient if `ytfzf` allows navigating history - like e. g. shell does. 

### Feature
```sh
ytfzf -s
foo # search term
# Enter to initiate search
# Esc to exit search results view
# press arrow up to bring up "foo" again
```

### Alternative solutions to problem?
N/A

**Comment by Euro20179** [comment]
Im fairly certain this is not possible due to how the read command works.

**Comment by jose1711** [comment]
How about https://github.com/jose1711/ytfzf/commit/fadcedb4d70556b142cff572faf5cbe26b701f80 ? Seems to be working for me (history is kept only for current session).

**Comment by Euro20179** [comment]
That uses a lot of bash specific features:
* the `-p` and `-e` flags in `read`
* `history` command

But if it works for you, feel free to put this in `~/.config/ytfzf/conf.sh`

```sh
search_prompt_menu () {
    printf "Search\n"
    read -p'>' -er _search
    history -s "$_search"
    printf "\033[1A\033[K\r%s\n" "> $_search"
}
```

(ngl, this is actually kinda cool, and I might try it out myself lol)

**Comment by jose1711** [comment]
Thanks for the tip!
