### ISSUE TITLE
[BUG]: the-jobs-need-to-be-written-to-a-file.list: No such file or directory

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#493]
### Describe the bug
Just before exiting `ytfzf` the following error message appears:
```
/usr/bin/ytfzf: line 113: /home/user/.cache/ytfzf/abc-50145/the-jobs-need-to-be-written-to-a-file.list: No such file or directory
/usr/bin/ytfzf: line 107: /home/user/.cache/ytfzf/abc-50145/the-jobs-need-to-be-written-to-a-file.list: No such file or directory
```

### To Reproduce
1. run `ytfzf -s`
2. start a search for `abc`
3. exit `fzf` (Esc)
4. press Ctrl-D to exit `ytfzf`

### Expected behavior
no error message, exit code 0

### Information
 - OS: Arch Linux
 - Terminal: `roxterm`
 - Ytfzf version: current development branch
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): `lrwxrwxrwx 1 root root 4 jan  8 19:31 /usr/bin/sh -> bash`

### Additional context
`/home/user/.cache/abc-50145` directory does not exist.

**Comment by Euro20179** [comment]
fixed (9f63601e23de30d15a2337b33cac0ecf9a2bfabf)
