### ISSUE TITLE
[BUG]: Link view gets stuck

### ISSUE THREAD

**Issue by p1839251** [pystardust/ytfzf#498]
Hello
### Describe the bug
Using link view, you can no longer use ytfzf.

### To Reproduce
prompt> ytfzf ytfzf
Scraping YouTube (with https://vid.puffyan.us) (ytfzf, pg: 1)
Fetching thumbnails...
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --   460k     0    20     0     0  0:00:01  0:00:01 --:--:--  357k 

ALT+l on first hit. (Still not very useful because the program won't stop and I have to exit to use the link)
So I get back to the main menu, and from then on, I can't start any of the videos.
If I hit enter, When I press enter, it shows the link to all the videos.
Neither ALT+m nor ALT+v works

### Expected behavior
ALT+l shows the link (pause the program, so I can copy the link)
All other videos can be viewed

### Information
 - OS: Archlinux
 - Terminal: yakuake 21.12.0-1
 - Ytfzf version: ytfzf 2.2-1
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
/usr/bin/sh -> bash

**Comment by Euro20179** [comment]
> ALT+l on first hit. (Still not very useful because the program won't stop and I have to exit to use the link)

use `--info-wait` or put `info_wait=1` in `~/.config/ytfzf/conf.sh`

> Neither ALT+m nor ALT+v works

This is odd, I'll look into it when I get home.

**Comment by Euro20179** [comment]
fixed the `alt-m`, `alt-v` issue (c6d5b4c254ed794ccd4d0cef6d52992a8d6a1b86)

This also fixes the bug where shortcuts were permanent,
