### ISSUE TITLE
column: invalid option -- 'o'

### ISSUE THREAD

**Issue by IceCloud76** [pystardust/ytfzf#5]
I'm running. Ubuntu 20.04. The column command doesn't have an 'o' flag it seems. I even checked the man pages. I'm not sure how you got this working that case. Maybe consider using awk instead?

```
column: invalid option -- 'o'
usage: column [-txne] [-c columns] [-s sep] [file ...]
No results found. Try different keywords.
Check for new versions and report at: https://github.com/pystardust/ytfzf
```

**Comment by pystardust** [comment]
I have omitted that option, with some minor sacrifice in history formatting.
Check if the current version works.
Column makes the formatting really neat, ill consider using awk if problem persists.

**Comment by seffs** [comment]
Had the same issue, I am running Raspberry OS.

You can compile util-linux from source and link `column` only:

https://noknow.info/it/os/install_util_linux_from_source?lang=en

Works like a charm

**Comment by pystardust** [comment]
I removed column. Using awk. It feels more stable. @IceCloud76 thanks for the suggestion

**Comment by IceCloud76** [comment]
The new update works great now. Thanks for the quick fix
