### ISSUE TITLE
Change player

### ISSUE THREAD

**Issue by ondrej256** [pystardust/ytfzf#50]
Could an option to configure the video player be added? I am using [devour](https://github.com/salman-abedin/devour) to swallow the terminal window of mpv. So being able to do something like `ytfzf -p "devour mpv"` would be fantastic. Thanks!

**Comment by westofer** [comment]
made it into env variable, 

`YTFZF_PLAYER="devour mpv"` should be added to `.bashrc`

**Comment by ondrej256** [comment]
Even better. Thanks!

**Comment by westofer** [comment]
RIP devour deosn't work

**Comment by westofer** [comment]
issue was with devour, https://github.com/salman-abedin/devour/pull/24
