### ISSUE TITLE
[Feature request]: Gettext (l10n) support

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#502]
### Background

[x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Multiple language support is nice.

### Feature
`ytfzf` messages could be shown in user's locale (it's not very many of them).

### Alternative solutions to problem?
I've tried something in https://github.com/jose1711/ytfzf/tree/gettext - but I don't really know POSIX standard so not sure if it makes any sense.

**Comment by Euro20179** [comment]
Whats is the `ytfzf.pot` file, where am i supposed to put it so that it works correctly?

Also i dont see the point in checking if they have /usr/bin/gettext, its probably better to just define the 2 functions.

Also gettext() looks like it just prints the text? And why does eval_gettext() need to use eval

Sorry for the amount of questions, I just dont understand how this works.

**Comment by jose1711** [comment]
> Whats is the `ytfzf.pot` file, where am i supposed to put it so that it works correctly?

All this is based on https://www.gnu.org/software/gettext/manual/html_node/sh.html. Gettext template (`.pot`) file is generated using the following command:
```
xgettext -o ytfzf.pot -L shell ytfzf
```

Afterwards a translator is supposed to open the file in e. g. `poedit` and turn it into translation file (`.po`) and translate all strings.

![obrázok](https://user-images.githubusercontent.com/1406222/156590666-324b2fa5-0a36-4770-a8c6-fa094e47e6d7.png)

Resulting should then be compiled into binary format (`.mo`) and put into `/usr/share/locale/LANGUAGE_CODE/LC_MESSAGES/ytfzf.mo`.

> Also i dont see the point in checking if they have /usr/bin/gettext, its probably better to just define the 2 functions.

The point was to have a fallback (i. e. English) for systems where `/usr/bin/gettext.sh` is missing completely.

> Also gettext() looks like it just prints the text? And why does eval_gettext() need to use eval

If `gettext()` is missing then original string should be used (hence the `echo`). Eval was used to have the variables properly expanded.

> Sorry for the amount of questions, I just dont understand how this works.

No problem. I can perhaps share `.po`, `.mo` files for actual tests.

**Comment by Euro20179** [comment]
> xgettext -o ytfzf.pot -L shell ytfzf

`xgettext` isn't posix, butttt we could just include `ytfzf.pot` in the source code and let people installing the program do the rest, or include it in the makefile.

However when I run `xgettext -o ytfzf.pot -L shell ytfzf` nothing happens.

**Comment by jose1711** [comment]
> edit:
> It'll only work on gnu systems since gettext.sh is also not a posix script

Hmm. haven't found a "POSIXy" way to add translation strings. Except for something like a text file where each line represents text to translate. But I don't like that approach. Are we closing this?
