### ISSUE TITLE
[BUG]: Selecting a playlist only scrapes forever.

### ISSUE THREAD

**Issue by Aless4ndro13** [pystardust/ytfzf#503]
### Describe the bug
Whenever I select a playlist, the program will scrape the playlist forever, until I don't manually stop it. I thought I was just downloading very long playlists, then I tested with a short playlist of six videos... it didn't stop scraping.

### To Reproduce
Searching with `--type=playlist`
### Expected behavior
Showing me the content of the playlist.
### Information
 - OS: Manjaro Linux 5.10.102-1
 - Terminal: Kitty
 - Ytfzf version: 2.1.rc-4
 - Output of `ls -l "$(which sh)"`: bash

### my ytfzf.sh
```shell
#!/usr/local/bin/ytfzf

show_thumbnails="1"
video_pref="best"
thumbnail_quality="medium"
odysee_video_search_count="40"
enable_submenus="1"
```

**Comment by Euro20179** [comment]
this is fixed in 2.2

**Comment by Aless4ndro13** [comment]
Thank you! Sorry for bringing up an already fixed issue.

**Comment by Euro20179** [comment]
All good
