### ISSUE TITLE
[BUG]: Subscription Scraping inconsistent [NOT WORKING]

### ISSUE THREAD

**Issue by edl2** [pystardust/ytfzf#504]
### Describe the bug
Almost every time I run the subscription feature it says "Nothing was scraped." Yet 1 out of every 15 or so it will bring something up, yet when it does it shows anywhere from 2 to 400 results (ex. 1 video from a month ago and 1 from a year ago and nothing else. The age of the videos is always inconsistent, its in order, but it was weird gaps of time. 
### To Reproduce
ytfzf -c S --sort, ytfzf -c youtube-subscriptions, etc. etc. 
### Expected behavior
Shows subscriptions in order. 
### Information
 - OS: Arch Linux 
 - Terminal: Alacritty 
 - Ytfzf version: 2.2
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Jan  8 13:31 /usr/bin/sh -> bash

**Comment by edl2** [comment]
![ytfzf3](https://user-images.githubusercontent.com/95947898/156674615-fc890979-b66c-4abd-b416-a134b82200e4.png)
![ytfzf1](https://user-images.githubusercontent.com/95947898/156674620-954ec750-e020-43c1-b81d-7116295e323e.png)


I might have found the problem. I did the captcha but that didn't fix the issue.

**Comment by Euro20179** [comment]
This is one of the reasons i have added an invidious scraper, try using `-cSI` instead of `-cS`
