### ISSUE TITLE
[Feature request]: Implement autoplay of next/similar video

### ISSUE THREAD

**Issue by 7ritn** [pystardust/ytfzf#506]
### Background

[ X ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
I like using YouTube for (background) music playback, but with ytfzf I have to search for every song I want to play, because there's no continous autoplay

### Feature
Implement an option for auto playing a new video.

### Alternative solutions to problem?
I don't think there are other solutions.

**Comment by Euro20179** [comment]
For now the best solution would be to create a playlist with songs you like and use it (see VIDEO JSON FORMAT in ytfzf(5)), However i'm assuming you want it to just pick for you.

I have some ideas for an update because of this post.
1. recommended videos from the selected video (only with invidious/youtube scraper) will be written to a file in the cache dir, in the appropriate format to be scraped as a playlist for ytfzf.
2. Create a system customizable via extensions, that allow for things to happen after a video is done playing.
    * this would allow an extension to auto play the next video basically

**Comment by 7ritn** [comment]
I think the first option is more straightforward. The system for option 2 would need to receive the video details to get the next video. However there would still be the question on how the extension would know what the next video is, so it probably would have to implement it's own next video scraper?

**Comment by Euro20179** [comment]
I started working on thsi yesterday. I wrote a scraper that scrapes revommendations from a video url, then i wrote an extention that plays the selected videos, and when theyre done uses ytfzf to scrape the recommended videos of the first url (if more than 1 urls are selected), and plays the first result automatically.

**Comment by Euro20179** [comment]
I pushed this to development branch yesterday, just make sure the auto-play extension is in `~/.config/ytfzf/extensions`

**Comment by 7ritn** [comment]
Okay tried it today and it seems to be working really well. Only thing with this is that I now have to exit MPV and ytfzf seperately, but that makes sense. Love it so much! Thanks :)

**Comment by Euro20179** [comment]
> Only thing with this is that I now have to exit MPV and ytfzf seperately, but that makes sense.

Yeah I don't think this is fixable, but glad you like it, and tbh i use it myself because it's quite useful.

**Comment by martin-greentrax** [comment]
This is very cool, thank you :)

While MPV is playing a song, is there a way to skip to the next related/random song?

**Comment by Euro20179** [comment]
Not currently, no
