### ISSUE TITLE
[Feature request]: Send url/video id to external script or program

### ISSUE THREAD

**Issue by klundry** [pystardust/ytfzf#508]
I looked through the man page and didn't see a way to do what I'm trying to do. I see there is a flag for printing the video url but I'm not sure how I could get that url to trigger a script. I would like an option to send the selected video url to an external command or script. An example is I'd like to send a youtube video to Kodi to be played there instead of locally.

**Comment by Euro20179** [comment]
for your specific use case you can write a custom url handler

```sh
kodi () {
   #put whatever code in here that will happen when you select a video, "$@" represents all video urls.
}

#when use use --kodi as a flag, this function will happen.
on_opt_parse_kodi(){
    url_handler=kodi
}
```

however, couldn't you just use pipes?

```sh
ytfzf -L ... | the-external-program
```

**Comment by klundry** [comment]
Ok, thanks. I'll give that a try. I didn't think a pipe would work if I was interactively browsing. That could work though. So if I do "ytfzf -L | *mycommand*" it will send whichever URL I hit enter on to the pipe?

**Comment by Euro20179** [comment]
it should yes.

**Comment by klundry** [comment]
Oh that might do exactly what I want then. Pardon my ignorance!

**Comment by klundry** [comment]
It's not working when I run "ytfzf -L |  xargs kodi-cli -y" and hit enter on a video, something gets sent to kodi but not a valid URL. I get an error and nothing plays.

Just to see if the output is different I run "YTURL=$(ytfzf -L); echo $YTURL" and get this:

> ps vita https://youtube.com/watch?v=OLzUK5CsMjI

So when using it with a pipe there's extra stuff in there getting sent to kodi which is why it isn't playing. I am able to get it to work by running it through awk first to match the field with youtube in it.

**Comment by Euro20179** [comment]
> It's not working when I run "ytfzf -L | xargs kodi-cli -y" and hit enter on a video, something gets sent to kodi but not a valid URL. I get an error and nothing plays.]

This is not helpful. Idk what kodi-cli is, idk if it accepts input from a pipe, what does the error say.
Running `ytfzf -L hi | xargs echo` works as expected so there is something else going on here.

What version of ytfzf do you have?
What is the output of `ytfzf -L ...`?
What was the awk command used?

**Comment by klundry** [comment]
ytfzf version 2.2
kodi-cli is just the bash script that allows remote controlling kodi from the CLI over the network and yes it accepts input from a pipe. As I said I got it to work by running it through awk first to get just the URL.

This is the command that worked.
> ytfzf -L | awk '/youtube/ {print $0}' | xargs ./kodi-cli -y

The problem is the search term and a > is getting output when it comes through the pipe. Like with the following command without kodi-cli.

> YTURL=$(ytfzf -L); echo $YTURL

**Comment by klundry** [comment]
If you redirect the output to a file you'll see what I mean. 

ytfzf -L > test.txt

**Comment by Euro20179** [comment]
`ytfzf -L hi > test.txt` results in:
> https://youtube.com/watch?v=5qap5aO4i9A
> 

`awk '/youtube/{print $0}' test.txt` results in:
> https://youtube.com/watch?v=5qap5aO4i9A
>

It's exactly the same, so idk.

**Comment by klundry** [comment]
Ah, looks like it's another quirk of busybox.

**Comment by klundry** [comment]
Same command outputs just the URL on my laptop running Manjaro. But on my Pinephone running PostmarketOS (alpine) which uses busybox I get that extra output along with the URL.

**Comment by Euro20179** [comment]
That's very odd, when i use busybox on ytfzf, i just get the link output like normal, what is in your config file on your pinephone?, are you using an alias of some sort?

**Comment by klundry** [comment]
Ohhhh, ok now I see what's happening. It's when the using ytfzf -L with no search term and letting ytfzf prompt for a search term. For some reason the prompt and search term you enter is getting passed along with the output.

**Comment by Euro20179** [comment]
ahhhhhhhhhhhhhhhhhhhhhh yes.

the default is that the search prompt is printed to stdout instead of stderr, tbh I dont see much problem with this as long as `awk '/youtube/{print $0}'` works, but if you want you can add this to your config and it should fix it


```sh
search_prompt_menu () {
	printf "Search\n>" >&2
	read -r _search
	printf "\033[1A\033[K\r%s\n" "> $_search" >&2
}
```

**Comment by klundry** [comment]
Thanks. Yeah, it's not a big deal since it's easy enough to work around.

**Comment by Euro20179** [comment]
cool! Closing issue.
