### ISSUE TITLE
[BUG]: can't use ytfzf -f

### ISSUE THREAD

**Issue by hoowwshii** [pystardust/ytfzf#509]
### Describe the bug
youtube-dl : error: no such option: --format-sort
### To Reproduce
when using "ytfzf -f", it happens
### Expected behavior
selection for resolution/audio
### Screenshots
![image](https://user-images.githubusercontent.com/68774737/157855555-09e48278-ab96-46b2-b8a5-01496a0edda7.png)

### Information
 - OS: arco linux
 - Terminal: alacritty
 - Ytfzf version: 2.2
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Jan  9 01:31 /usr/bin/sh -> bash

**Comment by hoowwshii** [comment]
im an idiot, in the end, i just realized how the new ytfzf works, my bad

**Comment by Euro20179** [comment]
Actually this is interesting, I didnt know youtube-dl didnt have support for formst-sort, might have to fix that
