### ISSUE TITLE
[Feature request]: Vim-Like Bindings

### ISSUE THREAD

**Issue by ThamognyaKodi** [pystardust/ytfzf#510]
### Background

[x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?

Since vim-like bindings would be more comfortable for vim or vi or vim-like users and there is no loss since you do not need to remove the original key bindings.

### Feature
Description of your proposed feature.

I would suggest vim like bindings

for example
`j` - down
`k` - up
'l' - right
'h' - left

and etc.

morevoer you can still keep the original arrow keybindings

### Alternative solutions to problem?

emacs bindings, but I would prefer vim bindings.

**Comment by Euro20179** [comment]
i would look through the fzf manpage cause i forget exaxtly how to do this, but its somethinf like

`--bind "j:down,k:up"` etc...

then in `~/.config/ytfzf/conf.sh` you can put

`FZF_DEFAULT_OPTS='--bind "j:down,k:up"'`

**Comment by ThamognyaKodi** [comment]
Yup, that works. Thanks for the help.
