### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by sakibulxyz** [pystardust/ytfzf#513]
I just want to know if there a way to select vid **resolution** because my internet is kind of slow for 1080p vids. I looked every where But didn't find  any way to do that.

**Comment by Euro20179** [comment]
`-f --format-selection=simple`?, but technically `-f` alone is the same thing just with more options.

**Comment by qoheniac** [comment]
You could also add `ytdl-format = bestvideo[height<=?720]+bestaudio/best[height<=?720]` to your `~/.config/mpv/mpv.conf`.
