### ISSUE TITLE
[BUG]: View count is formatted incorrectly

### ISSUE THREAD

**Issue by gardockt** [pystardust/ytfzf#514]
### Describe the bug
View count for each video has the last digit removed and contains two separators. In some cases a comma is inserted in front of the number or between separators. The bug was introduced in commit 8d7b1b4, and is occurring on both `master` and `development` branches.
Removing the last digit might be a result of `add_commas` function, which for input "123456" returns "112,345".

### To Reproduce
1. Search for any phrase

### Expected behavior
View count is shown as a comma-separated number with one leading separator, and has a value equal to scraped view count.

### Screenshots
![screenshot](https://user-images.githubusercontent.com/42496375/159250470-a4b3f225-4428-4cf8-9548-89ce72d45ce9.png)
Scraped view count for the first video: 163422

### Information
 - OS: Arch Linux
 - Terminal: alacritty
 - Ytfzf version: 2.2
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): `lrwxrwxrwx 1 root root 4 01-08 19:31 /usr/bin/sh -> bash`

### Additional context
Versions of related software:
`GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)`
`GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`

**Comment by Euro20179** [comment]
Weird, that breaks it for me. We're using the exact same version of awk.

For now you can just copy and paste the add_commas function into your config, and change the line you suggested to change.

**Comment by gardockt** [comment]
After further analysis, it looks like the error I noticed is inside `video_info_text` function, which explains why view count works fine with thumbnails enabled. Argument passed to `add_commas` contains leading separator, resulting in returned value being something like "|,123,456".

Fix that worked for me (line 52):
```diff
-       [ "${views#|}" -eq "${views#|}" ] 2>/dev/null && views="$(printf "|%s" "${views#|}" | add_commas)"
+       [ "${views#|}" -eq "${views#|}" ] 2>/dev/null && views="|$(echo "${views#|}" | add_commas)"
```

**Comment by Euro20179** [comment]
This should be fixed now.

**Comment by gardockt** [comment]
Thank you, now everything seems to be fine.
