### ISSUE TITLE
Issues on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by SJTheGreat06** [pystardust/ytfzf#516]
Hey Guys, 
I'm using Ubuntu 20.04 LTS and I tried to run ytfzf in it, I installed all the above dependencies except ueberzug which is not natively available on Ubuntu, so I tried to install it with PIP but that also failed, so ultimately I tried to ignore ueberzug and went ahead with installation. Everything was running smoothly until I selected my favorite video and tried to run it. As soon as I pressed Enter on the desired video, it gives multiple errors and as a result I'm unable to watch videos on Ubuntu. I'm attaching the errors herewith:
<pre><font color="#AA0000">[ytdl_hook] ERROR: aIAZSZPy3kk: YouTube said: Unable to extract video data </font>
<font color="#AA0000">[ytdl_hook] youtube-dl failed: unexpected error occurred </font>
<font color="#AA0000">Failed to recognize file format.</font>
</pre>

And this is the version info I'm using:
<pre>ytfzf: 2.2</pre>

It's my humble request from the community & developers to help me to fix this issue, your help is highly appreciated by me
Thank you, 
Have a great day ahead.

**Comment by Euro20179** [comment]
Did you install `youtube-dl` or `yt-dlp` if you installed `youtube-dl`, uninstall it. install `yt-dlp` with `sudo pip3 install yt-dlp`

If that doesn't work, try `ytfzf --ytdl-pref=best ...`. It could also just be that specific video, so it might be good trying out different videos.

**Comment by SJTheGreat06** [comment]
> Did you install `youtube-dl` or `yt-dlp` if you installed `youtube-dl`, uninstall it. install `yt-dlp` with `sudo pip3 install yt-dlp`
> 
> If that doesn't work, try `ytfzf --ytdl-pref=best ...`. It could also just be that specific video, so it might be good trying out different videos.

Sir, 
Thank you for your swift response on my query, but sir sorry to say, it doesn't fix the issue, I uninstall both youtube-dl & yt-dlp with <pre>sudo apt remove --purge</pre> command and install yt-dlp with <pre>sudo pip3 install yt-dlp</pre> as guided, but again I get an error something like this:<pre><font color="#AA0000">[ytdl_hook]  </font>
<font color="#AA0000">[ytdl_hook] youtube-dl failed: not found or not enough permissions </font>
<font color="#AA0000">Failed to recognize file format.</font></pre>

I tried with multiple videos but the error is same each and every-time.

**Comment by Euro20179** [comment]
I had a feeling that error would happen, since yt-dlp is a replacement for youtube-dl, but mpv needs the file `youtube-dl` to be present, so to fix this you can run `sudo ln -s /usr/bin/yt-dlp /usr/bin/youtube-dl`.
After running that, try out ytfzf and see what happens, both your way, and the way i suggested.

**Comment by SJTheGreat06** [comment]
> I had a feeling that error would happen, since yt-dlp is a replacement for youtube-dl, but mpv needs the file `youtube-dl` to be present, so to fix this you can run `sudo ln -s /usr/bin/yt-dlp /usr/bin/youtube-dl`. After running that, try out ytfzf and see what happens, both your way, and the way i suggested.

Sir, when I typed this command, I got this error: 
<pre><font color="#5FAFD7"><b>sudo ln -s /usr/bin/yt-dlp /usr/bin/youtube-dl</b></font>
ln: failed to create symbolic link &apos;/usr/bin/youtube-dl&apos;: File exists</pre>

**Comment by Euro20179** [comment]
what's the output of `youtube-dl --version`?

Are you sure you uninstalled `youtube-dl` properly, `sudo apt purge youtube-dl`?

If so, you can run `sudo ln -sf /usr/bin/yt-dlp /usr/bin/youtube-dl`

**Comment by SJTheGreat06** [comment]
> what's the output of `youtube-dl --version`?
> 
> Are you sure you uninstalled `youtube-dl` properly, `sudo apt purge youtube-dl`?
> 
> If so, you can run `sudo ln -sf /usr/bin/yt-dlp /usr/bin/youtube-dl`

Sir, I fixed the issue, actually the issue was that I was supposed to install youtube-dl with PIP but instead I did it with apt, so, when I did this command:
<pre>sudo -H pip install --upgrade youtube-dl</pre>
And this fixed the issue.

**Comment by Euro20179** [comment]
fair enough, it's just that `youtube-dl` is seen as outded because it doesn't get updated, so using yt-dlp and making a link to it is better from my experience.

**Comment by SJTheGreat06** [comment]
> what's the output of `youtube-dl --version`?
> 
> Are you sure you uninstalled `youtube-dl` properly, `sudo apt purge youtube-dl`?
> 
> If so, you can run `sudo ln -sf /usr/bin/yt-dlp /usr/bin/youtube-dl`

Sir, thank you very much for your precious time & showing concern towards the issue. 
I want to wish you BEST OF LUCK for your future projects and may always rise & shine, thank you for such a great and useful tool.

**Comment by Euro20179** [comment]
> Sir, thank you very much for your precious time & showing concern towards the issue.

Yw.

> I want to wish you BEST OF LUCK for your future projects and you may always rise & shine, thank you for such a great and useful tool.

Yw again, and have fun on your linux journey.
