### ISSUE TITLE
[Feature request]: Home pages and favorites list

### ISSUE THREAD

**Issue by guilhermeprokisch** [pystardust/ytfzf#519]
### Background

[ x ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
To have the same suggestions as we access youtube home page

### Feature
Description of your proposed feature.
Get a list of youtube homepage to watch

**Comment by Euro20179** [comment]
install the recommended scraper and use `ytfzf -c recommended`

**Comment by guilhermeprokisch** [comment]
https://github.com/pystardust/ytfzf/blob/master/addons/scrapers/recommended

**Comment by guilhermeprokisch** [comment]
Yes.. Just found it now.. I will come back here to close the issue :)

Thanks for this nice tool!
