### ISSUE TITLE
[BUG]: Don't break search-again mode if nothing is scraped

### ISSUE THREAD

**Issue by jose1711** [pystardust/ytfzf#520]
### Describe the bug
I don't believe `ytfzf` is supposed to terminate the loop if there are zero search results.

### To Reproduce
```
ytfzf -s
# search for the following terms: eemgmcwfxk rlisfrfqva
```
### Expected behavior
receive message `Nothing was scraped`, `ytfzf` continues waiting for another user entry

### Actual behavior
```
Scraping YouTube (with https://vid.puffyan.us) (eemgmcwfxk rlisfrfqva, pg: 1)
Scraping YouTube (with https://vid.puffyan.us) (eemgmcwfxk rlisfrfqva, pg: 2)
Scraping YouTube (with https://vid.puffyan.us) (eemgmcwfxk rlisfrfqva, pg: 3)
Nothing was scraped
# ytfzf exits with exit code 4 (scraping error)
```

### Screenshots
n/a

### Information
 - OS: Arch Linux x86_64 rolling
 - Terminal: `roxterm`
 - Ytfzf version: `git-1372.d1a839a`
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): `/usr/bin/sh -> bash`

**Comment by Euro20179** [comment]
This could really go either way imo, but I think it would make more sense to not break, ill look into it when I get home

**Comment by Euro20179** [comment]
Aight, I've made a push to development, you can test it out.

**Comment by jose1711** [comment]
thank you for such a quick fix. working nicely, closing.
