### ISSUE TITLE
[Feature request]: music.youtube.com support (Youtube Music)

### ISSUE THREAD

**Issue by 07416** [pystardust/ytfzf#526]
### Background

[ x ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
music.youtube.com is Youtube's music streaming platform, which seems to as comprehensive as its competitors and unlike for instance Spotify, DRM isn't used. The Youtube's main platform in general has no official uploads for full albums.

[Youtube Music](https://en.wikipedia.org/wiki/YouTube_Music) launched in 2015 and audio format is 128 kbit/s [AAC](https://en.wikipedia.org/wiki/Advanced_Audio_Coding) (the free tier). 

### Feature
Allow searching music.youtube.com separately from the main Youtube website.

example pages:

https://music.youtube.com/search?q=beatles
https://music.youtube.com/channel/UC2XdaAVUannpujzv32jcouQ

### Alternative solutions to problem?
N/A

**Comment by Euro20179** [comment]
This has been added as an extention in the development branch,
currently channel pages don't work, and playlists only scrape a max of 30 videos.
I probably won't be able to fix the ladder as I've never been able to with youtube.

If you install the extensions manually, make sure to put `yt-music` `yt-music-playlist` and `yt-music-utils` in `~/.config/ytfzf/scrapers`

**Comment by Euro20179** [comment]
`yt-music` scraper is now available as an addon in v2.4, if you have any other suggestions for improving yt-music, i'll look into it.

**Comment by 07416** [comment]
The script appears to mainly return user uploads: for instance searching for `deep purple` appears to additionally exclusively find results from youtube.com, not Youtube Music.

On music.youtube.com ([a sample page](https://music.youtube.com/search?q=deep+purple)), the search only returns community uploads under 'Videos' (and 'Community Playlists') as users can't submit content to Youtube Music itself (limited to labels and distributors from what I know).
