### ISSUE TITLE
[BUG]: using ytfzf -f produces an error on Arch install

### ISSUE THREAD

**Issue by floofywoofles** [pystardust/ytfzf#527]
### Describe the bug
I tried to use -f (to select format for audio/video) and it throws an error. Runs fine without -f though.
### To Reproduce
Run ytfzf -tf and watch any video

### Expected behavior
Should just play the video without an issue

### Screenshots
![image](https://user-images.githubusercontent.com/69652534/163032183-4ea9b360-345d-40f9-aa03-8d5648631e2c.png)

### Information
 - OS: Arch Linux x86_64
 - Terminal: alacritty 0.10.1 (2844606d)
 - Ytfzf version: ytfzf: 2.2
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Jan  8 13:31 /usr/bin/sh -> bash

**Comment by floofywoofles** [comment]
Also, this does work on Manjaro. Its only an issue on fresh arch install

**Comment by Euro20179** [comment]
This has been fixed in the development version.
But also in the development version the default -f screen is the old one, you can use `--format-selection=normal` to fix this
```sh
git clone -b development https://github.com/pystardust/ytfzf
cd ytfzf
./ytfzf -tf --format-selection=normal ...
```
