### ISSUE TITLE
[BUG]: Thumbnail resolution is extremely low

### ISSUE THREAD

**Issue by entodoays** [pystardust/ytfzf#529]
### Describe the bug
The video thumbnails show in so low a resolution that they are practically useless
### To Reproduce
Simply use the -t option.
### Expected behavior
Resolution is high enough for the thumbnail to be visible.
### Screenshots
![Screenshot from 2022-04-19 10-48-49](https://user-images.githubusercontent.com/7609728/163963976-3d05a98a-6da5-4bf9-8ddf-49593356a303.png)

### Information
 - OS: Ubuntu 21.10
 - Terminal: gnome-terminal
 - Ytfzf version: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Oct  7  2021 /usr/bin/sh -> dash

**Comment by Euro20179** [comment]
`--thumbnail-quality=maxres`

Also it looks like you might be using chafa, if so it's going to be bad quality regardless

**Comment by entodoays** [comment]
I tried both chafa and catimg because I do sometimes use Wayland. Chafa with --thumbnail-quality=maxres produces better, but still extremely pixellated thumbnails. Catimg doesn't seem to be compatible with this parameter.

**Comment by Euro20179** [comment]
by the nature of those programs, you cant get better quality thumbnails, so this issue is resolved.


also if you use kitty terminal i highly recommend using --thumb-viewer=kitty as in my opinion its the best wayland option. 
I am planning to add mpv as an option, however it would be a seperate window.

**Comment by Kabouik** [comment]
I don't understand why `chafa` imposes such low resolution, as `chafa /path/to/some/img` in terminal does show it with a much better resolution (although it's still Sixel, it *looks* like full resolution). Is there another limitation when using it to show thumbnails for `ytfzf`?

**Comment by Euro20179** [comment]
chafa uses ascii to display a thumbnail, there shouldn't be other limitations.

**Comment by Kabouik** [comment]
But chafa is capable of displaying sixel images, is that not supported when using it via ytfzf?

**Comment by Euro20179** [comment]
while chafa is capable of sixep, fzf is not therefore its not supported in ytff.

ueberzugpp supports sixel and it somehow works in ytfzf, idrk how. to use that, install ueberzugpp and run `ytfzf -T sixel`

**Comment by Kabouik** [comment]
Thanks, I finally managed to compile `ueberzugpp` (I'm on aarch64 and could not use prebuilt binaries or MBR) and I can confirm it works, although the alignment and size of thumbnails seem a bit off:

![ss20230914-014539](https://github.com/pystardust/ytfzf/assets/7107523/eab70f35-ebe0-4596-94fb-bfe41af11171)

**Comment by Euro20179** [comment]
make sure `fzf`'s height is set to 100%.

I'd do that by running
```sh
FZF_DEFAULT_OPTS="--height=100%" ytfzf ...
```

**Comment by Kabouik** [comment]
Thanks, that seems to do it (but thumbnails remaind small, there is a lot of empty space to use on the left fzf pane).
