### ISSUE TITLE
Install version 1.x (latest old version) of ytfzf

### ISSUE THREAD

**Issue by anishmittal2020** [pystardust/ytfzf#530]
### Before Making This Post
* [x] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?
How can I install version 1.x (latest old version) of ytfzf? Current version for me is quite unstable and plagued with many issues which I am unable to resolve, I would be happy to install the latest old version.

----

I am facing with 2.2 onwards
[[BUG]: ytfzf: Thumbnails not getting displayed · Issue #524 · pystardust/ytfzf](https://github.com/pystardust/ytfzf/issues/524)](https://github.com/pystardust/ytfzf/issues/524)

With 2.3 onwards, it gives many error messages!

**Comment by Euro20179** [comment]
```sh
git clone https://github.com/pystardust/ytfzf
git tag list
git switch <one of the tags>
```

it mayyy be better to put ytfzf somewhere in path manually, as the makefile differs a lot.

Also the thumbnails usually have nothing to do with the version and more with ueberzug funkyness, I wish you luck.

**Comment by anishmittal2020** [comment]
@Euro20179 All my issues have been solved by going back to version 1.

**Comment by Euro20179** [comment]
interesting, other than thumbnails what issues do you have.

**Comment by anishmittal2020** [comment]
Following issue was also solved:


I successfully installed ueberzug as you suggested, but I still don't get any thumbnail. May be ytfzf could print some helpful debug message to identify what is going wrong? OR what do you suggest?

![image](https://user-images.githubusercontent.com/42092626/162688250-b69cc7f7-5691-49ce-9f9e-0ceed10f8037.png)

![image](https://user-images.githubusercontent.com/42092626/162688643-beccd873-c0d9-4939-b69c-52dc644c98e8.png)

----

Also, now videos stopped playing as shown below

![image](https://user-images.githubusercontent.com/42092626/162690662-daf5a3c0-ccfa-4141-b8bb-9dace734e10a.png)

_Originally posted by @anishmittal2020 in https://github.com/pystardust/ytfzf/issues/524#issuecomment-1094659388_
