### ISSUE TITLE
[BUG]: Playing playlist with -m option

### ISSUE THREAD

**Issue by Timmy-Tenders** [pystardust/ytfzf#531]
### Describe the bug
This bug makes only one song of the playlist play and in video mode when it was requested that it be in audio only. Once the search term is passed a list is shown with the playlists. Once a playlist is selected the songs of the playlist are shown. This playlist is not played entirely even from this song forward.

### To Reproduce
ytfzf --audio-only --type=playlist <search_term>

### Expected behavior
The expected behavior is for this to show the playlist found in the search. Be able to select the playlist and then the playlist play entirely in audio only mode. 

### Information
 - OS:Endevour OS(Arch)
 - Terminal:Terminator
 - Ytfzf version:2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):lrwxrwxrwx 1 root root 4 Jan  8 19:31 /usr/bin/sh -> bash

**Comment by Euro20179** [comment]
The way you've run it is expected behavior, when you select a playlist it opens a submenu, so you'd need to use `--submenu-opts='-m'` I should probably explain that better in the manual,

Either way, it seems your looking for `ytfzf --disable-submenus -m --type=playlist ...`

**Comment by Euro20179** [comment]
No need to be sorry. The submenus just aren't very well documented.
