### ISSUE TITLE
[BUG]: /bin/ytfzf: línea 1899: interface_gui: order not found

### ISSUE THREAD

**Issue by benchile55** [pystardust/ytfzf#532]
I use Manjaro Stable branch kernel 5.15 and installed dmenu package for when I added interface/gui file  into my home/.config/ytfzf/interface/gui.bashsrc as executable  file;  firstly I had a request to install dmenu package missing and after it was  added it displayed search top bar query and when search query was filled came up this line 1899 : order not found error and stopped running then closed my query.

Do I need some extra package as installed?

Help please maybe I am not doing it right.

Thanks

### Information
 - OS:
 - Terminal:
 - Ytfzf version:
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):

**Comment by Euro20179** [comment]
>  into my `home/.config/ytfzf/interface/gui.bashsrc`

It should be called `gui` not `gui.bashrc`
