### ISSUE TITLE
[BUG]: Subscriptions (fancy_subs) unsorted

### ISSUE THREAD

**Issue by Geoplegatill** [pystardust/ytfzf#533]
### Describe the bug
Subscriptions (fancy_subs) unsorted

### To Reproduce
ytfzf -cSI

### Expected behavior
One subscription/channel at a time (sorted)

### Screenshots
![ytfzf fancy_subs sorting](https://user-images.githubusercontent.com/91780451/166831646-ef580fd1-7877-4c13-b181-bfa3a58b3bd9.png)

### Information
 - OS: Linux Mint 20.3
 - Terminal: GNOME Terminal
 - Ytfzf version: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Jul 18  2019 /usr/bin/sh -> dash

### Additional context
Version 1.2.0 worked perfectly with the fancy_sub sorting

**Comment by Euro20179** [comment]
`ytfzf -cSI --fancy-subs --sort=0` seems to work for me. However, it will not sort the channels by upload date, it'll be a random order I believe. It would be too impractical to sort properly

**Comment by Geoplegatill** [comment]
Still the same result for me. The videos per channel gets sorted just fine, but the fancy_sub/channel line are "unsorted"/"not in order" as the picture

With sort=1 every video gets sorted (newest first) but also every fancy_sub/channel do as well bunching all channels togheter after each other

**Comment by Euro20179** [comment]
I *may* have a solution, download the latest version of ytfzf, and switch to the development branch
```sh
git clone https://github.com/pystardust/ytfzf
cd ytfzf
git checkout development
```
then remove line 568, and change line 566 to
```sh
jq --arg left "${fancy_subs_left}" --arg right "${fancy_subs_right}" '"\($left + .[0].channel + $right)" as $div | [{"title": $div, "action": "do-nothing", "url": $div, "ID": "subscriptions-channel:\(.[0].channel)" }] + .[0:'"$sub_link_count"']' < "$_tmp_subfile"

```

**Comment by Geoplegatill** [comment]
It is working now!
Thanks.

**Comment by Euro20179** [comment]
Great! This will be in the next update.
