### ISSUE TITLE
[BUG]: Thumbnail preview moves to other terminal window on loop

### ISSUE THREAD

**Issue by Geoplegatill** [pystardust/ytfzf#534]
### Describe the bug
Thumbnail preview moves to other terminal window on loop

### To Reproduce
ytfzf -cSI, play video, open another terminal, exit video, when ytfzf is looping the thumbnail gets printed on the other terminal

### Expected behavior
Keep thumbnail preview on "original" terminal window

### Screenshots
![ytfzf thumb_loop_terminal](https://user-images.githubusercontent.com/91780451/166833726-d655d02e-40cf-485b-939e-2be5cf41e096.png)

### Information
 - OS: Linux Mint 20.3
 - Terminal: GNOME Terminal
 - Ytfzf version: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
lrwxrwxrwx 1 root root 4 Jul 18  2019 /usr/bin/sh -> dash

### Additional context
My conf.sh has:
show_thumbnails=1
is_loop=1
fancy_subs=1

**Comment by Euro20179** [comment]
If you're using swayimg, it's because you had focus on the other terminal when the thumbnail wanted to show. If you're not using swayimg then I'm not sure what the problem is, as I'm not able to replicate it.

**Comment by Geoplegatill** [comment]
I'm using ueberzug. It's not the focus thing, it picks the last opened terminal window, for example if I open two more terminals, focus on web browser, exit ytfzf/loop, it picks the third/last opened terminal window to print the thumbnail on...

**Comment by gardockt** [comment]
This is a known issue for Ueberzug. It is considered unfixable and occurs on some terminal emulators - GNOME Terminal is one of them. More details [here](https://github.com/seebye/ueberzug/wiki/Troubleshooting/119e30f331799b30fb9594db29740685cb09425b#images-appear-on-the-wrong-terminal-window).

**Comment by Geoplegatill** [comment]
Interesting. Yep, with another terminal emulator (Alacritty) it doesn't happen. I'm happy with that solution, thanks!
