### ISSUE TITLE
[BUG]: Video format selection broken

### ISSUE THREAD

**Issue by kickerofelves** [pystardust/ytfzf#536]
### Describe the bug
No matter what resolution I choose I always 1080p video.

### To Reproduce
Use a command like ```ytfzf -f "live lofi"``` and choose a live stream.
### Expected behavior
Chosen format should be streamed.

### Screenshots
n/a
### Information
 - OS: linux
 - Terminal: konsole
 - Ytfzf version: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
Using dash.

### Additional context
Just did a pull to update my local copy. This seems to be a regression of #465

**Comment by Euro20179** [comment]
I believe this happens because of the way the preference system works.

livestreams don't have a seperate audio and video preference, so it defaults to "best", if I got rid of this, you would *only* see video when selecting live streams, so I think in it's current state it's actually better.

**Comment by kickerofelves** [comment]
Sorry I don't understand. Because live streams don't have separate video and audio it isn't possible to "_only_ see video." It seems whatever video option is chosen the audio comes along with it.

I changed https://github.com/pystardust/ytfzf/blob/9349dc54eedb839d81797784dc708dc1821247e7/ytfzf#L388 from "simple" to "normal" and it works properly. I think the logic in get_video_format_simple() is broken. Not only does it present a set of options then ignore the user's choice but it also gives "Audio" as an option but crashes if it's chosen. Again, this seems like a regression of #465 where line 1692 is hardcoding best values instead of the choice. https://github.com/pystardust/ytfzf/blob/9349dc54eedb839d81797784dc708dc1821247e7/ytfzf#L1692

**Comment by Euro20179** [comment]
Alright I think i've fixed it, i've changed line 1692 to `printf "%s+%s/%s/%s" "[height=?$quality][vcodec!=?vp9]" "bestaudio" "[height=?$quality][vcodec!=vp9]" "bestaudio"`

This does not fix the audio only crashing, i'll edit this when i fix that as well.

**Comment by Euro20179** [comment]
I have come back to this problem once again and I believe I have made it as close to perfect as I can.

If a video has a seperate video and audio stream, it will use `$YTDLP_ID_FOR_THE_QUALITY+bestaudio/bestaudio`
(eg: `250+bestaudio/bestaudio`)

If not it uses `best[height=$quality]/best[height<=?$quality]/bestaudio`
(eg: `best[height=720]/best[height<=?720]/bestaudio`)

**Comment by kickerofelves** [comment]
That sounds great! Since I generally prefer more information over less I'm going to stick to the original format selection menu. Are you planning on removing ```get_video_format()```?

**Comment by Euro20179** [comment]
I dont see the reason to get rid of it, if you want a lot of information, and quite frankly more control --format-selection=normal if not use simple.

(`get_video_format` is normal).

Also I just thought about this but will have to confirm it later there's a chance `--format-selection=normal` is broken with livestreamsc

**Comment by kickerofelves** [comment]
OK I didn't know ```--format-selection=normal``` was an option. I didn't see it in the -h listing. I just tried with the latest version in the dev branch and it does work with live streams. Thanks!

**Comment by Euro20179** [comment]
Oh cool, thanks for testing.

There are many options not listed in -h cause it would be too many. The rest are in the man page, if you dont have it installed its also on the wiki.
