### ISSUE TITLE
[Feature request]: Improve autoplay when using mpv

### ISSUE THREAD

**Issue by 7ritn** [pystardust/ytfzf#537]
### Background

[ x ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
When using autoplay to quit you have to first exit mpv and then quickly exit ytfzf. This is a bit annoying.

### Feature
Detect an intentional exit and not an EOF exit from mpv by using the exit code ([https://mpv.io/manual/master/#exit-codes](https://mpv.io/manual/master/#exit-codes)) of mpv and if it's an intentional exit quit ytfzf as well. 

### Alternative solutions to problem?
--

**Comment by qoheniac** [comment]
You could break the while loop if mpv was closed on purpose like this: #538

**Comment by Euro20179** [comment]
This is now in v2.4
