### ISSUE TITLE
[BUG]: -d option doesnt work

### ISSUE THREAD

**Issue by ENRORMA** [pystardust/ytfzf#539]
### Describe the bug
the -d option doesnt work

### To Reproduce
use the -d option when searching for a video like ytfzf -d darkviperau and select a video

### Expected behavior
video should be downloaded

### Screenshots
![Screenshot from 2022-05-20 18-13-31](https://user-images.githubusercontent.com/105936026/169570311-e651d09d-db09-4ee1-9912-6a931c153640.png)

### Information
 - OS: Linux Mint 20.3
 - Terminal: gnome-terminal
 - Ytfzf version: ytfzf: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): lrwxrwxrwx 1 root root 4 May 17 18:40 /usr/bin/sh -> dash

**Comment by Euro20179** [comment]
Try uninstalling yt-dlp and reinstalling with `sudo pip install yt-dlp`
