### ISSUE TITLE
[BUG]: yt-dlp installed but youtube-dl is used with issue on 2.3

### ISSUE THREAD

**Issue by ewermor** [pystardust/ytfzf#541]
### Describe the bug
I have installed ytfzf 2.3 from source, yt-dlp from the official repo but youtube-dl seems to be used instead running into an error : 
```
[ytdl_hook] youtube-dl failed: not found or not enough permissions
Failed to recognize file format.
```
But, in the source file "ytfzf" the following code display "yt-dlp" :
```
 [ -z "$ytdl_path" ] && { command_exists "yt-dlp" && ytdl_path="yt-dlp" || ytdl_path="youtube-dl"; }
 echo "$ytdl_path";
```

### To Reproduce
- Install ytfzf 2.3 from source
- install yt-dlp from the official repository using : 
```
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp
```

### Expected behavior
Have yt-dlp used by default

### Information
 - OS: Debian 10
 - Terminal: st
 - Ytfzf version: 2.3
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`): /usr/bin/sh -> dash

**Comment by Euro20179** [comment]
thats an mpv error. Mpv requires you have a symlink to youtube-dl.

`sudo ln -sf /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl`

**Comment by ewermor** [comment]
It work better ! Thank you @Euro20179.
