### ISSUE TITLE
I have an error with ytfzf

### ISSUE THREAD

**Issue by XXCryp70XX** [pystardust/ytfzf#545]
```
File "/home/khaled/.local/lib/python3.9/site-packages/ueberzug/ui.py", line 285, in _set_click_through
    Xshape.SO.Set, Xshape.SK.Input, 0,
AttributeError: module 'Xlib.ext.shape' has no attribute 'SO'
```

happens  everytime when i use ueberzug as thumbviewer

**Comment by Euro20179** [comment]
this is a bug with ueberzug, I'm not entirely sure how to fix it, you could try deleting ~/.Xauthority, and relogging in to your computer. You could also try installing `xlib` with pip.
