### ISSUE TITLE
[BUG]: Is Vid Puffyan DOWN???

### ISSUE THREAD

**Issue by XXCryp70XX** [pystardust/ytfzf#549]
For those who are having an issue with scraping, because https://vid.puffyan.us seemed to be down at this moment hopefully soon they will fix the issue.

The issue: 
YouTube (with https://vid.puffyan.us) (s, pg: 1)
Youtube failed to load website
Nothing was scraped

![image](https://user-images.githubusercontent.com/94202188/176936613-7783c975-9951-4c59-a399-5c9f15934be5.png)

I got this result from a website:
![image](https://user-images.githubusercontent.com/94202188/176936911-4494b466-083c-4cfe-96bd-bdf76c673083.png)
![image](https://user-images.githubusercontent.com/94202188/176937156-02a50697-0a5d-43e3-b7b6-23198e160d95.png)

The site currently: 
![image](https://user-images.githubusercontent.com/94202188/176937223-43381964-a329-4991-9b34-0096358f313c.png)

**Comment by Euro20179** [comment]
You can always use a different instance other with the --ii option in 2.4 or in your config add `invidious_instance="https://instance"`

**Comment by Euro20179** [comment]
Should be fixed with #550
