### ISSUE TITLE
[Bug:] Wrong version number in release 2.4.0

### ISSUE THREAD

**Issue by Vouivre** [pystardust/ytfzf#551]
### Describe the bug

In the latest release (2.4.0) the displayed version number is wrong:

````
$ ytfzf --version
ytfzf: 2.4.0.rc-3 
````

Could you confirm that only the version number is wrong ? 

By packaging `ytfzf` I could simply correct the version number with sed.

**Comment by Euro20179** [comment]
I can confirm the version number is wrong

**Comment by Vouivre** [comment]
Thank you! I don't need a new release. I let you close this issue, perhaps you want to add a comment
on the release notes or something similar. This issue can be enough.

**Comment by Vouivre** [comment]
Thank you! I don't need a new release. I let you close this issue, perhaps you want to add a comment
on the release notes or something similar. This issue can be enough.
