### ISSUE TITLE
[Feature request]: Change dmenu Length

### ISSUE THREAD

**Issue by amarakon** [pystardust/ytfzf#554]
So by default the length of dmenu if you use the `-D` flag -s 30 (`dmenu -l 30`). That is too long for me because I usually like to have dmenu's length to be 10. I think there should be an option, like `--length`, which allows you to specify the dmenu length.

**Comment by Euro20179** [comment]
add 
```sh
external_menu () {
    tr -d '\t' | remove_ansi_escapes | dmenu -i -l 10 -p "$1"
}
```
to `~/.config/ytfzf/conf.sh`
replace `-l 10` with whatever you think is good

if you still want a `--length` option you can add the below segment instead.

```sh
external_menu () {
    tr -d '\t' | remove_ansi_escapes | dmenu -i -l "$config_dmenu_length" -p "$1"
}

on_opt_parse_length () {
    config_dmenu_length=$1
    return 1
}
```

Be warned that if a `--length` feature is added that does something different your config will overwrite it.
