### ISSUE TITLE
[BUG]: /usr/local/bin/ytfzf: 415: export: built on UNKNOWN: bad variable name

### ISSUE THREAD

**Issue by prakash2033** [pystardust/ytfzf#555]
### Describe the bug
After installation, when i run `ytfzf` for the first time, i get below error
```
/usr/local/bin/ytfzf: 415: export: built on UNKNOWN: bad variable name
```

### To Reproduce
`ytfzf test`

### Expected behavior
Show result of query

### Screenshots
![image](https://user-images.githubusercontent.com/9929306/179390898-5f482e00-34b0-44a1-b23a-8a91b4cfcad5.png)

### Information
 - OS:Pop!_OS 22.04 LTS
 - Terminal: xterm
 - Ytfzf version: Latest from github, can't verify since ytfzf do not show it
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):
![image](https://user-images.githubusercontent.com/9929306/179390969-295c3581-e771-48cf-a640-a62911e18efe.png)

**Comment by prakash2033** [comment]
It works fine when i switch to `development` branch and reinstall it. Looks like something wrong in `master` branch. Let me know if i shall close the bug anyway?
![image](https://user-images.githubusercontent.com/9929306/179391215-b1eaad50-3de3-4d20-8929-353de6b75788.png)

**Comment by Euro20179** [comment]
I tend to keep bugs repots opwn until its merged to master so we can leave it open

**Comment by stl3** [comment]
Gitbash 2.37.1, Win10
YTFZF_VERSION="2.4.0", master branch
``./ytfzf: line 415: export: `CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files': not a valid identifier``
``./ytfzf: line 415: export: `ProgramFiles(x86)=C:\Program Files (x86)': not a valid identifier``

**Comment by Euro20179** [comment]
Gitbash is not posix compliant, and therefore unsupported, however you can run `check_vars_exists=0 ytfzf ...` and it should work.
