### ISSUE TITLE
/usr/local/bin/ytfzf: 163: [: -ge: unexpected operator

### ISSUE THREAD

**Issue by brandon-devs** [pystardust/ytfzf#559]
Error message:
`/usr/local/bin/ytfzf: 163: [: -ge: unexpected operator`

Command run:
`ytfzf -t "linus tech tips"`

OS:
Void Linux

Terminal:
Void Terminal

Ytfzf version:
Most recent

Output of `ls -l "$(which sh)"`:
`lrwxrwxrwx 1 root root 4 Oct  6  2021 /bin/sh -> dash`

**Comment by Euro20179** [comment]
This is fixed in version `2.4.1`
