### ISSUE TITLE
[Feature request]: Pause functionality when running with -m option

### ISSUE THREAD

**Issue by chkhetiani** [pystardust/ytfzf#562]
### Background

[ ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
For users who use ytfzf for listening to music it would be nice to be able to pause and continue music when running ytfzf with -m option. 
Ex: When in meeting I want to pause 5 hour music video and don't want to restart it.

### Feature
Description of your proposed feature.
Eather hitting some key to pause and continue the music/video stream would be awesome.
Not sure if this is even possible to do in terminal (listen for the keys)

### Alternative solutions to problem?
Alternative but not perfect way would be possibility to start listening from given time stamp.

**Comment by Euro20179** [comment]
If youre using mpv as your player you can press space

**Comment by DestroyerAce** [comment]
@chkhetiani if you want to use media keys to control 
you can add this plugin https://github.com/hoyon/mpv-mpris 
its also available in most distro repos so you can easily install it
