### ISSUE TITLE
Double-quoted variables behave differently when containing long flags

### ISSUE THREAD

**Issue by tomhonour** [pystardust/ytfzf#564]
### Before Making This Post
[*] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?
I put the following code into a script and noticed that double-quoted variables behave differently with respect to flags:
```
#!/bin/bash
read a
ytfzf -tL "$a"
```
If I use `--upload-date=week example text` for `a`, the flag will only take effect if $a is used instead of "$a". In other words, double-quoting $a places the flag into the search - it ends up including '--upload-date=week' as part of the search term.

Is this a feature of bash, or should I create a bug report?

**Comment by Euro20179** [comment]
This is a feature of bash,

Each word separated by $IFS (whitespace by default) will be treated as a separate argument. If there are quotation marks, everything in the quotes will be treated as 1 argument.
