### ISSUE TITLE
How to play random vidoes from subscriptions list?

### ISSUE THREAD

**Issue by GasparVardanyan** [pystardust/ytfzf#565]
### Before Making This Post
* [+] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?

I want to have my music channels in ~/.config/ytfzf/subscriptions and to have ytfzf to randomely choose and play videos from my subscribed channels.

**Comment by Euro20179** [comment]
From `ytfzf(1)`
> -r, --random-select
>                     Auto-play a random result.

`ytfzf -cSI -r`

and if you want it to keep happening until you `ctrl-c` ytfzf use: `ytfzf -cSI -r -l`

**Comment by GasparVardanyan** [comment]
Thank you a lot, this tool is amazing !!
