### ISSUE TITLE
[BUG]: Provide other dependency than ueberzug to show Thumbnails for tty window terminals.

### ISSUE THREAD

**Issue by anshiq** [pystardust/ytfzf#566]
### Describe the bug
ytfzf works fine when I use GUI. I was using my Kali Linux 2022 without any GUI (X11). I use ytfzf to increase productivity. but it is not showing Thumbnails of the videos. The reason I got was ueberzug uses X11 to show the Thumbnails but ueberzug  not works on tty window terminals because of absence of x11. But also i have a solution: There is a terminal browser w3m It show Images on tty terminal please use the same dependency to show thumbnails on tty window for ytfzf.
### To Reproduce
If you are on gui use: sudo systemctl set-default multi-user.target
then, reboot the system.
on startup, now you gonna use your pc without gui on tty window terminals ,
now search any content using ytfzf you will not see any thumbnail thats bug I am discribing.
### Information
 - OS: Kali Linux 2022
 - Terminal: tty window (no gui terminal)
 - Ytfzf version: latest
- Output of `ls -l "$(which sh)"` (if your using fish: `ls -l (which sh)`):

### Additional context

https://user-images.githubusercontent.com/66484628/186337607-0da71df9-2b75-4d5b-a96c-9773815f6db2.mp4

**Comment by Euro20179** [comment]
You can copy https://github.com/pystardust/ytfzf/blob/master/addons/thumbnail-viewers/w3m to `~/.config/ytfzf/thumbnail-viewers/w3m` and then use `ytfzf --thumb-viewer=w3m` if you want w3m, however i don't recommend it because it's bad.
In my opinion you should use `ytfzf --thumb-viewer=chafa`

**Comment by anshiq** [comment]
ytfzf --thumb-viewer=mpv is the most fine working on tty window terminal. W3m, kitty and imv are not working and also other dependencies showing broken thumbnails. Mpv is most fine in case of tty window. For normal gui ytfzf is working so damm fine.
