### ISSUE TITLE
FOR window based system :(

### ISSUE THREAD

**Issue by omaru-ok** [pystardust/ytfzf#567]
### Background

[ ] its not available for window's nativly .

### Feature
for window X64 and installtion using scoop 
### Alternative solutions to problem?
:( please make it possible  for win 11 
i use terminal now day a lot

**Comment by Euro20179** [comment]
this has been discussed in #81,

in short use wsl

**Comment by omaru-ok** [comment]
crying moment coz window already sucks on resources . and ur saying to use wsl :(

**Comment by Euro20179** [comment]
I'm sorry, but I maintain this project for fun, maintaining a windows version does not sound fun, if you want to do it, or anyone else wants to do it, they are free to as per the GPL.

**Comment by omaru-ok** [comment]
okay thx
