### ISSUE TITLE
[Feature request]: medium video duration filter

### ISSUE THREAD

**Issue by Joseph65** [pystardust/ytfzf#569]
### Background

[ *] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
youtube and invidious added this search filter recently allowing us to finetune more the search results to the duration of 4-20 minutes
### Feature
Description of your proposed feature.
search results duration of 4-20 minutes

**Comment by Euro20179** [comment]
Correct me if I'm wrong, but i think you can just do, `ytfzf --video-duration=medium ...`
