### ISSUE TITLE
[Feature request]: Use Invidious API to select healthy instances

### ISSUE THREAD

**Issue by BSGalvan** [pystardust/ytfzf#570]
### Background

- [x] I have checked ytfzf(1) and ytfzf(5) and the wiki before creating this.

### Problem

Currently, there are three ways of controlling which Invidious instance is used by `ytfzf` to search for a given command-line query:

1. Using the `--ii` flag (`ytfzf(1)`)
2. Setting a user override for `invidious_instance` in `$XDG_CONFIG_HOME/ytfzf/conf.sh` (`ytfzf(5)`)
3. Changing the default instance [in the source code](https://github.com/pystardust/ytfzf/commit/0f5672c662d3856b2f1b7bb5b00ea90e680e8ed8)

The major issue with these methods is that if an instance faces downtime, users will have to _manually_ change the instance they use (or wait for hot-fixes). In the long term, this starts to become unsustainable.

Additionally, another minor issue with hard-coding an instance is that it loads that particular instance, as all users without additional configuration, will end up querying that instance every time.

### Feature
In order to solve this issue, I propose the following.
Following [libredirect](https://github.com/libredirect/libredirect)'s example, we can use the Invidious API to set a healthy instance. The process is as follows:

1. Get the list of healthy instances from the [Invidious API](api.invidious.io). This list should be cached to improve subsequent performance.
2. Parse the JSON file, and consider the top N(=10) healthy instances. Out of these N, select one at random (using `shuf()` or similar).
3. Set the value of `invidious_instance` to the value selected in 2.

Note: the `shuf()` call is simply to ensure that the load is distributed among the top N instances.

The above process then ensures that `ytfzf` auto-selects healthy instances. Additionally, we may want to refresh the cached file at some regular interval to ensure that it hasn't become stale.

### Alternative solutions to problem?
We could just carry on with making new commits whenever an instance seems to stop working, or let users make the decision of choosing a particular instance :man_shrugging: 

If this sounds like a feature that makes sense, please let me know, and I'd be happy to make a pull request!
Thanks for developing and maintaining such a wonderful piece of software :D

**Comment by Euro20179** [comment]
This is a great idea! I myself have had concerns over too many using the same instance, and instances going down, I just couldn't come up with a good solution.

Preferably it would be nice to keep a `--ii` option, and `invidious_instance` variable to override so that you can use your own instance (I have done this personally).

Feel free to make a pull request (please use development branch), however I am happy to do this myself.
