### ISSUE TITLE
[Feature request]:  Loop Feature for a particular listening song

### ISSUE THREAD

**Issue by PitamahBhishma-0** [pystardust/ytfzf#573]
### Background

[ ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
We need this feature if user wants to listen the particular song for more than one time, without exit of song. 

### Feature
I think adding a loop for a single music if user wants to listen more than once without searching next time without exit of that song will be awesome.

**Comment by Euro20179** [comment]
you can enable loop in mpv by pressing shift+l

**Comment by PitamahBhishma-0** [comment]
actually mpv is for video right if i am not wrong ? I wanted the loop while being in music mode .

**Comment by Euro20179** [comment]
mpv does both, you can press shift+l in music mode

**Comment by PitamahBhishma-0** [comment]
![image](https://user-images.githubusercontent.com/66584689/195229972-9061eab7-687b-4555-84be-8191f369d151.png)
After i clicked shit+I the part File appeared  music went on playing and exited after playing once.

**Comment by Euro20179** [comment]
it's shift L not shift I

**Comment by PitamahBhishma-0** [comment]
yoo bro thanks it worked, for this all time i was trying shift+I. LOL
