### ISSUE TITLE
[BUG]: some channels don't open in submenu

### ISSUE THREAD

**Issue by jaker-dotcom** [pystardust/ytfzf#581]
### Describe the bug
Some channels cannot be opened in submenu. Opening them directly via selecting the channel scraping does work.

### To Reproduce
ytfzf --type=all pewdiepie
select the channel to open it in submenu
\> yields videos of pewdiepie only
close
ytfzf --type=all visualpolitik
select the cannel to open it in submenu
\> search results are not related to previous search or selected channel
close
\ytfzf -c invidious-channel UCJQQVLyM6wtPleV4wFBK06g
\> yields videos of that channel only

### Expected behavior
No matter which channel is selected, it should list the videos of said channel in a new query.

### Screenshots
No screenshots but the output:
[user@host ]$ ytfzf --type=all visualpolitik                     
Scraping YouTube (with https://vid.puffyan.us) (visualpolitik, pg: 1)
Scraping YouTube (with https://vid.puffyan.us) (https://vid.puffyan.us/channel/UCJQQVLyM6wtPleV4wFBK06g, pg: 1)
[user@host ]$ ytfzf -c invidious-channel UCJQQVLyM6wtPleV4wFBK06g
UCJQQVLyM6wtPleV4wFBK06g/videos is not a scrapable link run:
/usr/bin/ytfzf --channel-link='UCJQQVLyM6wtPleV4wFBK06g/videos'
to fix this warning
Scraping Youtube (with https://vid.puffyan.us) channel: UCJQQVLyM6wtPleV4wFBK06g/videos (pg: 1)

### Information
 - OS: Manjaro Linux 
 - Terminal: Konsole
 - Ytfzf version: 2.3.1.rc-1
- Output of `ls -l "$(which sh)"`: lrwxrwxrwx 1 root root 4  9. Jan 2022  /usr/bin/sh -> bash

### Additional context
I tried with different channels too. It's not specific to the channel above. 
For the sake of creating this issue I also tested playlists. Most results are from the selected playlist but it also yields some unrelated results that are not from the playlist.
[user@host ]$ ytfzf --type=all it-trends the morpheus
Scraping YouTube (with https://vid.puffyan.us) (it-trends the morpheus, pg: 1)
Scraping YouTube (with https://vid.puffyan.us) (https://youtube.com/playlist?list=PL6RbeNL8jYDeDF3JO5EOKF6spjoSSbl5l, pg: 1)
\> yields mostly videos from playlist but also unrelated content

**Comment by Euro20179** [comment]
> ytfzf --type=all it-trends the morpheus
Scraping YouTube (with https://vid.puffyan.us/) (it-trends the morpheus, pg: 1)
Scraping YouTube (with https://vid.puffyan.us/) (https://youtube.com/playlist?list=PL6RbeNL8jYDeDF3JO5EOKF6spjoSSbl5l, pg: 1)

It seems that  it's not scraping the playlist, and instead is making a new query.
I was able to reproduce this in v2.3.1.rc-1 but not 2.5.0; Try updating ytfzf to version 2.5.0.

**Comment by jaker-dotcom** [comment]
didn't even notice I wasn't up to date. Weird that it wasn't updated via yay even though the AUR package is maintained. Well everything works like a charm now!
