### ISSUE TITLE
change resolution

### ISSUE THREAD

**Issue by Lunatic1985** [pystardust/ytfzf#582]
Hi, how do i change ytfzf resolution? (MPV) lets say 1080p60vp9, Thanks.

**Comment by Euro20179** [comment]
You can always use `-f`, or press `alt-f` when selecting a video (in fzf)

**Comment by Lunatic1985** [comment]
I understand, there is no permanent way to do it? before I used a config in mpv.conf and in bashrc but it doesn't work anymore...

**Comment by Euro20179** [comment]
This sounds out of sc

**Comment by Euro20179** [comment]
you can set ytdl_pref in your ytfzf config

**Comment by Lunatic1985** [comment]
I'm going to try, I need to create the config because I installed with Portage and I don't have one, thanks for answering.

**Comment by Lunatic1985** [comment]
I created the ytfzf config and it doesn't take the parameters, the same with the MPV config nothing happens and it keeps playing at the highest quality, alt-f -f doesn't give me results either, I think I'll look for another alternative  ;)

**Comment by Euro20179** [comment]
The most popular alternative I know of is [mps youtube](https://github.com/mps-youtube/mps-youtube), [this gui](https://github.com/FreeTubeApp/FreeTube) also exists.
I don't really know how good these are though because I just use this lol.
