### ISSUE TITLE
[BUG]: No fzf text when using ueberzug thumbnails (2.5.1 regression)

### ISSUE THREAD

**Issue by ionenwks** [pystardust/ytfzf#592]
### Describe the bug
```
ueberzug layer --parser json < "$UEBERZUG_FIFO"  &
exec 3> "$UEBERZUG_FIFO" > "$thumbnail_debug_log" 2>&1 # to keep the fifo open
```
Thumbnails display fine, but that is redirecting the output intended for fzf to the log file (aka exec is making the the entire script output ot this), maybe meant to have that on the line above?

### To Reproduce
`ytfzf -t test` with uberzug

### Information
 - OS: Gentoo
 - Terminal: kitty-0.26.4
 - Ytfzf version: 2.5.1
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): bash-5.2
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: the file contain

**Comment by Euro20179** [comment]
I did indeed mean to have this on the  line above...

A fix has been pushed to master,

This is a pretty major issue, should it get it's own release of `2.5.2`?, should I add a note to the  patch notes telling people to use a later commit, something else?

I'm leaning towards `2.5.2` but a second opinion is helpful.

**Comment by ionenwks** [comment]
Releases are cheap, especially for a shell script.

I've patched it but others offer a broken release without 2.5.2 so I'd say go for it.

**Comment by Euro20179** [comment]
Cool
