### ISSUE TITLE
Url-handlers not working

### ISSUE THREAD

**Issue by GhoulBoii** [pystardust/ytfzf#597]
### Before Making This Post
* [x] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?
I have set mpvq as my url-handler in my [conf.sh](https://0x0.st/oYQ0.sh) and when I try to play a video it gives me the following error: 

![image](https://user-images.githubusercontent.com/78494833/198880671-a73ca3aa-d13d-45e6-9355-dbb07fe7680c.png)

I get the same errors with other url-handlers as well.

This is my ~/.config/ytfzf directory structure: [dir.txt](https://0x0.st/oYQ7.txt)

**Comment by Euro20179** [comment]
in your config use `load_url_handler mpvq`, I should probably make this more clear in the docs.

if you set url_handler directly, its going to try to run the command `mpvq`, so another option is to set url_handler to the absolute file path, as thats essentially what load_url_handler does

**Comment by GhoulBoii** [comment]
Works correctly now! Thanks for the help. Would be helpful if you can change it in the docs section so future readers won't make the same mistake.

**Comment by Euro20179** [comment]
> Would be helpful if you can change it in the docs section 

Yep I've done that, I have not pushed it to development yet though.
