### ISSUE TITLE
[BUG]: searching all subscriptions sometimes returns inconsistent and incomplete list of videos

### ISSUE THREAD

**Issue by kevenwyld** [pystardust/ytfzf#598]
### Describe the bug

When running `ytfzf -c SI` and a list of 12 youtube channels in `.config/ytfzf/subscriptions` I find that running the command repeatedly will return different results each time.  Often missing content from one or two of the subscriptions.

### To Reproduce

Add 12 ish channels to `.config/ytfzf/subscriptions` and run `ytfzf -c SI`

### Expected behavior

Command should return the same results each time

### Screenshots

Here's are two videos.  In the first I left the default random instance option enabled.  In the second it is locked to a specific one.  The behavior is the same if I set a specific instance using `invidious_instance=<instance_url>`.  So I suspect it's not a problem with inconsistent data from the instances.

With random instances enabled:

https://user-images.githubusercontent.com/11936535/198902469-fe0304e2-b07b-44c3-814d-4a55c648f6f6.mp4

With single instance:

https://user-images.githubusercontent.com/11936535/198902540-75903a5e-abb4-4bfc-884c-ff909c9113b5.mp4

I went pretty fast assuming you could just pause the video to read the list.

### Information
 - OS: Archlinux
 - Terminal: Alacritty
 - Ytfzf version: ytfzf: 2.5.2 (AUR git package built today)
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
```
    ] > ls -l (which sh)
    lrwxrwxrwx 1 root root 4 Jan  8  2022 /usr/sbin/sh -> bash*
```
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: Not a thumbnail issue.

### Additional context

As stated above, this happens even if I lock a single instance using `invidious_instance=<instance_name>` in the conf.sh file.

Here's the contents of the subscriptions file:

```
https://www.youtube.com/channel/UC4PIO2pZaFKzI97uumFTNSg/videos
https://www.youtube.com/channel/UCeKpbMimEGgLM_0tnghfoVw/videos
https://www.youtube.com/channel/UC7pokUsRb6q2B0FOzSqQLlw/videos
https://www.youtube.com/channel/UCw3UZn1tcVe7pH3R6C3Gcng/videos
https://www.youtube.com/channel/UCCkSr3M8GXbS4txqPY7OMxQ/videos
https://www.youtube.com/channel/UC7Jf7t6BL4e74O53dL6arSw/videos
https://www.youtube.com/channel/UCY8gSLTqvs38bR9X061jFWw/videos
https://www.youtube.com/channel/UC-CubOaooNwC-3RBKUoAOQQ/videos
https://www.youtube.com/channel/UC7aAyIrjeH2RKciAXzdOaJA/videos
https://www.youtube.com/channel/UCKLIIdKEpjAnn8E76KP7sQg/videos
https://www.youtube.com/channel/UCyjwQ6oz4cqqtEcWGboSU3g/videos
https://www.youtube.com/channel/UChIs72whgZI9w6d6FhwGGHA/videos
```

I have the following other configuration in my conf.sh file:

```
thumbnail_quality='high'
is_sort=1
url_handler_opts='--save-position-on-quit'
```

**Comment by Euro20179** [comment]
The results do seem to be inconsistent.

Until this is fixed, feel free to use `-c S` to scrape youtube directly instead of invidious.

**Comment by kevenwyld** [comment]
@Euro20179 thanks.  In fact the problem is still present with `-c S`.  See the video:


https://user-images.githubusercontent.com/11936535/198908502-3e40cf47-b363-40aa-9340-82bde720be8b.mp4

**Comment by Euro20179** [comment]
Interesting, i'll have to do somem tests with a small sub file.

**Comment by Euro20179** [comment]
I believe this is simply a case of sending too any requests to servers..

To prevent this i'm going to implement the thread system, then you can use `--max-threads=10` or something, and it should be more consistent (still not great, but i think that's out of my control?)

In addition I'm planning on adding some option to only read the first n lines of the subscriptions file, then in fzf you can press alt-p to scrape n more pages.

**Comment by Euro20179** [comment]
try `-cS` on the latest commit to the development branch. (-cSI is still broken)

I believe the problem was that the way youtube is scraped was broken.

**Comment by kevenwyld** [comment]
@Euro20179 Thanks!  `-cS` is working very well now.  The results are the same every time.

**Comment by Euro20179** [comment]
Interesting, I believe the problem, then is with invidious, as both `-cS` `-cSI` broke completely at the same time for me, so I believe that invidious will also have to fix this bug, I could be wrong though.

**Comment by Euro20179** [comment]
[this](https://github.com/iv-org/invidious/issues/3378) may be the problem.

**Comment by Euro20179** [comment]
[this](https://github.com/iv-org/invidious/commit/09942dee6621e7047a63dffcc61b3bbf78cef2c6) commit seems to fix `-cSI` if the invidious instance has updated to it.

**Comment by kevenwyld** [comment]
Thanks, yes it does and I'm getting consistent results from the instances that have updated (some are still not responding but I suspect they don't all automatically pull updates right away).

I think we can close this.  Thanks for your help, and for all your work on this project!
