### ISSUE TITLE
[BUG]: Permission error with multiple users sharing /tmp

### ISSUE THREAD

**Issue by zeitgenosse** [pystardust/ytfzf#599]
### Describe the bug

ytfzf run as user2 fails to create files in /tmp if these files already exist, owned by user1. 

### To Reproduce

Login as user1 over ssh, use ytfzf to watch a video (it will fail). It produces the files `/tmp/ytfzf-env` and `/tmp/the-job-needs-to-be-written-to-a-file.list` with permissions mask 755 and owned by user1. 

Login as user2 locally. Start ytfzf to do a search query. It will fail:

```
/usr/bin/ytfzf: 508: cannot create /tmp/ytfzf-env: Permission denied
/usr/bin/ytfzf: 236: cannot create /tmp/the-jobs-need-to-be-written-to-a-file.list: Permission denied
```

### Expected behavior

Two different users should be able to use ytfzf on the same computer. More specifically: A user doesn't try to overwrite another user's files in /tmp. 

### Information
 - OS: Debian testing
 - Terminal: 
 - Ytfzf version: 2.5.0 (Debian)

**Comment by Euro20179** [comment]
This should be fixed in  the development branch, i'm not 100% positive because i can't really recreate it,

However i was able to run ytfzf with 2 users at the same time with no errors.
