### ISSUE TITLE
Automatically play first result

### ISSUE THREAD

**Issue by cybarspace** [pystardust/ytfzf#6]
Hello there. This is a real nice script, but I'd like to have it play the first result automatically without me needing to press enter (assume that I'm satisfied with the first result, regardless of accuracy). Can this be done currently via flags (I don't see it in the docs) or via some shell syntax magic? If so then could you please let me know how?

I only tried `ytfz -m <search-query> <<< printf "\n"` and that didn't work (I thought it'd automatically press Enter after search).

PS: I use `zsh` but I have `bash` installed for scripts, so either syntax suggestion is welcome. Thank you.

**Comment by pystardust** [comment]
I added -a flag for autoplaing the first result.
I don't think fzf takes input that way.  
Option -a will not prompt and auto play the first result. It can be combined with the rest flags.
I will make sure every component is posix complaint so you need not worry.

**Comment by pystardust** [comment]
@cybarspace is this is fine?

**Comment by cybarspace** [comment]
@pystardust Yes! Thanks a lot. :blush:
This is exactly what I was looking for.

Here's what I was trying to do originally:

![image](https://user-images.githubusercontent.com/50134239/108621066-a0e25c00-745a-11eb-8a3e-b70a11e9bc7d.png)

Basically, a kind of music playing REPL that sources from YouTube. Thanks for the prompt solution.
