### ISSUE TITLE
[BUG]: One(?) of the latest 4 commits breaks scraping subscriptions

### ISSUE THREAD

**Issue by manfred3000** [pystardust/ytfzf#606]
### Describe the bug
Issuing `ytfzf -c youtube-subscriptions` built with the latest 4 commits  gives me `Nothing was scraped`
### To Reproduce
See above. Using a previous build `(r1747.6250193-1)` fixes the issue.
### Expected behavior
Subscriptions get scraped without issues.
### Information
 - OS: Arch Linux
 - Terminal: `foot`
 - Ytfzf version: `r1751.9c9b03e-1` (`ytfzf-git` from the AUR)
- Output of `ls -l "$(which sh)"`: `lrwxrwxrwx 1 root root 4  8. Jan 2022  /usr/bin/sh -> bash`

**Comment by Euro20179** [comment]
What kind of channel links are you using in your subscription file?

example: `https://www.youtube.com/user/<channel>/videos`

**Comment by manfred3000** [comment]
I'm using `https://www.youtube.com/channel/UC**********etc*********`
