### ISSUE TITLE
[BUG]: Can't scrape subscriptions

### ISSUE THREAD

**Issue by TomoBossi** [pystardust/ytfzf#607]
### Describe the bug
The "ytfzf -c youtube-subscriptions" command shows that the channels in my subscriptions file are being read correctly, but after the script goes through the whole list I get the error message "Nothing was scraped"

### Screenshots
![image](https://user-images.githubusercontent.com/62483708/203889788-edf1c0f9-3801-4034-b325-e9c3f0bc2020.png)

### Information
 - OS: EndeavourOS
 - Terminal: xfce4-terminal
 - Ytfzf version: 2.5.2
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): lrwxrwxrwx 1 root root 4 ene  8  2022 /usr/bin/sh -> bash

**Comment by Euro20179** [comment]
Using `-c S` in 2.5.2 is broken, upgrade to the development branch or use `-c SI`
