### ISSUE TITLE
Heads up on ueberzug

### ISSUE THREAD

**Issue by tomhonour** [pystardust/ytfzf#608]
Ueberzug is no longer being maintained:
[https://github.com/seebye/ueberzug](https://github.com/seebye/ueberzug)

[This video describes what happened](https://redirect.invidious.io/watch?v=9G9bf5i7Im8)

**Comment by Euro20179** [comment]
I have seen that, however there are no real alternatives for xorg, and it should continue to work anyway If it stops working for some reason, I might look for alternatives

**Comment by ionenwks** [comment]
ftr a (hopefully) serious-looking fork released ueberzug-18.2.0 with fixes not long ago (not just a backup of the old repo), and seems to work fine with ytfzf still

https://github.com/ueber-devel/ueberzug/
