### ISSUE TITLE
[BUG]: preview gets stuck when selecting multiple videos

### ISSUE THREAD

**Issue by 2084x** [pystardust/ytfzf#612]
### Describe the bug
When using tab to select multiple videos, the preview gets stuck on the first selection.

### To Reproduce
1. `ytfzf -t yoursearchhere`.
2. Select a video with tab.
3. Keep scrolling and see the preview no longer changes.

### Expected behavior
The preview should continue to follow the cursor after a selection is made with tab.

### Screenshots
[2022-12-15 09-15-06 - [00.01.833-00.16.000]-audio.webm](https://user-images.githubusercontent.com/108906685/207728291-c5859a01-5362-4551-8507-5f9b6e0fb7a3.webm)

### Information
 - OS: arch linux
 - Terminal: st
 - Ytfzf version: 2.5.3-1
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

### Additional context
my conf:
```sh
pages_to_scrape=1
sub_link_count=5
show_thumbnails=1
async_thumbnails=1
url_handler_opts="--force-window=yes"
```
the alias I use to make searches:
```sh
yts="ytfzf --type=all --thumbnail-quality=sddefault" 
```

**Comment by Euro20179** [comment]
This has been fixed in [this](https://github.com/pystardust/ytfzf/commit/bfad45f900f9e71a14ee4823e2df75c30d2cc9c2) commit.

**Comment by 2084x** [comment]
Thankyou!
