### ISSUE TITLE
[Feature request]: support chafa-sixel

### ISSUE THREAD

**Issue by rihaq** [pystardust/ytfzf#614]
### Background

[ ] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
Best quality image and not pixilated 
### Feature
Description of your proposed feature.
`chafa --format sixel`
### Alternative solutions to problem?
img2sixel

**Comment by Euro20179** [comment]
This cannot be done because fzf does not support sixel.

**Comment by rihaq** [comment]
[Why Isn't it Possible？ It's just not. [coY2IA-oBvw].webm](https://user-images.githubusercontent.com/93857023/209288795-e51c4283-ab0c-4840-8115-9d16a80eaafc.webm)

**Comment by Euro20179** [comment]
There is an issue on the fzf page about implementing sixel, but no one wants to do it, which is perfectly reasonable as sixel is fairly complicated.

**Comment by rihaq** [comment]
> There is an issue on the fzf page about implementing sixel, but no one wants to do it, which is perfectly reasonable as sixel is fairly complicated.

Ayo, kittyTard
