### ISSUE TITLE
[Feature request]: support mpv sixel

### ISSUE THREAD

**Issue by rihaq** [pystardust/ytfzf#615]
### Background

[x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
Watch video in terminal
### Feature
Description of your proposed feature.
`mpv.--vo=sixel`

**Comment by Euro20179** [comment]
add `url_handler_opts="--vo=sixel"` to ~/.config/ytfzf/conf.sh
