### ISSUE TITLE
[Feature request]:  export subs videos to html file

### ISSUE THREAD

**Issue by Joseph65** [pystardust/ytfzf#616]
### Background

[ *] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
would be nice for archiving the subs videos in a html file

### Feature
Description of your proposed feature.
export subscriptions videos to a html file for archiving and history of the channel sorting from newest to oldest uploaded video

**Comment by Euro20179** [comment]
This can be done in an external script, I was bored so I wrote said script, if you don't like it, then feel free to change it.
```sh
#!/bin/sh

cache_dir="./ytfzf-cache"

links="$(cache_dir="$cache_dir" YTFZF_CONFIG_FILE=/dev/null ytfzf --sort -AL --keep-cache "$@")"

session_cache_dir="$(echo "$cache_dir"/hi-*)"

command -v youtube-dl > /dev/null 2>&1 && youtube_dl="youtube-dl" || youtube_dl="yt-dlp"

mkdir website
mkdir website/videos

while read -r link; do
    data="$(jq -r --arg url "$link" '.[]|select(.url==$url)' < "${session_cache_dir}/videos_json")"
    title="$(printf "%s" "$data" | jq -r '.title')"

    $youtube_dl --remux-video "webm" "$link" -o "website/videos/$title"

    echo "<h2>$title</h2><br><video height=\"300px\" controls src=\"./videos/$title.webm\"></video><br>" >> "./website/index.html"

done <<-EOF
    $links
EOF

rm -rf "$session_cache_dir"
```

if you run the script with `-cSI` it will archive your subscription videos and make a website with them.
