### ISSUE TITLE
[BUG]: --channel-link doesn't work on all links

### ISSUE THREAD

**Issue by rEnr3n** [pystardust/ytfzf#617]
### Describe the bug
Issue is the same with #600 but the link given there works for me.
```
$ ytfzf --channel-link="https://www.youtube.com/c/SomeOrdinaryGamers"
https://www.youtube.com/channel/UCtMVHI3AJD4Qk4hcbZnI9ZQ
```

Some links print out the channel id. Some don't.

### To Reproduce
```
$ ytfzf --channel-link="https://www.youtube.com/c/christianlempa"
https://www.youtube.com/c/christianlempa
```

### Expected behavior
```
$ ytfzf --channel-link="https://www.youtube.com/c/christianlempa"
https://www.youtube.com/channel/UCZNhwA1B5YqiY1nLzmM0ZRg
```

### Information
 - OS: Arch Linux
 - Terminal: Alacritty
 - Ytfzf version: ytfzf: git-1824.8bcae1b
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
```
lrwxrwxrwx 1 root root 4 Jan  9  2022 /usr/sbin/sh -> bash
```
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

**Comment by Euro20179** [comment]
The example you gave appears to be intended behavior, the page `https://www.youtube.com/c/christianlempa` does not exist, so --channel-link wont work.

**Comment by rEnr3n** [comment]
Sorry I forgot to check. I assumed it was universal.
