### ISSUE TITLE
[BUG]: mpvq stopped working

### ISSUE THREAD

**Issue by GhoulBoii** [pystardust/ytfzf#618]
### Describe the bug

mpvq is not working properly. This has been happening for the past couple of days. I tried different url handlers and they seem to work properly, just not mpvq. 

### To Reproduce

1. run `ytfzf --detach -u mpvq penguinz0`
2. the video opens normally
3. run `ytfzf --detach -u mpvq hello`
4. the video opens in a separate window and does not get queued

### Expected behavior

The second video should get queued rather than open in a separate window

### Screenshots

![image](https://user-images.githubusercontent.com/78494833/210201228-9db9432c-a943-4a15-989b-cce405bafa96.png)

### Information
 - OS: Arch Linux
 - Terminal: st
 - Ytfzf version: 2.5.3
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): lrwxrwxrwx 4 root  9 Jan  2022 /usr/bin/sh -> bash
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

**Comment by Euro20179** [comment]
I can't seem to replicate this, have you changed anything, or has anything changed in the past couple of days?

**Comment by GhoulBoii** [comment]
Not really sure. I change stuff daily but do not think that I changed anything related to ytfzf and mpv.

**Comment by Euro20179** [comment]
try, `ytfzf --detach -l -u mpvq some-search` and opening multiple videos from that menu.


Running multiple ytfzf commands will open multiple windows.

**Comment by GhoulBoii** [comment]
Tried the command and it still opens multiple videos for each link and does not queue them.

**Comment by Euro20179** [comment]
Not sure then, try using the development branch, as I'm out of ideas.

**Comment by GhoulBoii** [comment]
Tried the development branch as well and same issue. Yes, ``socat`` is installed.

**Comment by Euro20179** [comment]
I'm out of ideas then for now at least.

**Comment by GhoulBoii** [comment]
I have found the issue. The mpvq script requires ``lsof`` which I think I accidentally removed from my system. Reinstalling it makes the script work again. Can I suggest making a dependencies list at the top of each of the addons script so it is useful to know which dependencies to have installed? If you are not interested in doing so, I can make a PR for it.

**Comment by Euro20179** [comment]
>  The mpvq script requires lsof

Nice catch! I didn't realize it required that.

> Can I suggest making a dependencies list at the top of each of the addons script

I'll look through them and see which do not have it.

**Comment by Euro20179** [comment]
pushed it here: b9ffa375139543b14debeb31eb0e68c03e013ad6, I don't think I missed any.

**Comment by GhoulBoii** [comment]
Thanks for the quick fix. Looks like everything is account for in the dependencies. Have a good day!
