### ISSUE TITLE
[Feature request]: Keep position of selector in loop mode after video finishes

### ISSUE THREAD

**Issue by n8x0b7T** [pystardust/ytfzf#619]
### 
- [x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
The selector returns to the top of the list when in loop mode after the video exits.

```
 -l, --loop
    Reopen the menu when the video stops playing. This can also be set in the config file with is_loop.
```

### Feature
It would be best if the program saved the id of the last opened video (perhaps in a global variable), then re-selects it when the video closes. This probably ought to be the default, but it could also be added as a separate option

**Comment by Euro20179** [comment]
This is quite funny because I was working on this exact feature today, where when you press ctrl-e it saves the position, but enter selects normally. I'll try again but make it so that Enter saves position. (note that this would not work in external menus)

**Comment by Euro20179** [comment]
I have pushed this to the development branch, feel free to try it.

**Comment by n8x0b7T** [comment]
Thanks for the update! I have updated to `ytfzf: 2.5.4.rc-1`. I can't seem to get the location saving feature to work. Is there an extra option I need to set?

**Comment by Euro20179** [comment]
Ah, it seems that it's broken with thumbnails, try it without thumbnails.

**Comment by n8x0b7T** [comment]
I see that it is working with thumbnails now, but instead of keeping the spot, I believe it's jumping down by an entire page. Any idea what could be causing that?

**Comment by Euro20179** [comment]
When my window is small it puts the cursor at the bottom but jumps to the correct position. Other than that I'm not sure.

**Comment by n8x0b7T** [comment]
On my install, it seems to jump down by an arbitrary interval every time. Maybe the offset it somehow adding up every time and it might also be off by one

**Comment by Euro20179** [comment]
What version of `jq` do you have? Also, what is the output of `ls -l $(which sh)`?

**Comment by n8x0b7T** [comment]
My `jq` version is `jq-1.6`. My `sh` version is `GNU bash, version 5.1.16(1)-release`.

**Comment by Euro20179** [comment]
What does your config file look like, if you have one?

**Comment by n8x0b7T** [comment]
I'm not using a config file. I figured out the problem goes away when I don't use the `--sort` option.

**Comment by Euro20179** [comment]
> I figured out the problem goes away when I don't use the --sort option.


This is a good hint, I'll look into this, never tried this myself with the `--sort` option.

**Comment by Euro20179** [comment]
Should be fixed.

**Comment by n8x0b7T** [comment]
Thank you!
This feature works great now.
