### ISSUE TITLE
FIX: bash - hist and current files

### ISSUE THREAD

**Issue by nycko123** [pystardust/ytfzf#63]
Line 352, doesn't parse "\n"s which results in exporting empty lines to ytfzf_hst ytfzf_cur
`selected_data="$(echo "$selected_data" | sed 1d )"`

Working (in both dash and bash under linux) solution is to change the 'echo' to 'printf' OR to use 'echo -e' whenever backslash escapes need to be parsed.

**Comment by pystardust** [comment]
Thanks ill fix it immediately

**Comment by pystardust** [comment]
I fixed it as you mentioned and testing it with bash. 
Let me know if you the problem persists.

**Comment by nycko123** [comment]
Works good. Problem fixed, thanks.
