### ISSUE TITLE
[BUG]: Thumbnails not displaying after update

### ISSUE THREAD

**Issue by 2084x** [pystardust/ytfzf#632]
### Describe the bug
After the most recent update thumbnails don't display and instead `/usr/bin/ytfzf: line 2519: : No such file or directory` is printed.
### To Reproduce
ytfzf -t yoursearchhere
### Expected behavior
Thumbnails show just as they did before
### Screenshots
![pic-selected-230117-1929-12](https://user-images.githubusercontent.com/108906685/212847296-4e66f181-9dde-4a0a-9d73-7781749bc58b.png)

### Information
 - OS: arch linux
 - Terminal: st
 - Ytfzf version: 2.5.4
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): zsh
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: file is empty

### Additional context
Thumbnails are still being downloaded just fine and I can see ueberzug running in htop when the menu is opened.
![pic-selected-230117-1928-54](https://user-images.githubusercontent.com/108906685/212847473-ebd9be24-5b8c-4ce1-9b5f-211011324507.png)

**Comment by Euro20179** [comment]
> zsh

This is not the output of  `ls -l "$(which sh)"` because for me `zsh` straight up doesn't work with ytfzf on the newest version.
But if for some reason this is what `/bin/sh` is linked to, `zsh`, and does work, it is unsupported anyway, so use a different shell.

Either way it seems that the ueberzug thumbnail viewer is broken, because this bug only happens when i use the ueberzug viewer.

**Comment by 2084x** [comment]
> This is not the output

sorry output is: `lrwxrwxrwx 1 root root 4 Jan  9  2022 /usr/bin/sh -> bash`

> the fix has been pushed to the development branch.

Thankyou, thumbnails work again.

**Comment by Euro20179** [comment]
> sorry output is: lrwxrwxrwx 1 root root 4 Jan 9 2022 /usr/bin/sh -> bash

All good.

> thumbnails work again.

Excellent.

Im hoping to release 2.5.5 in a week or 2 because this is somewhat of a major bug.

**Comment by manfred3000** [comment]
- OS: Arch Linux
 - Terminal: `foot`
 - Ytfzf version: ytfzf-git-r1860.42ed7d6-1
- Output of `ls -l "$(which sh)"`: `lrwxrwxrwx 1 root root 4  8. Jan 2022  /usr/bin/sh -> bash`

Unfortunately for me this issue is still present with the latest commit and using `chafa` as thumbviewer...

**Comment by Euro20179** [comment]
>  ytfzf-git-r1860.42ed7d6-1

This is a very strange version, update to either 2.5.4, or to the latest commit.

**Comment by manfred3000** [comment]
> > ytfzf-git-r1860.42ed7d6-1
> 
> This is a very strange version, update to either 2.5.4, or to the latest commit.

Copy-pasta fail:
```
~ ❯ pacman -Q ytfzf-git                                                                               [0] 21:49
ytfzf-git r1880.734778b-1
```
No thumbnails using `chafa`.

**Comment by Euro20179** [comment]
I am also using `ytfzf-git` on the latest version with foot, and chafa and cannot reproduce the issue.
Are there any errors?

**Comment by manfred3000** [comment]
I've tried on two different machines and version 2.5.4 as well - no thumbnails and no error output. Using e.g. `mpv` is working fine...

**Comment by Euro20179** [comment]
> EDIT#2: Disabling firejail 'solves' the issue - sorry for the noise. Stupid coincidence...

Interesting, I'm not sure why that would happen, unless ytfzf is run under filejail or filejail is managing the `/tmp` folder.

**Comment by manfred3000** [comment]
> > EDIT#2: Disabling firejail 'solves' the issue - sorry for the noise. Stupid coincidence...
> 
> Interesting, I'm not sure why that would happen, unless ytfzf is run under filejail or filejail is managing the `/tmp` folder.

Yep, I created `$HOME/.config/firejail/chafa.local` with the following line:
`whitelist /tmp/ytfzf-1000/*` and now we're playing ball again...
Thanks!

**Comment by Euro20179** [comment]
nice!

**Comment by marshallishere** [comment]
I'm having the same issue, but I'm not using firejail. I updated ytfzf and got this error:

![Captura de tela de 2023-01-22 14-05-53](https://user-images.githubusercontent.com/110747746/213929438-a44b638d-43c7-40f7-815f-18dfbc512a64.png)

It happens with all the videos.

I'm using foot terminal with chafa on Fedora Workstation. My config file is this:
```
invidious_instance='https://invidious.weblibre.org'
pages_to_scrape=5
ytdl_pref="((bestvideo[height<=?1080][fps<=?60][vcodec^=vp9]/bestvideo[height<=?1080][fps<=?60])+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
log_level=1
fzf_preview_side=right
show_thumbnails=1
search_region=BR
load_thumbnail_viewer chafa
load_interface custom
```
