### ISSUE TITLE
Is there a way to select multiple results to be played one after another?

### ISSUE THREAD

**Issue by ZaxonXP** [pystardust/ytfzf#633]
As in the subject, Is there a way to select more than one results to be played one after another?

Regards,
Piotr

**Comment by jaker-dotcom** [comment]
Hey there,
in fzf you can choose multiple options with tab. ytfzf uses fzf to select the videos.
You probably can choose the key in the fzf config, if desired.

Kind regards,
Jaker

**Comment by ZaxonXP** [comment]
It works. Thanks!
