### ISSUE TITLE
[BUG]: Cannot scrape youtube (unknown action: reload)

### ISSUE THREAD

**Issue by ubmarco** [pystardust/ytfzf#634]
### Describe the bug

Cannot scrape YouTube due to an error.

### To Reproduce
```
$ ytfzf -l 'soymartino'
Scraping YouTube (with https://invidious.dhusch.de) (soymartino, pg: 1)
unknown action: reload(__is_fzf_preview=1 YTFZF_CHECK_VARS_EXISTS=1 session_cache_dir='/tmp/ytfzf-1002/soymartino-79868' session_temp_dir='/tmp/ytfzf-1002/soymartino-79868/tmp' /usr/sbin/ytfzf -W "next_page{f}")
```
### Expected behavior

List of scraped items appears.

### Information
 - OS: 6.0.19-3-MANJARO
 - Terminal: xfce4-terminal with ZSH
 - Ytfzf version: 2.5.4
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): `lrwxrwxrwx 1 root root 4  9. Jan 2022  /usr/sbin/sh -> bash`
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:
- fzf version: 0.17.4 (f0fe79d)

**Comment by Euro20179** [comment]
update fzf, im on version 0.37

**Comment by ubmarco** [comment]
Oh thanks for this hint. It works now.
I already checked my version when writing this issue and pacman said it is up-to-date (`fzf-0.35.1-1`).
However there was an old version installed to `/usr/local/bin/fzf` which took precedence.
Presumably an install script that did something non-standard in the past.
Anyway, thanks again for the help.
