### ISSUE TITLE
error when using -t option

### ISSUE THREAD

**Issue by powerhousepro69** [pystardust/ytfzf#65]
I am getting the following error when using  the -t option

ytfzf -t funny
Downloading Thumbnails................................
invalid preview window layout: left:50%:noborder:wrap

I tried it in mate-terminal and guake.    Same error

thank you for taking a moment to read this.

**Comment by Euro20179** [comment]
what version of fzf do you have

**Comment by pystardust** [comment]
Which OS are you using? Some versions of fzf don't support some options. We can try changing it to make it compatible

**Comment by powerhousepro69** [comment]
fzf --version 0.17.5

Linux Mint Mate v19.1

**Comment by JojiiOfficial** [comment]
You should probably upgrade to a newer version. On arch it is 0.25.1

**Comment by Euro20179** [comment]
I'm running Linux Mint 20.1, i don't really know how package updating works, but i'm running fzf 0.20.0 so maybe you can update fzf

**Comment by JojiiOfficial** [comment]
`apt update && apt upgrade` should do it.

**Comment by powerhousepro69** [comment]
Version 0.17.5 was still in the repo.

I downloaded fzf  v.0.25.1 from github.
It now works perfectly.

Thanks again.  I appreciate your time.
Nice Code!    👍️
