### ISSUE TITLE
[BUG]: No audio for certain video files

### ISSUE THREAD

**Issue by hectorBrown** [pystardust/ytfzf#657]
### Describe the bug
On selecting certain video files, the video plays but with no audio content. Other videos behave normally.
### To Reproduce
`ytfzf car crash interrupts podcast` finds [this video](https://www.youtube.com/watch?v=virDyRJdsLk) in the results. On selection, an error:
```
Scraping YouTube (with https://invidious.sethforprivacy.com) (car crash podcast, pg: 1)
[ytdl_hook] EDL doesn't support fragmentswithout duration with MP4 DASH 
EDL specifies no segments.'
EDL parsing failed.
Error in EDL.
EDL: source file 'edl://!mp4_dash,init=%907%https://rr4---sn-8vq54vox03-aigs.googlevideo.com/videoplayback?expire=1678175315&ei=85cGZMuaBJWD0wXUhbboCQ&ip=87.75.165.153&id=o-ANq8fDKBwvaAC3CisGx-FCtkZDEwPK9G6NEOqcmI0oYW&itag=140&source=youtube&requiressl=yes&mh=Su&mm=31%2C29&mn=sn-8vq54vox03-aigs%2Csn-aigzrnld&ms=au%2Crdu&mv=m&mvi=4&pl=20&initcwndbps=1792500&vprv=1&mime=audio%2Fmp4&ns=1hOMTl-iefW390O5kHo5hHkL&gir=yes&clen=3516368&dur=217.199&lmt=1678132672704562&mt=1678153496&fvip=2&keepalive=yes&fexp=24007246&c=WEB&txp=3318224&n=yPwJxPijhRDvbw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOOLaWH8pEZJZMC9QTd3GftztNvWUL5wWEjnIBwczSsWAiAG94zK8eH1oHpl9jj4pTwLoK4DcKXTtxLKIPZcHMwhvw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgY2MCmRJz4l9dMUFz-yu_agimZ613jTu-teQPVsqlMcICIQC8WqtGu_y8_RdE42PlLJVLsNs7LTlFnMHQ7_Q8m2Q2SQ%3D%3D&range=0-3516368;' has unknown duration.
 (+) Video --vid=1 (*) (h264 1920x1080 59.940fps)
File tags:
 Uploader: Daily Dose Of Internet
 Channel_URL: https://www.youtube.com/channel/UCdC0An4ZPNr_YiFiYoVbwaw
VO: [gpu] 1920x1080 yuv420p
V: 00:00:01 / 00:03:37 (1%) Cache: 6.2s/1MB
```
occurs and the video plays without audio.
### Expected behavior
The video should play normally.
### Screenshots
N/A
### Information
 - OS: Arch Linux on 6.1.15-1-lts
 - Terminal: kitty 0.27.1
 - Ytfzf version: 2.5.5
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`):
`lrwxrwxrwx 1 root root 4 Feb  2 06:38 /sbin/sh -> bash`
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: N/A

### Additional context
N/A

**Comment by Euro20179** [comment]
I am also having this issue however I do not believe it is a problem with ytfzf,

Opening the video with `mpv` directly gives the same error.

**Comment by hectorBrown** [comment]
Yeah, actually found [this](https://github.com/mpv-player/mpv/issues/11392) soon after posting.

**Comment by oraimagini** [comment]
ERROR Version: 
MPV 0.35.1 
YTFZF 2.3 
---> YT-DLP 2023.03.04

I had the same problem and I solved this, I made a downgrade: 
yt-dlp --update-to stable@2023.02.17
