### ISSUE TITLE
[BUG]: `ytdl_opts="-o ~/Videos/%(title)s.%(ext)s"` output the video to `/home/username/ ~/Videos/`

### ISSUE THREAD

**Issue by kohane27** [pystardust/ytfzf#658]
### Describe the bug

`ytdl_opts="-o ~/Videos/%(title)s.%(ext)s"` output the video to `/home/username/ ~/Videos/`

Hello there! Hope you're doing well. I realized that `ytdl_opts` no longer works. Video is downloaded to `/home/username/ ~/Videos/` (i.e., a `~/` in the home directory is created)

### To Reproduce

To reproduce:
1. `~/.config/ytfzf/conf.sh`:

```bash
#!/bin/sh
ytdl_pref="bv*[height<=1200]+ba/b[width<2000] / wv*+ba/w"
ytdl_opts="-o ~/Videos/%(title)s.%(ext)s"
thumbnail_viewer=swayimg
show_thumbnails=1
async_thumbnails=1
fzf_preview_side=down
```

2. Use the command `ytfzf --show-thumbnails --download "lofi beats"`
3. Output:
```
➜  ytfzf --show-thumbnails --download "lofi beats"
[youtube] Extracting URL: https://youtube.com/watch?v=sv70epXyXTk
[youtube] sv70epXyXTk: Downloading webpage
[youtube] sv70epXyXTk: Downloading android player API JSON
[info] sv70epXyXTk: Downloading 1 format(s): 248+251
[dashsegments] Total fragments: 7
[download] Destination:  ~/Videos/lofi-beat.f248.webm
```
4. Video is downloaded to `/home/username/ ~/Videos/` (i.e., a `~/` directory in the home directory is created)

### Expected behavior

Video is downloaded to `~/Videos/`

### What I've tried

I've tried `ytdl_opts="-o /home/username/Videos/%(title)s.%(ext)s"` but the same behavior was resulted: it created the video in `/home/username/ /home/username/Videos`

### Information
 - OS: Linux
 - Terminal: kitty
 - Ytfzf version: 2.5.5

Thank you!

**Comment by Euro20179** [comment]
This should now be fixed in the development branch.

**Comment by kohane27** [comment]
Thank you for looking into this issue of mine and providing a prompt solution.

I've just tried the development branch and can confirm that the bug is fixed. The downloaded videos are in the correct directory.

Thank you again!
