### ISSUE TITLE
MacOS errors out when trying to play videos

### ISSUE THREAD

**Issue by hernan43** [pystardust/ytfzf#66]
I'm on Catalina(still) and had been a user of the one liner version of the script. I upgraded to the newer style and now when I try and view videos i get this:

> ➜  ytfzf git:(master) ytfzf "nintendo"
> 2021-03-03 11:38:20.166 mpv[80733:9519816] This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit(void) to debug.  This will be logged only once.  This may break in the future.
> Playing: h
> [file] Cannot open file 'h': No such file or directory
> Failed to open h.
> 
> Playing:
> [file] Cannot open file '': No such file or directory
> Failed to open .
> 
> Playing: ps://www.you
> No protocol handler found to open URL ps://www.you
> The protocol is either unsupported, or was disabled at compile-time.
> 
> Playing: ube.com/wa
> [file] Cannot open file 'ube.com/wa': No such file or directory
> Failed to open ube.com/wa.
> 
> Playing: ch?v=Super Smash Bros. Ul
> [file] Cannot open file 'ch?v=Super Smash Bros. Ul': No such file or directory
> Failed to open ch?v=Super Smash Bros. Ul.
> 
> Playing: ima
> [file] Cannot open file 'ima': No such file or directory
> Failed to open ima.
> 
> Playing: e - Mr. Sakurai Presen
> [file] Cannot open file 'e - Mr. Sakurai Presen': No such file or directory
> Failed to open e - Mr. Sakurai Presen.
> 
> Playing: s
> [file] Cannot open file 's': No such file or directory
> Failed to open s.
> 
> Exiting... (Errors when loading file)
> ERROR[#03]: Couldn't play the video/audio using the current player: mpv
> 	Try updating youtube-dl
> Check for new versions and report at: https://github.com/pystardust/ytfzf

I've tried it on both iTerm and the vanilla Terminal program. I've also tried both bash and zsh. I used the MacOS install instructions listed in the README file.

It lets me browse and select videos. But once I select one it errors out as above.

EDIT

It looks like the error is coming from mpv(0.33.0).

**Comment by Euro20179** [comment]
I think this has to do with the fact that the video you are trying to play is a waiting screen for a livestream/premier
Last time I checked livestreams work, you just have to wait for them to start, but can you try playing a different video.

**Comment by Euro20179** [comment]
> with partial chunks of the URL instead of the full URL.

yes

**Comment by westofer** [comment]
for debugging, can you run
`YTFZF_PLAYER="echo"` ytfzf Richard Stallman

@hernan43

**Comment by hernan43** [comment]
It really hates t's for some reason.

> ➜  ytfzf git:(master) YTFZF_PLAYER="echo" ytfzf Richard Stallman
> h  ps://www.you ube.com/wa ch?v=You can ge  arres ed wi hou  a reason - Richard S

**Comment by westofer** [comment]
I do belive this issue is caused by using sed instead of gsed

```
GNU sed interprets escape sequences like \t, \n, \001, \x01, \w, and \b. OS X's sed and POSIX sed only interpret \n (but not in the replacement part of s).

```

https://github.com/pystardust/ytfzf/blob/d57aeb1f43a6d95fe67550aae297138017554b51/ytfzf#L372-L374

`\t` is being interpetted as `t`
relaed to #37 , I wonder why this comment didn't get added https://github.com/pystardust/ytfzf/pull/37#issuecomment-786137908

**Comment by Euro20179** [comment]
my guess is this line is not selecting the video id from the data, and is instead selecting the title

`shorturls="$(echo "$selected_data" | sed -E -e 's_.*\|([^\|]+) *$_\1_')"`

i think @westofer might be right about the t thing

**Comment by Euro20179** [comment]
just, at the top of the script try adding
`alias sed=gsed`

**Comment by westofer** [comment]
if what @Euro20179 said works we can do a pull request with 
```
## For MacOS users
if [ "$(uname)" = "Darwin" ]; then
	alias sed='\gsed'
fi
``

as in https://github.com/pystardust/ytfzf/pull/37#issuecomment-786137908


please test it @hernan43 , thanks!

**Comment by Euro20179** [comment]
> relaed to #37 , I wonder why this comment didn't get added #37 (comment)

I'm like 99% sure it did get added, but it also got removed at some point and i forget why

**Comment by hernan43** [comment]
That alias line fixes it. 

I should have thought to try the GNU utils because in the one liner I had to do something similar for one of the components to get it to work.

**Comment by westofer** [comment]
nice! can you please make sure that this works? (i dont have mac :sweat_smile: )

```
# add at top of file
## For MacOS users
if [ "$(uname)" = "Darwin" ]; then
	alias sed='\gsed'
fi

```

**Comment by Euro20179** [comment]
> \gsed

Just wondering, why is there a \ here

**Comment by Euro20179** [comment]
This seems to be why the alias was removed
https://github.com/pystardust/ytfzf/pull/37#issuecomment-786141891

**Comment by westofer** [comment]
> Just wondering, why is there a \ here

dunno, don't question it, act like knowlegable

**Comment by windowswithoutborders** [comment]
I'm on macOS and never noticed, but then again one of the first things I did was replace all the bsd utilities with their gnu counterparts through the brew package manager and setup my path as per the [instructions](https://formulae.brew.sh/formula/gnu-sed#default) brew provides to reference them first. I think it would be sufficient enough to just mention it as a dependency specific to macOS in the readme.

Instructions from brew:
> GNU "sed" has been installed as "gsed".
If you need to use it as "sed", you can add a "gnubin" directory
to your PATH from your bashrc like:
>
>     PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"

**Comment by ffuentese** [comment]
The same happens in OpenBSD.

**Comment by westofer** [comment]
the solution is to install gnu sed or replace `\t` with real tabs

**Comment by pystardust** [comment]
I think it is better to use printf to show that it is an actual tab.
```sh
printf "1\t3\n" | sed "s/""$(printf '\t')""/2/"
printf "Tab:<\n>\n" | sed "N;s/\n/""$(printf '\t')""/"
```
Tell me if this works. It need to give an output like
```
123
Tab:<     >
```

**Comment by pystardust** [comment]
@westofer can you very if this works.

**Comment by westofer** [comment]
works with gnused

**Comment by westofer** [comment]
```sh
 printf "1\t3\n" | sed "s/""$(printf '\t')""/2/"
123
printf "Tab:<\n>\n" | sed "N;s/\n/""$(printf '\t')""/"
Tab:<	>

```
freebsd sed, works

**Comment by pystardust** [comment]
@hernan43 
I have added a fix. Update and let me know if it breaks again.

**Comment by hernan43** [comment]
The update is working for me. Thank you!
