### ISSUE TITLE
[Feature request]: View comments on the currently selected video.

### ISSUE THREAD

**Issue by HanoJing** [pystardust/ytfzf#663]
### Background

[✓] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Why do we need this feature?
In order to be able to comfortably view comments under the currently playing video.

### Feature
Description of your proposed feature.
Search, select a video and view the comments of the selected video, rather than `ytfzf -c comments link-to-video`.

### Alternative solutions to problem?
None

---
Is this already possible or am I missing something? 
Is this already possible when scraping `youtube,comments` and maybe switching to a scraper if that is possible?

**Comment by Euro20179** [comment]
It would be possible to make it so you can press `alt-c` but I am currently working on other things.

**Comment by Euro20179** [comment]
I tried adding in the aformentioned `alt-c` shortcut, however I felt that it was messy, so I created [this extension](https://github.com/pystardust/ytfzf/blob/development/addons/extensions/comments) . Basically just put it in a file called `~/.config/ytfzf/extensions/comments`, run `ytfzf -e comments`, and if you have another ytfzf open that's playing a video it'll automatically detect it and open the comments for that video.

**Comment by HanoJing** [comment]
Oooh amazing! Thank you so so much!
