### ISSUE TITLE
[BUG]: Bugs on ytfzf

### ISSUE THREAD

**Issue by robson-66** [pystardust/ytfzf#664]
Recently when I run ytfzf I get these errors as in the screenshot below

![ScreenShot](https://i.postimg.cc/VN728VQz/screen.png)

In addition, there is no sound in the videos being played.
I am asking you to intervene in this matter.

**Comment by HanoJing** [comment]
Yes, I had the very same issue, This is a video with mpv and is fixed in the latest version of mpv. 
https://github.com/mpv-player/mpv/issues/11392.

**Comment by robson-66** [comment]
You're absolutely right it was the mpv's fault, today on Arch Linux (which I'm using) there was an mpv update, and the problem was gone.
