### ISSUE TITLE
Possible MPV/youtube-dl error while trying to play video

### ISSUE THREAD

**Issue by m-GDEV** [pystardust/ytfzf#67]
I just installed this program after I saw its showcase on reddit.com/r/unixporn
I followed all the installation instructions and installed all of the dependencies. I also got the most up to date verison of youtube-dl.

Not sure what the error means.
Here is the video I was trying to watch: https://www.youtube.com/watch?v=mAFMJ1LnQu8

## Error given

Downloading Thumbnails................................
                                                    [ytdl_hook] ERROR: mAFMJ1LnQu8: YouTube said: Unable to extract video data 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
ERROR[#03]: Couldn't play the video/audio using the current player: mpv
	Try updating youtube-dl
Check for new versions and report at: https://github.com/pystardust/ytfzf

**Comment by westofer** [comment]
`youtube-dl --version` should produce an output equal to or greater than `2021.03.02`

incase youtube-dl is of desired version, please post the output of this command.

`YTFZF_PLAYER="echo" ytfzf Richard Stallman` choosing the first video

**Comment by Euro20179** [comment]
I don't know if this is what you did but someone asked in that thread if it worked on a raspberry pi so I tried it, got the same error you did here, and I had to install youtube-dl manually like this

`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`

`sudo chmod a+rx /usr/local/bin/youtube-dl`

**Comment by westofer** [comment]
can you send version info :3 

please send the output of `YTFZF_PLAYER="echo" ytfzf Richard Stallman` choosing the first video

thanks

**Comment by westofer** [comment]
oh that was @Euro20179 , I thought it was the original author :sweat_smile: 

thanks for the installation instructions :]

**Comment by Euro20179** [comment]
> I thought it was the original author

haha

**Comment by m-GDEV** [comment]
# Solution

It seems that my old installation of youtube-dl through pip was conflicting with the new installation. After uninstalling the pip version everything is working fine. 

Thanks for your help everyone!
