### ISSUE TITLE
[BUG]: when using --external-menu it doesn't respect --auto-select

### ISSUE THREAD

**Issue by Arrow-x** [pystardust/ytfzf#672]
### Describe the bug
when using `--external-menu` it doesn't respect `--auto-select`, and it shows the search results.
### To Reproduce
just use the two options together
### Expected behavior
To jump straight to quality selection when using `--formats` and shows them in `dmenu`
### Information
 - OS: Linux
 - Terminal: St
 - Ytfzf version: 2.5.5-1
- Output of `ls -l "$(which sh)"` (if you're using fish: `ls -l (which sh)`): 
`lrwxrwxrwx root root 4 B Thu Feb  2 07:38:44 2023  /usr/bin/sh ⇒ bash`
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

**Comment by Euro20179** [comment]
These options are inherently incompatible with each other as auto-select uses a custom menu. Auto select doesnt open the menu anyway, so just dont use external-menu.
