### ISSUE TITLE
[BUG]: -rii option now auto-plays first video without displaying menu?

### ISSUE THREAD

**Issue by CactusSoup** [pystardust/ytfzf#675]
### Describe the bug
My wrapper script for ytfzf calls `-rii` the first time in the day I attempt to use `ytfzf -D` to avoid problems with expired invidious servers. Whereas before this would silently refresh the instances but make no functional change, it is now no longer displaying any menu and instead appears to automatically try to play the first video it finds in a search result.

The behaviour is the same regardless of using `-D` or not.

### To Reproduce
`ytfzf <search term>`
`ytfzf -rii <search term>`

### Expected behavior
Second command will appear and behave identically to the first.

### Information
 - OS: Arch
 - Terminal: St
 - Ytfzf version: 2.6.0
 - Output of `readlink $(which sh)`: bash
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

Output of `ytfzf --version-all`:
- ytfzf: 2.6.0
- jq: jq-1.6
- curl: curl 8.0.1 (x86_64-pc-linux-gnu) libcurl/8.0.1 OpenSSL/3.0.8 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.10.0 nghttp2/1.53.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

### Additional context
No external configuration file, running fresh out the box.

**Comment by Euro20179** [comment]
are you using `-rii` or `--rii`?

`-rii` is actually `-r -i i`, whereas `--rii` does what you'd expect.

**Comment by CactusSoup** [comment]
Oh dang it. Thank you, must have somehow screwed up the script and chopped an "-" off!
