### ISSUE TITLE
[BUG]: could not read init

### ISSUE THREAD

**Issue by tokisuno** [pystardust/ytfzf#678]
### Describe the bug
only the audio plays without a video feed opening. issue is as seen (here)[https://github.com/mpv-player/mpv/issues/10366] 

### To Reproduce
use program and select video

### Expected behavior
video plays

### Information
 - OS: arch
 - Terminal: alacritty
 - Ytfzf version: 2.6.0
 - Output of `readlink $(which sh)`: bash
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

### Additional context
love the project

**Comment by Euro20179** [comment]
this happens for me but only randomly, try using the `-f` option to pick a format manually

**Comment by tokisuno** [comment]
yeah that works. kind of annoying since it takes a while for the video to load in the first place, and just adds more time between ytfzf searching, then selecting, then choosing resolution, then searching again, but i am using this more as a minimalist way to use youtube without distraction in case i need to find a lecture or something.

**Comment by Euro20179** [comment]
in fzf you can press alt-f to do the same thing as -f
