### ISSUE TITLE
[BUG]: ytfzf -cS   >> unsupported key: start  [ytfzf: 2.6.0]

### ISSUE THREAD

**Issue by har5ha** [pystardust/ytfzf#685]
Mpv plays the video from the scraped list of my subscriptions and "exits" with the following message in the terminal, even when **_is_loop=1_** is set in the _~/.config/ytfzf/conf.sh_   file

### To Reproduce

~  ytfzf --version
ytfzf: **2.6.0**

1) $ ytfzf -cS
Scraping Youtube channel: https://www.youtube.com/channel/Uxxxxxxxxxx/videos
Scraping Youtube channel: https://www.youtube.com/channel/UChxxxxxxxxx/videos
Scraping Youtube channel: https://www.youtube.com/channel/UCZuxxxxxxx/videos
**unsupported key: start**

2) Choose a video from by subscriptions 
3) mpv plays the video and "exits" with the following message in the terminal, even when  is_loop=1 is set in the ~/.config/ytfzf/conf.sh   file

     **"_unsupported key: start_"**

4) I have a single line in ~/.config/ytfzf/conf.sh  >> is_loop=1

### Expected behavior
After playing the video using mpv, YTFZF should return to my List of Subscriptions

### Information
 - OS: Kali Linux
 - Terminal: URXVT/Kitty/Alacritty
 - Ytfzf version: ytfzf: 2.6.0
 - Output of `readlink $(which sh)`: $

**Comment by Euro20179** [comment]
What version of fzf do you have

**Comment by har5ha** [comment]
> What version of fzf do you have
 A very old one (fzf 0.30.0), I upgraded to  fzf 0.42.0 (debian) after going through your comment. Now it works fine after the upgrade. 

Thanks! a lot, for your time.

PS: This can be closed

**Comment by har5ha** [comment]
Working after fzf upgraded to 0.42.0
