### ISSUE TITLE
[BUG]: Thumbnail not working after upgrade to Debian 12

### ISSUE THREAD

**Issue by pinipon** [pystardust/ytfzf#698]
### Describe the bug
Everything worked fine in Debian 11, `ytfzf` version 1.1.0
I have uninstalled `ytfzf` and all its dependencies before upgrading to Debian 12
After upgrading to Debian 12, installed `ytfzf` and its dependencies from the debian repo.
Now `ytfzf` version 2.5.4, `fzf` 0.38.0, `ueberzug` 18.1.9, thumbnail is not working and following message appears on the left:
`/usr/bin/ytfzf: 2521: cannot create : Directory nonexistent`

If I use `ytfzf -t -T mpv` everything works fine.
But due to `mpv` thumbnail preview is loaded on separate window, I need to work with `ueberzug`.
`chafa` and `catimg` are not an option because already tried and suffer from low pixel resolution.

On the other hand, running `ytfzf 1.1.0` on the same context (Debian 12, `fzf` 0.38.0, `ueberzug` 18.1.9), everything works fine and thumbnails are loaded perfectly on the terminal. To be able to run `ytfzf 1.1.0`, I had to symlink `ln -s /usr/bin/yt-dlp /usr/local/bin/youtube-dl`

### Information
 - OS: `Debian 12 stable`
 - Terminal: `LXTerminal`
 - Ytfzf version: `2.5.4`
 - Output of `readlink $(which sh)`:
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file: `file is empty`

**Comment by Euro20179** [comment]
Try upgrading to ytfzf 2.6.1

**Comment by pinipon** [comment]
Re-trying `ytfzfz` 2.5.4 from debian repo on freshly installed Debian 12, bug still the same.
Uninstalling 2.5.4 and and installing 2.6.1 from github solve the problem.
Thanks for the help.
