### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by cristianochene** [pystardust/ytfzf#70]
➜  ~ ytfzf test
[ytdl_hook] ERROR: QZ36oaXHkOU: YouTube said: Unable to extract video data
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.

Exiting... (Errors when loading file)
ERROR[#03]: Couldn't play the video/audio using the current player: mpv
	Try updating youtube-dl
Check for new versions and report at: https://github.com/pystardust/ytfzf

**Comment by Euro20179** [comment]
Try updating youtube-dl form their website

https://ytdl-org.github.io/youtube-dl/download.html

or run

`sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl`

`sudo chmod a+rx /usr/local/bin/youtube-dl`

**Comment by cristianochene** [comment]
its now working, thank you very much!

**Comment by westofer** [comment]
can you close the issue :3

**Comment by cristianochene** [comment]
Sure, sorry, I'm not used to this platform yet. Thanks again!
