### ISSUE TITLE
[Feature request]: Recognize flatpak installation of mpv

### ISSUE THREAD

**Issue by DocKDE** [pystardust/ytfzf#700]
### Background

[x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
I was trying out ytfzf on Fedora Silverblue and had the issue that it doesn't recognize mpv when it's installed as a flatpak. 

### Feature
I suppose this is not a trivial change but I wondered if there would be interest in having ytfzf also work with a flatpak installation of mpv.

### Alternative solutions to problem?
Of couse the mpv package can be layered in Silverblue to avoid this issue but it's not really the blessed way of doing things.

**Comment by Euro20179** [comment]
I dont really want to add flatpak mpv support directly in ytfzf, so instead I made an addon.

If you make a folder in `~/.config/ytfzf` called `url-handlers` you can make a file called fmpv, and put the following code in it

```sh
#!/bin/sh

IFS="$(printf '\t')" read -r ytdl_pref is_audio_only is_detach video_pref audio_pref url_handler_opts
flatpak run io.mpv.Mpv --version > /dev/null 2>&1 || {
    printf "\033[31mthe flatpak version of mpv is not installed\033[0m\n"
    exit 1
}

detach_cmd() {
	nohup "$@" >"/dev/null" 2>&1 &
}

video_player () {
	[ "$is_detach" -eq 1 ] && use_detach_cmd=detach_cmd || use_detach_cmd=''
	$use_detach_cmd flatpak run io.mpv.Mpv --ytdl-format="$ytdl_pref" $(eval echo "$url_handler_opts") "$@"
}

audio_player() {
	case "$is_detach" in
        0) flatpak run io.mpv.Mpv --no-video --ytdl-format="$ytdl_pref" $(eval echo "$url_handler_opts") "$@" ;;
        1) detach_cmd flatpak run io.mpv.Mpv --force-window --no-video --ytdl-format="$ytdl_pref" $(eval echo "$url_handler_opts") "$@" ;;
	esac
}

case "$is_audio_only" in
    0) video_player "$@" ;;
    1) audio_player "$@" ;;
esac
```

Give the file execute permissions,

then you should be able to run `ytfzf -u fmpv ...` and it should use the flatpak version.

lemme know if there's any bugs with it.

**Comment by DocKDE** [comment]
I understand not wanting to embed it directly into ytfzf. I tried the addon and it works without issues so far. If anything comes up, I'll give the word but I'll close the issue for now. Thanks a lot for the quick response and your work!
