### ISSUE TITLE
Using submenus

### ISSUE THREAD

**Issue by behindthearcane** [pystardust/ytfzf#709]
### Before Making This Post
* [x] I have taken a look at both man pages, `ytfzf(1)` and `ytfzf(5)`

### What do you need help with?
I am struggling to understand how submenus work. Basically, I have a subscriptions file and have configured ytfzf to scrape subscriptions. I want this to open up ytfzf with a list of the channels which when selected would enter a submenu for that specific channel. Is this possible?

I have added `enable_submenus=1` to my conf.sh file although I think that was already the default.

Any help would be greatly appreciated.

Edit:
I know that I can access a channel submenu when using the default search and entering entries starting with [channel]. I want to know if there is similar functionality in the subscription feed.

**Comment by Euro20179** [comment]
> I want to know if there is similar functionality in the subscription feed.

Currently this is not possible, however I would be willing to add something that just takes a list of channel urls and lets you select one of them to open in a submenu, maybe something like `ytfzf -c channels ./path/to/channels/list`, and by default if no path is given, it would use your subscriptions file as the list.

> I know that I can access a channel submenu when using the default search and entering entries starting with [channel]

Correct,

**Comment by behindthearcane** [comment]
Thank you. I appreciate the offer, but I can use a simple shell script as a solution for now. Simply wanted to ensure there was no baked in solution that I was missing.
I appreciate all the work that is being done with this project.

**Comment by Flaried** [comment]
> Currently this is not possible, however I would be willing to add something that just takes a list of channel urls and lets you select one of them to open in a submenu, maybe something > I would be willing to add something that just takes a list of channel urls and lets you select one of them to open in a submenu, maybe something like `ytfzf -c channels ./path/to/channels/list`, and by default if no path is given, it would use your subscriptions file as the list.

Is there a way to currently do this? basically I want 2 subscription files and be able to switch between the
