### ISSUE TITLE
[BUG]: Misaligned description items on start with --preview-side=bottom

### ISSUE THREAD

**Issue by UndeadDevel** [pystardust/ytfzf#712]
### Describe the bug
When launching with options `-t --preview-side=bottom` the info columns in the video title list are misaligned (this was launched with some more options, but I reproduced it with those named as well), see screenshot.

### To Reproduce
`ytfzf -t --preview-side=bottom video`
### Expected behavior
No misaligned column text.
Note that using `Ctrl+P` fixes the issue, but only until the next video is launched, at which point the issue returns.

### Screenshots
![bug](https://github.com/pystardust/ytfzf/assets/30495439/ee1bfd39-af76-405a-b87c-4e38215133a5)

### Information
 - OS: Debian 12 running inside QubesOS
 - Terminal: gnome-terminal
 - Ytfzf version: 2.6.1
 - Output of `readlink $(which sh)`: `dash`

### Additional context
This screenshot also demonstrates how it would be nice to be able to get rid of the info panel when using the `-t` option and an external thumbnail viewer, because it unnecessarily takes up valuable workspace real estate.

**Comment by Euro20179** [comment]
This should be fixed in f18630f

**Comment by UndeadDevel** [comment]
Confirmed fixed, thank you!
