### ISSUE TITLE
[Feature request]: Enable external thumbnails without info pane in fzf or preserve thumbnail viewer window

### ISSUE THREAD

**Issue by UndeadDevel** [pystardust/ytfzf#713]
### Background

- [x] I have checked ytfzf(1) and ytfzf(5) or the wiki before creating this.

### Problem
Decent quality thumbnails are difficult to get working properly on some setups for various reasons, such that an external thumbnail viewer, such as mpv, will have to be used. Comfortable usage entails not having to reposition the thumbnail viewer window after every video (since that external window closes when the video is launched), so the terminal running ytfzf needs to be made smaller in order for there to be enough space for the thumbnail window on the workspace; this, in turn, reduces the amount of video titles displayed in the video list, because now not the whole workspace is used by ytfzf and half of the terminal window is taken up by the info pane (in which the thumbnail would normally be). See screenshot in #712 for a visual demonstration.

### Feature
It seems there are two solutions: one is to add a command line option that will not generate the info pane when the -t option is used, so basically just display the list like without -t but nevertheless launch an external thumbnail viewer window.

### Alternative solutions to problem?
Another solution would be to reuse the thumbnail viewer window, because that window can then be pinned and raised permanently and positioned properly only once until the end of the session instead of after every video.

**Comment by Euro20179** [comment]
I have added a way to say how large the preview window is in this commit: 42937fa688

you can set `preview_window_width=0%` in the config or run `preview_window_width=0% ytfzf ...` in order to get rid of the preview.

I'm also going to attempt to implement reusing the thumbnail window but i'm not sure how well that will go.

**Comment by UndeadDevel** [comment]
Confirmed working and it solves the problem for me, thanks for the blazingly fast response!
