### ISSUE TITLE
Use default terminal colors

### ISSUE THREAD

**Issue by ThatOneCalculator** [pystardust/ytfzf#72]
Hello! I was wondering if there's a way I could make the fzf menu use my default terminal colors instead of the gray for border and the light blue/hot pink for the selectors.
![image](https://user-images.githubusercontent.com/44733677/109911812-9f394500-7c5f-11eb-91ee-56fe7472accc.png)

**Comment by westofer** [comment]
add `YTFZF_ENABLE_FZF_DEFAULT_OPTS=1` to `~/.config/ytfzf/conf.sh`

then pick a colorscheme https://github.com/junegunn/fzf/wiki/Color-schemes

I assume you can also add the color scheme to `~/.config/ytfzf/conf.sh` but without using `export` keyword

**Comment by Euro20179** [comment]
do what @westofer said but
to add the color scheme add this to the `~/.config/ytfzf/conf.sh` file
`FZF_DEFAULT_OPTS="fzf options go here"`
for exmple
`FZF_DEFAULT_OPTS="--color=light,fg:232,bg:255,bg+:116,info:27"`

**Comment by westofer** [comment]
dunno how I missed that :+1: 
Ignore my comment completly.

`FZF_DEFAULT_OPTS` is enough

**Comment by ThatOneCalculator** [comment]
I don't have a `~/.config/ytfzf/conf.sh`, I should create it, yea?

**Comment by Euro20179** [comment]
yes

**Comment by Euro20179** [comment]
> FZF_DEFAULT_OPTS is enough

You still need to put `YTFZF_ENABLE_FZF_DEFAULT_OPTS=1` or ytfzf will ignore FZF_DEFAULT_OPTS

**Comment by ThatOneCalculator** [comment]
Awesome, thank you! Issue resolved! Great work on the repo, and thank you all for the fast replies.
