### ISSUE TITLE
[BUG]: using nonalphanumeric characters in optstring produces unspecified results

### ISSUE THREAD

**Issue by r1bilski** [pystardust/ytfzf#724]
### Describe the bug
Currently, the `optstring` passed to `getopts` contains `-` character. This causes my shell to fail running `ytfzf` in POSIX mode.

### To Reproduce
Run `ytfzf` with no arguments.

### Expected behavior
`-` character is not used in `optstring`

### Information
- OS: Artix Linux
- Terminal: alacritty 0.13.1
- Ytfzf version: master / 2.6.2
- Output of readlink $(which sh): yash (v2.55)

### Additional context
https://pubs.opengroup.org/onlinepubs/9699919799/
> The use of other option characters that are not alphanumeric produces unspecified results.

**Comment by Euro20179** [comment]
there's a variable called long_opt_char which is the char that should be used for long-opts, by default it's `-` because every shell i tested supports it, however i kept it an option to make it posix compliant
put
```
long_opt_char=v
```
in your config.

**Comment by r1bilski** [comment]
I saw this option and already applied it. 
Thanks.
