### ISSUE TITLE
How do I change the default quality of the videos?  

### ISSUE THREAD

**Issue by joaquin-good** [pystardust/ytfzf#733]
### What do you need help with?
I'm searching and I can't find how to change the default video quality settings, but nothing, they told me that in .config but neither.

**Comment by cv1618** [comment]
I have this line in $HOME/.config/ytfzf/conf.sh
`video_pref="bestvideo[height<=?1080]+bestaudio/best"`
It will play the video in 1080 if available but will ignore 4k.

**Comment by joaquin-good** [comment]
> I have this line in $HOME/.config/ytfzf/conf.sh
> `video_pref="bestvideo[height<=?1080]+bestaudio/best"`
> It will play the video in 1080 if available but will ignore 4k.

I get an error when running the script, it says "permission denied"

**Comment by joaquin-good** [comment]
> I have this line in $HOME/.config/ytfzf/conf.sh
> `video_pref="bestvideo[height<=?1080]+bestaudio/best"`
> It will play the video in 1080 if available but will ignore 4k.

It worked for me, you really saved me, I appreciate it very much, thank you very much!!
