### ISSUE TITLE
[BUG]: Unable to extract uploader id;

### ISSUE THREAD

**Issue by mrintroverrt** [pystardust/ytfzf#740]
### Screenshots
![image](https://github.com/pystardust/ytfzf/assets/118121673/f0f962d4-0fe8-4e93-b22f-b990670b0f57)

### Information
 - OS:Ubuntu Ubuntu 22.04.4 LTS
 - Terminal: bash
 - Ytfzf version: current

```
prasaanth@lenovo:~/ytfzf$ ytfzf 
Search
> pewdiepie
Scraping YouTube (with https://invidious.materialio.us) (pewdiepie, pg: 1)
[ytdl_hook] ERROR: [youtube] MJDtQTTAogk: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
```

i have updated yt-dlp to the latest version also

**Comment by Euro20179** [comment]
yt-dlp is often extremely outdated in debian and debian derivatives.

Try uninstalling yt-dlp, then reinstalling with `pip3 install yt-dlp`

**Comment by mrintroverrt** [comment]
Thanks Fixed now its working
