### ISSUE TITLE
Multiple sessions break thumbnails

### ISSUE THREAD

**Issue by KrakatauiHD** [pystardust/ytfzf#75]
Thumbnails do not show properly if more than one session with thumbnails enabled exists on the system.
The issue probably originates from the hard-coded variables for ueberzug (line 230-232).

**Comment by pystardust** [comment]
@KrakatauiHD 
Yes just realised it. We might need to create tmp files using mktemp and use that as the uberzug file.
Also the thumbnails are wiped out when the script is run. So we will need to add checks to not delete thumbnails when another session is open. The thumbnails have unique names so it woudn't be a problem sharing the same dir.

**Comment by Euro20179** [comment]
the thumbnails break because `FIFO="/tmp/ytfzf-ueberzug-fifo` is hardcoded but from what I see, it has to not be influenced by a random variable because each time a new video is selected it re-calls the entire script with the -U flag and it will generate  a different file, the solution is to give it a name that is unique but will not change when reloading the script, I have no idea how to do that

**Comment by westofer** [comment]
`mktemp`

`mktemp (1)           - create a temporary file or directory`

**Comment by Euro20179** [comment]
> mktemp

this has randomness in it, Xs will be replaced with random characters, also the file needs to be "a named pipe" which mkfifo does

**Comment by Euro20179** [comment]
there could be a different solution like not recalling the script every time somehow but i have no idea

**Comment by pystardust** [comment]
Exporting variable is a really nice implementation. We also need to manage how the images are being deleted. Currenly the images are deleted when the script is run.
What if we have a pid file that determines if a session is running.
Every time a session is run, the pid is appended to the file. And once the session is about to end we check if there is any process running from the pids in the pid file. 
If so then we do not delete the pid file or the thumbs and exit.
Else we delete the pid file and the thumbs.

**Comment by Euro20179** [comment]
I don't fully understand what is happening in your description, and I have to go to school, but if someone would like to give this a shot, then you should.

**Comment by pystardust** [comment]
@KrakatauiHD 
https://github.com/pystardust/ytfzf/tree/multi-session
I have added a branch for this.
It seems to be working well. Ill merge it after testing it a little more

**Comment by pystardust** [comment]
@KrakatauiHD The feature has been merged
