### ISSUE TITLE
Thumbnails don't render in st or alacritty

### ISSUE THREAD

**Issue by paniash** [pystardust/ytfzf#77]
I'm testing this on Artix linux with dwm. As clearly mentioned in the README, running with `-t` does download thumbnails but doesn't render on the terminal. This happens on both st and alacritty. I only receive the message `Loading...` at the placeholder of the thumbnails.

## Screenshots
**st**:
![st-issue](https://user-images.githubusercontent.com/59497618/110006301-7c7e5d80-7d3f-11eb-992a-28737504241e.png)

**alacritty**:
![pic-full-210304-2312-58](https://user-images.githubusercontent.com/59497618/110006327-830cd500-7d3f-11eb-90f3-a9e1348e9790.png)

**Comment by westofer** [comment]
do you use fish shell by any chance?

**Comment by paniash** [comment]
> do you use fish shell by any chance?

No. I'm using zsh.

> also you have ueberzug installed?
Yes.

**Comment by paniash** [comment]
Ok, so I tried it with kitty and termite. I'm facing the exact same issue on those as well. Not sure what's going on.

**Comment by Ritte88** [comment]
I tried out bash (usually run zsh) with alacritty/gnome terminal. Did not  work with thumbnails. 
Running Arch/Wayland.

**Comment by Euro20179** [comment]
> Running Arch/Wayland.

ueberzug relies on X, if you are running anything other than X thumbnails won't work

**Comment by pystardust** [comment]
@paniash Are you using swallow patch?
Bugswriter also had this issue. Dwm is trying to alter the image previews for somereason.

**Comment by paniash** [comment]
@pystardust Yes, I am using swallow patch. But that's only particular to st. Alacritty, kitty and termite don't use swallow but the issue persists. Also, just to be sure, I ran `ytfzf -t` on qtile as well and I'm facing the same issue once again.

**Comment by pystardust** [comment]
Thats strange, are you using X or Wayland as Ritte88 asked?
Images work consistantly only on X
I will test it on qtile. 
On dwm undoing the swallow patch had fixed the problem for bugswriter

**Comment by paniash** [comment]
I'm on X11.

**Comment by GNUxeava** [comment]
It was working last time but after seeing this issue, it failed. Ueberzug apparently had a memory leak, filling RAM and half my swap.

**Comment by GNUxeava** [comment]
Also, I face this weird issue, don't know if it has to do with ranger or ueberzug. It fails to preview images unless I open it in an external program (feh in my case). After that the images preview correctly as intended, even on other instances of ranger. After this, I tried reproducing your issue and it worked.
Terminal emulator: Alacritty (works on kitty as well)
Shell: fish
![2021-03-05-173946_1920x1080_scrot](https://user-images.githubusercontent.com/21287366/110114098-1a266b00-7dda-11eb-9856-fdb243d15f61.png)

**Comment by paniash** [comment]
> Let me try it on other window managers and see if the issue still persists.

Doesn't seem to work with i3 either. Doesn't seem to be a WM specific issue.

**Comment by GNUxeava** [comment]
Alright. I tried reproducing the issue again just to be sure. This time it failed in all of the cases, even after having an instance of ueberzug running (by having it preview an image in ranger). It straight up eats all of my memory and the only solution is to kill it. Now I wonder how it worked in 2 out of like 10 cases.
![2021-03-05-175909_1920x1080_scrot](https://user-images.githubusercontent.com/21287366/110116155-1811db80-7ddd-11eb-84d8-df0e67f82b09.png)

**Comment by GNUxeava** [comment]
Okay. This is clearly an example of heisenbug. Nothing changed and it works now. Tried twice.
![2021-03-05-181146_1920x1080_scrot](https://user-images.githubusercontent.com/21287366/110116991-4e038f80-7dde-11eb-8d25-a6f4161c5137.png)

**Comment by pystardust** [comment]
@GNUxeava 
I have just tested it on fish. There seems to be a problem with fish shell.
I had the same issue: memory and cpu spikes
Try running it bash/dash/zsh (for thumbnails )
I will need to see what exactly is the problem with fish.
I has something to do with ueberzug and fish combined together. Cause without images it seems to work smooth on fish.

**Comment by westofer** [comment]
fish has problems even on `ranger` for me

**Comment by GNUxeava** [comment]
Can confirm works as expected on zsh.
It works well without thumbnails on fish.
![2021-03-05-191314_1920x1080_scrot](https://user-images.githubusercontent.com/21287366/110123484-f3bafc80-7de6-11eb-9356-3c744284aaaa.png)

**Comment by GNUxeava** [comment]
> fish+ueberzug has problems even on `ranger` for me

Can confirm. In fish I have to open it in external image viewer for previews to work in ranger.

**Comment by westofer** [comment]
related:

https://webcache.googleusercontent.com/search?q=cache:1PuQcVHbN8wJ:https://github.com/seebye/ueberzug/issues/116+&cd=1&hl=en&ct=clnk&gl=sa

issues removed? can't find a direct link

**Comment by westofer** [comment]
works perfect with latest fish version `fish-git` on AUR (`3.1.2-2054-g254729f86`)

**Comment by paniash** [comment]
Well, doesn't work for me on bash or zsh. :-(

**Comment by pystardust** [comment]
@paniash Lets try debugging
First lets check if ueberzug even works independently
Make an executable file `ubtest.sh`
```sh
#!/bin/sh

[ -z "$1" ] && { echo "Usage: ubtest.sh  <image>" ; exit; }

FIFO="ytfzf-test-pipe"

[ -e "$FIFO" ] || mkfifo "$FIFO"

ueberzug layer --parser json <> "$FIFO" & 

read ueberzug_info << EOF
{ "action": "add", "identifier": "test", "path": "$1", "x": 0, "y": 0, "scaler": "fit_contain", "width": 50, "height": 50 }
EOF

echo "$ueberzug_info" > "$FIFO"
sleep 5

rm "$FIFO" 
```

run it on an image
```
./ubtest.sh some.png
```

**Comment by paniash** [comment]
> First lets check if ueberzug even works independently

Good idea. Looks like ueberzug fails to work independently as you suspected. This is the error log that I get on running `./ubtest.sh some.png`

```sh
Traceback (most recent call last):
  File "/usr/bin/ueberzug", line 33, in <module>
    sys.exit(load_entry_point('ueberzug==18.1.9', 'console_scripts', 'ueberzug')())
  File "/usr/lib/python3.9/site-packages/ueberzug/__main__.py", line 55, in main
    module.main(options)
  File "/usr/lib/python3.9/site-packages/ueberzug/layer.py", line 204, in main
    display = xutil.get_display()
  File "/usr/lib/python3.9/site-packages/ueberzug/xutil.py", line 60, in get_display
    return Xdisplay.Display()
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.9/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'
```

**Comment by Euro20179** [comment]
i searched that bottom error (these solutions are from programs that use ueberzug but it might be worth trying anyway) and found 2 solutions:
* deleting .Xauthority and relogging
* adding DISPLAY=:0 before running ytfzf (`DISPLAY=:0 ytfzf search`)

**Comment by pystardust** [comment]
How have you installed ueberzug? Trough `pip` ?
Since you are using artix try the latest version from arch repos using pacman
And as Euro mentioned try
```
DISPLAY=:0 ./ubtest.sh some.png
```

**Comment by paniash** [comment]
As per @Euro20179's suggestion, I deleted `.Xauthority` and relogged. I still don't know what was the issue (can someone explain?) but it works fine now!!!

**Comment by arilebedey** [comment]
I ran into this issue too and solved it by uninstalling ueberzug and installing the latest build, `yay -S python-ueberzug-git`
