### ISSUE TITLE
Loop mode

### ISSUE THREAD

**Issue by cybarspace** [pystardust/ytfzf#8]
Please consider adding a flag to loop the currently playing song until the user presses `q` to quit `mpv`. `mpv` has a `--loop` flag for that, so I'm assuming you need only to call that flag in your script when passed a custom loop flag.

**Comment by pystardust** [comment]
Okay Ill check the exit codes for mpv with different modes of exiting. Ill do this asap

**Comment by cybarspace** [comment]
Sure, no problem. Take your time, no rush. It's admirable enough that you're so invested in this project. It's really good, portable, simple, and easy to integrate into scripts.

**Comment by pystardust** [comment]
What you mean by loop is repeating the same track over and over right?
I can an option but I suggest pressing capitol L on the mpv player. This would look the current file till you stop it. I feel that is much easier than parsing in an option. What do you think?

**Comment by pystardust** [comment]
If you want to listen to music here are my tips
* capitol L for loop 
* capitol J for lyrics

**Comment by pystardust** [comment]
Also with regards to another issue, I have added loop prompt feature (-l), which repeats the same videos prompt after closing a video ( so as to continue watching). 
Now if you do something like
`ytfzf  -mal   <songname>`
this will loop the first choice. (to end you need to press ^C on the terminal)
I wouldn't recommend this way, cause mpv has it inbuilt with L

**Comment by cybarspace** [comment]
> I suggest pressing capital L on the mpv player. This would loop the current file till you stop it. I feel that is much easier than parsing in an option. What do you think?

Absolutely. I wasn't actually ware of that option. This will do fine for now.

> I have added loop prompt feature (-l)

I just tried it out. I think there's probably more that can be done with this, but you have done a lot for us already. Maybe give it some more thought and polish. Meanwhile I'll create a fork and try to adapt your code to suit my use case, since I use it for extremely simple things. Your script is actually too powerful for me... :sweat_smile: (I don't use download, cache, history, format, lyrics, etc.)

Thanks for all your time and effort. :blush:
I'll be closing this issue now, as I have technically found a solution/workaround.

**Comment by cybarspace** [comment]
Lol, for whatever reason, my mind is telling me to translate your script to Python :v
It'll take some time since I'm not good at either shell or Python, but I'll do it anyway.
