### ISSUE TITLE
Windows support ?

### ISSUE THREAD

**Issue by revskill10** [pystardust/ytfzf#81]
Hi, great project.

Could i use this on Windows machine ?

**Comment by Euro20179** [comment]
to my knowledge the only way you could use this on windows is if you have WSL installed

**Comment by pystardust** [comment]
@revskill10 
It works on WSL (without thumbnails).

**Comment by revskill10** [comment]
@Euro20179 @pystardust Thanks for the suggestion. 

But when i say Windows, i mean pure windows environment, not WSL or any linux-like virtual machine.

One of the reason not to use WSL is that WSL consumed too much RAM for me, and i don't even know the benefit of WSL instead of just virtualbox (RAM consumption is almost the same, so what's the WSL's benefit ?)

**Comment by cybarspace** [comment]
> what's the WSL's benefit?

WSL has better performance and is more integrated afaik.

You could try Cygwin, but I don't know how well that'd work.

By nature, Windows doesn't support POSIX shell scripts, just like how Linux doesn't support BAT batch scripts (not as far as I know). Their syntax is considerably different.

**Comment by Euro20179** [comment]
i was curious if this worked in powershell since there are a lot of aliases to make it more bash-like but the test or [ command works differently in bash so it didn't work (there's probably a lot more that doesn't work but yeah)

**Comment by pystardust** [comment]
@revskill10 
Windows cannot interpret posix on its own. We can try implementing aliases to make it bash like, but that would make it really painful. It would be much easier rewriting the script in powershell. 
Currently this script will stick to posix, I suggest WSL as cyberspace has mentioned. Or anyother way that allows running posix scripts on windows.

**Comment by revskill10** [comment]
@pystardust Due to the RAM consumption reason i said above, WSL is a NO to me. On Windows 10, a WSL could consume at least 6-8 GB on a laptop machine, it's a non-sense to me (and Windows User to use WSL).

The issue exists for only one reason, make this project runnable on pure Windows/Cydwin environment (without any kind of virtual machine).

I see i can use Docker or WSL in 1 minute to setup, but it's a different issue.

**Comment by cybarspace** [comment]
> On Windows 10, a WSL could consume at least 6-8 GB on a laptop machine

That's really too high. I didn't get that much ever. Something else is probably at play but it doesn't matter. No need to use WSL.

> The issue exists for only one reason, make this project runnable on pure Windows/Cygwin environment

Is it not already runnable in Cygwin? 🤔
What errors do you get after installing all dependencies and starting it via Cygwin?

**Comment by BurhanDanger** [comment]
I checked `ytfzf` under cygwin. It's working nicely. Did not test thumbnail though.

**Comment by cybarspace** [comment]
> I checked `ytfzf` under cygwin. It's working nicely. 

Marvelous.

> Did not test thumbnail though.

Unlikely to work since ueberzug needs X11, but you can try installing it and see if you'd like: `pip install ueberzug`
