### ISSUE TITLE
Feature request: Bring us back to the search result after video is over. Also rofi/dmenu support

### ISSUE THREAD

**Issue by danrobi11** [pystardust/ytfzf#9]
Hi. First, thank you for sharing your ytfzf script.
It would be useful to be able to return to the search result after the video is over. 
That way we dont have to send search request to youtube over and over for the same search.
Same like [yt](https://github.com/sayan01/scripts/blob/master/yt) does it.

Optional: run ytfzf with rofi/dmenu. Would be nice to be able to use ytfzf with rofi or dmenu.

**Comment by pystardust** [comment]
yes noted, ill work on it

**Comment by pystardust** [comment]
@danrobi11 
I have added the prompt loop as you have requested. To enable it pass in the -l option. I have updated the readme stating so.
I had tried dmenu, but for some reasons it couldn't handle so much text input. 
I am working on dmenu.

**Comment by pystardust** [comment]
I have added dmenu support. Use -D option.

**Comment by pystardust** [comment]
@danrobi11  f there is anything else let me know. I am closing this issue.

**Comment by danrobi11** [comment]
Thank you much!

I think you're not a dmenu/rofi user ;) 
You should try these below. Rofi is very snappy

You can use rofi by adding:

- ```prompt_menu='tr -d "$(printf "\t")" | rofi -dmenu -p "Search" '``` line 169 instead of ``` dmenu -i -l 30 ```


Also, this change will display all the ytfzf column in rofi with ```title_len=$((frac * 3 - 2))``` line 72 instead of ```* 6 - 1```
