### ISSUE TITLE
mpd for audio stream ?

### ISSUE THREAD

**Issue by thomastrinn** [pystardust/ytfzf#92]
Hi,
really great work! I like it! :)

I was playing around with mpc, and I got the following command:

`
youtube-dl -f bestaudio -g uIphNGLBeZQ | mpc add 
`

It works, with `mpc play` it plays the song.

But I can not find the way to use it with ytfzf. Could you help?

Thx,
Thomas

**Comment by pystardust** [comment]
I guess it you change the player variable
Considering 
```sh
youtube-dl -f bestaudio "$URL"  | mpc add
```
works, write a script as show  below
```sh
#!/bin/sh
youtube-dl -f bestaudio  "$@" | mpc add
```
And add 
```sh
YTFZF_PLAYER="/path/to/script"
```
Also make sure you do not have any default format preference (since you just want the raw url)
```sh
YTFZF_PREF=""
```

**Comment by thomastrinn** [comment]
Hi!

Yes, it works! It will be added to the mpc queue!

Thx!
